#!/usr/bin/env bash
# GENERATED by .github/scripts/dash-gen (fleet_compose) — do not edit.
# Regenerate with: tools/dash gen compose
#
# One database and one role per project that declares `database: true`
# in _data/projects.yml. This is what replaces the eight separate
# Postgres containers the fleet used to run.
#
# Idempotent on purpose: Postgres runs this directory ONCE, on an empty
# data dir, so a volume created before a project was added would never
# see it. `dash up` pipes the same script through psql on every start,
# and every statement below is guarded.
set -euo pipefail

PW="${FLEET_DB_PASSWORD:-fleetdev}"
SUPER="${POSTGRES_USER:-postgres}"

ensure() {  # $1 = database, $2 = role
  psql -v ON_ERROR_STOP=1 --username "$SUPER" --dbname postgres <<-SQL
	SELECT 'CREATE ROLE "$2" LOGIN PASSWORD ''$PW'''
	 WHERE NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '$2')\gexec
	SELECT 'CREATE DATABASE "$1" OWNER "$2"'
	 WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '$1')\gexec
	GRANT ALL PRIVILEGES ON DATABASE "$1" TO "$2";
	SQL
  echo "  fleet-db: ensured $1 (owner $2)"
}

ensure "barodybroject" "barodybroject"
ensure "aieo" "aieo"
ensure "law_ai" "law_ai"
ensure "fredgar_ai" "fredgar_ai"
ensure "ai_seed" "ai_seed"
ensure "djangoerp" "djangoerp"
