"""One palette for every surface: the Harness Console's CSS and the TUI's Textual theme.

The base roles are bashOS's own (`bashos.desktop.theme`, cyan-led, dark and
light), copied verbatim so the terminal dash, the browser console and the
bashOS desktop read as one product. When bashOS publishes `theme v1` as data
(docs/TERMINAL-FRAMEWORK.md §3.3) this table is what gets replaced by an import.

Two surfaces render from it:

  css()             CSS custom properties under the console's role names
                    (--page, --ink, --accent, --good, …) for light, the OS dark
                    preference, and an explicit data-theme toggle.
  textual_themes()  textual.theme.Theme objects, registered by the TUI.

Health levels (red / amber / green) are the same three colours everywhere: a
red dot in the terminal and a red chip in the browser mean the same thing.
"""
from __future__ import annotations

from typing import Any

# bashOS base roles (desktop/theme.py) + the roles bashOS leaves implicit that a
# dense dashboard needs: secondary ink, muted text, gridlines, hairline borders.
TOKENS: dict[str, dict[str, str]] = {
    "dark": {
        "primary": "#00b7c3", "secondary": "#4ec9b0", "accent": "#c586c0",
        "foreground": "#d4d8de", "background": "#101418", "surface": "#151a20", "panel": "#1d242e",
        "success": "#4ec9b0", "warning": "#d7ba7d", "error": "#f14c4c",
        "ink2": "#a9b1bb", "muted": "#7b8591", "grid": "#2a323c", "border": "rgba(212,216,222,0.12)",
    },
    "light": {
        "primary": "#008a94", "secondary": "#1f7a68", "accent": "#8f4d8a",
        "foreground": "#20262c", "background": "#f4f6f8", "surface": "#ffffff", "panel": "#e8ecf0",
        "success": "#1f7a68", "warning": "#8a6d1f", "error": "#c23434",
        "ink2": "#4a545e", "muted": "#6b7580", "grid": "#d9dee3", "border": "rgba(32,38,44,0.12)",
    },
}

LEVEL_ROLE = {"red": "error", "amber": "warning", "green": "success"}

# console CSS variable  ←  token role
CSS_ROLES = {
    "--page": "background", "--surface": "surface", "--ink": "foreground", "--ink-2": "ink2",
    "--muted": "muted", "--grid": "grid", "--border": "border", "--accent": "primary",
    "--good": "success", "--good-text": "success", "--warning": "warning",
    "--serious": "warning", "--critical": "error",
    # The console's Mantine shell maps its own surface scale onto these, so a
    # raised panel and the secondary/highlight hues come from here too.
    "--panel": "panel", "--secondary": "secondary", "--highlight": "accent",
}


def level_color(level: str | None, mode: str = "dark") -> str:
    """The colour of a health level; muted for unknown/absent."""
    tokens = TOKENS[mode]
    return tokens[LEVEL_ROLE[level]] if level in LEVEL_ROLE else tokens["muted"]


def _block(mode: str) -> str:
    t = TOKENS[mode]
    decls = " ".join(f"{var}: {t[role]};" for var, role in CSS_ROLES.items())
    return f"color-scheme: {mode}; {decls}"


def css() -> str:
    """The shared tokens as CSS — same selector structure as the console's own
    sheet, so a page that links this first keeps its dark-mode toggle working."""
    return (
        "/* generated by tools/fleetcore/theme.py — the bashOS palette; edit there */\n"
        f":root {{ {_block('light')} }}\n"
        f"@media (prefers-color-scheme: dark) {{ :root:not([data-theme=\"light\"]) {{ {_block('dark')} }} }}\n"
        f":root[data-theme=\"dark\"] {{ {_block('dark')} }}\n"
    )


def textual_themes() -> list[Any]:
    """Textual Theme objects named like bashOS's own (bashos-dark / bashos-light)."""
    from textual.theme import Theme

    keys = ("primary", "secondary", "accent", "foreground", "background", "surface", "panel",
            "success", "warning", "error")
    return [Theme(name=f"bashos-{mode}", dark=(mode == "dark"), **{k: TOKENS[mode][k] for k in keys})
            for mode in ("dark", "light")]
