#!/usr/bin/env python3
"""Fixture tests for the site-quality kit (templates/site-quality/).

    python3 templates/site-quality/test_site_quality_kit.py                 # test the kit
    python3 templates/site-quality/test_site_quality_kit.py --target <repo> # validate a repo's .github/site-quality.yml

Stdlib + PyYAML. JSON Schema validation uses `jsonschema` when it is installed
and falls back to a built-in check of the allowlist rules otherwise. Where the
hub carries specs/WORK.contract.yml, its `pinned_ref_re` decides what a valid
caller pin is, so the kit is tested against the same contract the conformance
checker reads. The runner's own behaviour is tested by node
(.github/site-quality/tests, `npm test`).
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

import yaml

KIT = Path(__file__).resolve().parent
HUB = KIT.parent.parent
TOKENS = {"__PROJECT_NAME__", "__DEFAULT_BRANCH__", "__KIT_VERSION__"}
FAILS: list[str] = []
WORKFLOW = "bamr87/bamr87/.github/workflows/site-quality.yml"
# Generated by local fixture builds; gitignored, never part of the kit.
EPHEMERA = {"Gemfile.lock", "_site", ".jekyll-cache", ".sass-cache", "__pycache__"}

_contract = HUB / "specs" / "WORK.contract.yml"
DEFS = (yaml.safe_load(_contract.read_text(encoding="utf-8")) or {}).get("definitions", {}) if _contract.is_file() else {}
PINNED_REF = re.compile(DEFS.get("pinned_ref_re", r"^(v\d+|v\d+\.\d+\.\d+|[0-9a-f]{40})$"))
DATE = re.compile(r"^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])$")


def check(cond: bool, msg: str) -> None:
    print(("  ok    " if cond else "  FAIL  ") + msg)
    if not cond:
        FAILS.append(msg)


def kit_files() -> list[Path]:
    return sorted(p for p in KIT.rglob("*") if p.is_file() and "archive" not in p.relative_to(KIT).parts
                  and not EPHEMERA & set(p.relative_to(KIT).parts))


def read(rel: str) -> str:
    return (KIT / rel).read_text(encoding="utf-8")


def schema() -> dict:
    return json.loads(read("site-quality.schema.json"))


# --- schema validation -------------------------------------------------------
def _fallback_errors(doc, sch) -> list[str]:
    """The rules the fixtures exercise, hand-coded, for hosts without `jsonschema`."""
    if not isinstance(doc, dict):
        return ["not a mapping"]
    errs = [f"unknown key {k}" for k in doc if k not in sch["properties"]]
    errs += [f"missing {k}" for k in sch["required"] if k not in doc]
    if doc.get("version") != 1:
        errs.append("version != 1")
    pages = doc.get("pages")
    if not isinstance(pages, list) or not pages or any(not str(p).startswith("/") for p in pages):
        errs.append("pages must be a non-empty list of /paths")
    allow = doc.get("allowlist") or {}
    if allow.get("on_expired", "warn") not in ("warn", "error"):
        errs.append("allowlist.on_expired not warn|error")
    for i, e in enumerate(allow.get("entries") or []):
        for k in ("rule", "reason", "issue", "until"):
            if k not in e:
                errs.append(f"entry {i}: missing {k}")
        if "selector" not in e and "page" not in e:
            errs.append(f"entry {i}: needs selector or page")
        if "until" in e and not (isinstance(e["until"], str) and DATE.match(e["until"])):
            errs.append(f"entry {i}: until must be a quoted YYYY-MM-DD")
        if "issue" in e and not str(e["issue"]).startswith("https://"):
            errs.append(f"entry {i}: issue must be a link")
    for sec in ("lighthouse",):
        for cat in ((doc.get(sec) or {}).get("categories") or {}).values():
            if cat.get("level") not in ("warn", "error"):
                errs.append("level not warn|error")
    return errs


def validate(doc) -> list[str]:
    sch = schema()
    try:
        import jsonschema  # type: ignore
    except ImportError:
        return _fallback_errors(doc, sch)
    v = jsonschema.Draft202012Validator(sch, format_checker=jsonschema.FormatChecker())
    return [f"{'/'.join(map(str, e.absolute_path)) or '(root)'}: {e.message}" for e in v.iter_errors(doc)]


def load(p: Path):
    # PyYAML (YAML 1.1) turns an unquoted 2026-12-31 into a date, which the
    # schema rejects: the same rule the runner enforces with yaml/ajv.
    return yaml.safe_load(p.read_text(encoding="utf-8"))


# --- tests -------------------------------------------------------------------
def t_version() -> None:
    print("VERSION `files:` matches the kit")
    meta = yaml.safe_load(read("VERSION"))
    listed = {f.strip() for f in str(meta["files"]).split(",")}
    top = {p.name for p in kit_files() if p.parent == KIT} - {"README.md", "VERSION", Path(__file__).name}
    listed_top = {f for f in listed if "/" not in f}
    check(listed_top == top, f"top-level files listed == on disk (missing {sorted(top - listed_top)}, stale {sorted(listed_top - top)})")
    check("fixtures/" in listed, "fixtures/ is listed")
    check(re.fullmatch(r"\d+\.\d+\.\d+", str(meta["version"])) is not None, "version is semver")


def t_placeholders() -> None:
    print("only fan-out tokens; no {{…}} scaffolds (fixture sites may use Liquid)")
    for p in kit_files():
        if p.suffix not in (".yml", ".yaml", ".md", ".json", ".html", ""):
            continue
        t = p.read_text(encoding="utf-8")
        found = set(re.findall(r"__[A-Z][A-Z_]*__", t))
        liquid_ok = "fixtures" in p.relative_to(KIT).parts or p.name == "README.md"
        check(found <= TOKENS and (liquid_ok or re.search(r"(?<!\$)\{\{", t) is None),
              f"{p.relative_to(KIT)} ({sorted(found - TOKENS) or 'clean'})")


def t_caller() -> None:
    print("caller workflow: pinned @v1, read-only, stamped (UPS-QA-60)")
    text = read("site-quality.yml")
    doc = yaml.safe_load(text)
    check("# kit: site-quality v__KIT_VERSION__" in text, "kit stamp")
    jobs = doc.get("jobs") or {}
    uses = [j.get("uses", "") for j in jobs.values()]
    check(len(uses) == 1 and uses[0].startswith(WORKFLOW + "@"), f"one job calling {WORKFLOW}")
    ref = uses[0].partition("@")[2] if uses else ""
    check(ref == "v1", f"pinned @v1 (got @{ref})")
    check(PINNED_REF.match(ref) is not None, "pin satisfies WORK.contract.yml pinned_ref_re (no custom tags)")
    check(not re.search(r"site-quality-v\d", text), "no custom site-quality-vN tag anywhere")
    check(doc.get("permissions") == {"contents": "read"}, "top-level permissions: contents: read")
    job = next(iter(jobs.values()), {})
    check((job.get("permissions") or {}) == {"contents": "read"}, "job permissions: contents: read")
    w = job.get("with") or {}
    check(w.get("mode") in ("build", "url"), "with.mode is build|url")
    check(w.get("config") == ".github/site-quality.yml", "with.config is .github/site-quality.yml")
    check("__DEFAULT_BRANCH__" in text, "push branch is the fan-out token")


def t_schema() -> None:
    print("schema vs fixtures (UPS-QA-61)")
    sch = schema()
    check(sch.get("$schema", "").endswith("2020-12/schema"), "schema is JSON Schema 2020-12")
    check(sch["properties"]["version"].get("const") == 1, "version: 1 is required")
    entry = sch["$defs"]["allowEntry"]
    check(set(entry["required"]) == {"rule", "reason", "issue", "until"}, "allowlist entry requires rule, reason, issue, until")
    check({tuple(a["required"]) for a in entry["anyOf"]} == {("selector",), ("page",)}, "allowlist entry needs selector and/or page")
    valid = sorted((KIT / "fixtures/configs/valid").glob("*.yml")) + [
        KIT / "site-quality.template.yml", KIT / "fixtures/pass-site/site-quality.yml", KIT / "fixtures/fail-site/site-quality.yml"]
    for p in valid:
        errs = validate(load(p))
        check(not errs, f"valid   {p.relative_to(KIT)} {errs or ''}")
    for p in sorted((KIT / "fixtures/configs/invalid").glob("*.yml")):
        errs = validate(load(p))
        check(bool(errs), f"invalid {p.relative_to(KIT)} ({len(errs)} error(s))")


def t_template_lenient() -> None:
    print("config template only reports (defaults never turn a caller red, #314)")
    text = read("site-quality.template.yml")
    doc = yaml.safe_load(text)
    active = "\n".join(line for line in text.splitlines() if not line.lstrip().startswith("#"))
    check("level: error" not in active, "no active `level: error`")
    check("fail_on" not in (doc.get("axe") or {}), "no axe.fail_on")
    check(all("max" not in p for p in (doc.get("contrast") or {}).get("pages") or []), "no contrast max")
    check(doc.get("load_errors", "warn") == "warn", "load_errors: warn")
    check((doc.get("allowlist") or {}).get("on_expired") == "warn", "allowlist.on_expired: warn (rollout)")
    check((doc.get("allowlist") or {}).get("entries") == [], "no allowlist entries seeded")
    check(not (doc.get("lighthouse") or {}).get("public_upload"), "no public Lighthouse upload")


def t_reusable() -> None:
    print("reusable workflow interface + pinned runtime")
    wf = HUB / ".github/workflows/site-quality.yml"
    if not wf.is_file():
        check(False, ".github/workflows/site-quality.yml exists")
        return
    doc = yaml.safe_load(wf.read_text(encoding="utf-8"))
    on = doc.get("on") or doc.get(True) or {}
    inputs = (on.get("workflow_call") or {}).get("inputs") or {}
    for name in ("mode", "config", "base-url", "theme-cache", "expired-allowlist-level", "gate", "artifact-name"):
        check(name in inputs, f"input {name}")
    check(inputs.get("mode", {}).get("default") == "build", "mode defaults to build")
    check(inputs.get("theme-cache", {}).get("default") is False, "no theme cache by default (fresh theme)")
    check(inputs.get("expired-allowlist-level", {}).get("default") == "", "expired level defaults to the config (warn)")
    outputs = (on.get("workflow_call") or {}).get("outputs") or {}
    check({"status", "theme-sha", "report-artifact"} <= set(outputs), "outputs status, theme-sha, report-artifact")
    pkg = json.loads((HUB / ".github/site-quality/package.json").read_text(encoding="utf-8"))
    loose = {k: v for k, v in pkg.get("dependencies", {}).items() if not re.fullmatch(r"\d+\.\d+\.\d+", v)}
    check(not loose, f"runtime dependencies pinned exactly {loose or ''}")
    for tool in ("@lhci/cli", "axe-core", "@axe-core/playwright", "pa11y", "playwright"):
        check(tool in pkg.get("dependencies", {}), f"{tool} pinned")
    check((HUB / ".github/site-quality/package-lock.json").is_file(), "package-lock.json committed")
    dep = (HUB / ".github/dependabot.yml").read_text(encoding="utf-8")
    check('directory: "/.github/site-quality"' in dep, "Dependabot npm entry for /.github/site-quality")


def target(repo: Path) -> int:
    f = repo / ".github" / "site-quality.yml"
    if not f.is_file():
        print(f"FAIL  {f} not found")
        return 1
    errs = validate(load(f))
    for e in errs:
        print(f"FAIL  {e}")
    print("OK" if not errs else f"FAILED ({len(errs)})")
    return 1 if errs else 0


def main(argv: list[str]) -> int:
    if len(argv) == 2 and argv[0] == "--target":
        return target(Path(argv[1]))
    for t in (t_version, t_placeholders, t_caller, t_schema, t_template_lenient, t_reusable):
        t()
    if FAILS:
        print(f"\nFAILED ({len(FAILS)})")
        return 1
    print("\nOK — site-quality kit")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
