"""cv_fragment — project the fleet registry into bamr87/cv's data contract.

The third leg of the cv ⇄ cv-builder-pro ⇄ hub triangle: bamr87/cv stores the
CV of record (data/cv.json, CVData schema), cv-builder-pro is the editor and
export engine, and THIS hub orchestrates — it knows the fleet's projects and
stacks, so it renders them into `_data/cv_portfolio.json`, a committed,
deterministic PROPOSAL in CVData `Project[]` / `Skill[]` shapes.

The fragment is adoption input, not a direct write: a human (or the sync-cv
skill / @claude) reviews it against bamr87/cv's data/cv.json and merges what
belongs on the CV. That keeps the CV curated and factual while the hub keeps
the portfolio signal fresh. Fields the registry cannot know (startDate) are
left blank for the adopter; adoption metadata (`featured`, `fleet_status`)
is stripped on merge.

Selection: featured projects always (unless archived); otherwise status
"active" only. Deterministic output — no timestamps, stable ordering — so the
file only changes when the registry meaningfully changes.
"""
from __future__ import annotations

import json
from pathlib import Path

FRAGMENT_NAME = "cv_portfolio.json"
CONSUMER = "https://github.com/bamr87/cv"

_COMMENT = (
    "GENERATED by dash-gen cv from _data/projects.yml - do not hand-edit. "
    "Proposal input for bamr87/cv data/cv.json (CVData Project/Skill shapes): "
    "review, fill startDate, drop the adoption-metadata keys (featured, "
    "fleet_status), then merge what belongs on the CV. "
    "Regenerate: tools/dash-gen cv"
)


def eligible(project: dict) -> bool:
    """CV-worthy: never archived; featured always, otherwise active only."""
    status = project.get("status") or ""
    if status == "archived":
        return False
    if project.get("featured"):
        return True
    return status == "active"


def _project_entry(project: dict) -> dict:
    slug = project.get("slug") or project.get("name") or ""
    entry: dict = {
        "id": f"fleet-{slug}",
        "name": project.get("name") or slug,
        "description": (project.get("description") or "").strip(),
        "technologies": [str(s) for s in (project.get("stack") or [])],
        "github": project.get("repo_url") or "",
        "startDate": "",
    }
    if project.get("live_url"):
        entry["url"] = project["live_url"]
    # Adoption metadata — helps the reviewer rank; stripped on merge.
    entry["featured"] = bool(project.get("featured"))
    entry["fleet_status"] = project.get("status") or ""
    return entry


def build_fragment(registry: list[dict]) -> dict:
    chosen = [p for p in registry if eligible(p)]
    chosen.sort(key=lambda p: (not p.get("featured"), (p.get("name") or "").lower()))

    stacks: set[str] = set()
    for project in registry:
        if (project.get("status") or "") != "archived":
            stacks.update(str(s) for s in (project.get("stack") or []))

    return {
        "$comment": _COMMENT,
        "consumer": CONSUMER,
        "source": "_data/projects.yml",
        "projects": [_project_entry(p) for p in chosen],
        "skills": [
            {
                "category": "Open-Source & Fleet Stacks",
                "skills": sorted(stacks, key=str.lower),
            }
        ],
    }


def render(registry: list[dict]) -> str:
    return json.dumps(build_fragment(registry), indent=2, ensure_ascii=False) + "\n"


def write_fragment(registry: list[dict], repo_root: Path, check: bool = False) -> int:
    """Write _data/cv_portfolio.json; with check=True, report staleness instead.

    Returns a process exit code (0 ok / 1 stale in check mode).
    """
    out_path = repo_root / "_data" / FRAGMENT_NAME
    new_text = render(registry)
    old_text = out_path.read_text() if out_path.exists() else None
    if new_text == old_text:
        print(f"{FRAGMENT_NAME} already up to date "
              f"({len(build_fragment(registry)['projects'])} projects).")
        return 0
    if check:
        print(f"{FRAGMENT_NAME} is STALE (run `tools/dash-gen cv`).")
        return 1
    out_path.write_text(new_text)
    print(f"wrote _data/{FRAGMENT_NAME} "
          f"({len(build_fragment(registry)['projects'])} projects).")
    return 0
