#!/usr/bin/env python3
"""
daily_report — prior-day fleet activity digest + failure work order.

The gather step of the dash's continuous analysis → implementation cycle
(.github/workflows/daily-repo-analysis.yml). Once a day it queries the GitHub
API (via PyGithub, same as actions_analytics) for every repo in the registry
and produces, for the window [now - <days>, now]:

  1. a COMMITTED Markdown digest — _reports/daily/<date>.md — summarizing the
     day's commits, pull requests, issues, releases, and CI failures across the
     fleet (a durable record saved in the monorepo), plus a regenerated index
     span in _reports/README.md; and

  2. an EPHEMERAL agent work order — daily-analysis-workorder.md — listing the
     CI failures worth acting on, DEDUPED against open `daily-analysis` issues
     in the dash repo, that the Opus Claude Code reviewer consumes to open one
     draft PR (hub-fixable) or file one issue (submodule/cross-repo) per failure.

Deterministic where it matters: the digest and the candidate selection + dedupe
are computed HERE (in code). The non-deterministic AI step only investigates and
authors fixes for a pre-vetted, de-duplicated, capped list — it cannot spam.

Exit status is 0 even on a quiet day (no activity, no failures — that is normal
and still writes a "quiet day" digest). When GITHUB_OUTPUT is set it emits
`has_failures=true|false`, `failure_count=N`, `report_path=...`, and `date=...`
for the workflow to branch on.

Auth: a token from GH_TOKEN / GITHUB_TOKEN, else `gh auth token`. Network /
rate-limit failures degrade gracefully — a repo that can't be read is skipped,
not fatal, so a single flaky repo never sinks the whole digest.
"""
from __future__ import annotations

import argparse
import datetime as dt
import os
import re
import subprocess
import sys
from pathlib import Path

import actions_analytics  # owner_repo, resolve_token, as_utc, WASTE_CONCLUSIONS

try:
    import yaml
except ImportError:  # pragma: no cover
    sys.stderr.write("daily_report requires PyYAML: pip install pyyaml\n")
    sys.exit(2)

REPO_ROOT = Path(__file__).resolve().parents[3]
REGISTRY = REPO_ROOT / "_data" / "projects.yml"
REPORT_DIR_DEFAULT = REPO_ROOT / "_reports" / "daily"
INDEX_DEFAULT = REPO_ROOT / "_reports" / "README.md"
WORKORDER_DEFAULT = REPO_ROOT / "daily-analysis-workorder.md"

# CI conclusions that count as a failure worth reviewing.
FAILURE_CONCLUSIONS = actions_analytics.WASTE_CONCLUSIONS - {"cancelled"}

# Markers for the AUTO index span in _reports/README.md.
INDEX_START = "<!-- AUTO:daily-index START - regenerated by dash-gen daily; do not edit by hand -->"
INDEX_END = "<!-- AUTO:daily-index END -->"

# How many recent reports to list in the index span.
INDEX_KEEP = 30


# --------------------------------------------------------------------------- #
# helpers
# --------------------------------------------------------------------------- #
def now_utc() -> dt.datetime:
    return dt.datetime.now(dt.timezone.utc)


def in_window(value: dt.datetime | None, start: dt.datetime) -> bool:
    v = actions_analytics.as_utc(value)
    return v is not None and v >= start


def short(text: str | None, n: int = 72) -> str:
    text = (text or "").splitlines()[0].strip() if text else ""
    return text if len(text) <= n else text[: n - 1] + "…"


def marker_key(repo_name: str, path: str, workflow: str) -> str:
    """Stable identity for a failing workflow (repo + file path)."""
    tail = path or workflow or "?"
    return f"{repo_name}:{tail}"


def issue_marker(key: str) -> str:
    return f'<!-- daily-analysis key="{key}" -->'


# --------------------------------------------------------------------------- #
# per-repo collection
# --------------------------------------------------------------------------- #
def collect_repo(gh, project: dict, start: dt.datetime, max_runs: int) -> dict | None:
    """Gather one repo's activity in the window. None on unreachable repo."""
    from github.GithubException import GithubException

    nwo = actions_analytics.owner_repo(project.get("repo_url", "") or "")
    if not nwo:
        return None
    branch = project.get("branch") or "main"
    external = not nwo.startswith("bamr87/")

    try:
        repo = gh.get_repo(nwo)
    except GithubException:
        return None

    act: dict = {
        "name": project.get("name", nwo),
        "nwo": nwo,
        "repo_url": project.get("repo_url"),
        "branch": branch,
        "external": external,
        "commits": [],
        "commits_capped": False,
        "prs_opened": [],
        "prs_merged": [],
        "prs_closed": [],
        "issues_opened": [],
        "issues_closed": [],
        "releases": [],
        "failures": [],
    }

    # --- commits on the default branch -------------------------------------
    try:
        seen = 0
        for c in repo.get_commits(sha=branch, since=start):
            seen += 1
            if seen > 100:
                act["commits_capped"] = True
                break
            act["commits"].append({
                "sha": c.sha[:7],
                "message": short((c.commit.message if c.commit else "") or ""),
                "url": c.html_url,
            })
    except GithubException:
        pass

    # --- pull requests (scan updated-desc until out of window) -------------
    try:
        scanned = 0
        for pr in repo.get_pulls(state="all", sort="updated", direction="desc"):
            if not in_window(pr.updated_at, start):
                break
            scanned += 1
            if scanned > 120:
                break
            rec = {"number": pr.number, "title": short(pr.title), "url": pr.html_url,
                   "user": pr.user.login if pr.user else "?"}
            if in_window(pr.merged_at, start):
                act["prs_merged"].append(rec)
            elif in_window(pr.created_at, start):
                act["prs_opened"].append(rec)
            elif pr.state == "closed" and in_window(pr.closed_at, start):
                act["prs_closed"].append(rec)
    except GithubException:
        pass

    # --- issues (get_issues includes PRs — filter them out) ----------------
    try:
        scanned = 0
        for iss in repo.get_issues(state="all", since=start, sort="updated", direction="desc"):
            # Raw-payload check: reading iss.pull_request on a list-fetched
            # Issue triggers a hidden per-issue GET (PyGithub lazy completion).
            if "pull_request" in iss._rawData:  # noqa: SLF001 — perf, not laziness
                continue
            scanned += 1
            if scanned > 120:
                break
            rec = {"number": iss.number, "title": short(iss.title), "url": iss.html_url}
            if iss.state == "closed" and in_window(iss.closed_at, start):
                act["issues_closed"].append(rec)
            elif in_window(iss.created_at, start):
                act["issues_opened"].append(rec)
    except GithubException:
        pass

    # --- releases ----------------------------------------------------------
    # Never slice a PaginatedList: PyGithub's slice iterator raises IndexError
    # (not GithubException) when the repo has fewer releases than the slice —
    # that killed the whole 2026-07-21 run. Iterate + break instead.
    try:
        for idx, rel in enumerate(repo.get_releases()):
            if idx >= 10:
                break
            if in_window(rel.published_at, start):
                act["releases"].append({"tag": rel.tag_name, "name": short(rel.title or ""),
                                        "url": rel.html_url})
    except GithubException:
        pass

    # --- CI failures (completed runs with a failure conclusion) ------------
    # bamr87-owned repos only: an external mirror's failures aren't ours to fix.
    if not external:
        try:
            seen = 0
            for run in repo.get_workflow_runs():
                created = actions_analytics.as_utc(run.created_at)
                if created and created < start:
                    break                       # newest-first: past the window
                seen += 1
                if seen > max_runs:
                    break
                if run.status != "completed":
                    continue
                if (run.conclusion or "") not in FAILURE_CONCLUSIONS:
                    continue
                act["failures"].append({
                    "workflow": run.name or "(workflow)",
                    "path": getattr(run, "path", "") or "",
                    "conclusion": run.conclusion,
                    "event": run.event or "?",
                    "branch": run.head_branch or "?",
                    "run_id": run.id,
                    "url": run.html_url,
                    "created": created.strftime("%Y-%m-%d %H:%M UTC") if created else "?",
                })
        except GithubException:
            pass

    return act


# --------------------------------------------------------------------------- #
# report assembly
# --------------------------------------------------------------------------- #
def build_report(registry: list[dict], gh, days: int, max_runs: int) -> dict:
    now = now_utc()
    start = now - dt.timedelta(days=days)
    repos: list[dict] = []
    scanned = 0
    for project in registry:
        nwo = actions_analytics.owner_repo(project.get("repo_url", "") or "")
        if not nwo:
            continue
        sys.stderr.write(f"  · {nwo}\n")
        try:
            act = collect_repo(gh, project, start, max_runs)
        except Exception as exc:  # one unreadable repo must never sink the digest
            sys.stderr.write(f"    ! {nwo} skipped: {type(exc).__name__}: {exc}\n")
            act = None
        scanned += 1
        if act is not None:
            repos.append(act)

    def total(key: str) -> int:
        return sum(len(r[key]) for r in repos)

    totals = {
        "commits": sum(len(r["commits"]) for r in repos),
        "prs_opened": total("prs_opened"),
        "prs_merged": total("prs_merged"),
        "prs_closed": total("prs_closed"),
        "issues_opened": total("issues_opened"),
        "issues_closed": total("issues_closed"),
        "releases": total("releases"),
        "failures": total("failures"),
        "repos_active": sum(1 for r in repos if _has_activity(r)),
    }
    return {
        "generated_at": now.strftime("%Y-%m-%d %H:%M UTC"),
        "window_start": start.strftime("%Y-%m-%d %H:%M UTC"),
        "window_end": now.strftime("%Y-%m-%d %H:%M UTC"),
        "window_days": days,
        "repos_scanned": scanned,
        "totals": totals,
        "repos": repos,
    }


def _has_activity(r: dict) -> bool:
    return any(r[k] for k in ("commits", "prs_opened", "prs_merged", "prs_closed",
                              "issues_opened", "issues_closed", "releases", "failures"))


# --------------------------------------------------------------------------- #
# markdown rendering
# --------------------------------------------------------------------------- #
def render_report_md(rep: dict, date_label: str) -> str:
    t = rep["totals"]
    L: list[str] = []
    L.append(f"# Daily Repo Activity — {date_label}")
    L.append("")
    L.append(f"_Window: {rep['window_start']} → {rep['window_end']} "
             f"(last {rep['window_days']}d) · generated {rep['generated_at']} · "
             f"{rep['repos_scanned']} repos scanned_")
    L.append("")
    L.append("## Fleet summary")
    L.append("")
    L.append(f"- 📦 **{t['commits']}** commits across **{t['repos_active']}** active repo(s)")
    L.append(f"- 🔀 **{t['prs_opened']}** PRs opened · **{t['prs_merged']}** merged · "
             f"**{t['prs_closed']}** closed")
    L.append(f"- 🐛 **{t['issues_opened']}** issues opened · **{t['issues_closed']}** closed")
    L.append(f"- 🚀 **{t['releases']}** release(s)")
    L.append(f"- {'❌' if t['failures'] else '✅'} **{t['failures']}** CI failure(s)")
    L.append("")
    if t["failures"]:
        L.append("> [!WARNING]")
        L.append(f"> {t['failures']} CI failure(s) detected in the last {rep['window_days']}d. "
                 f"The analysis agent reviews these and opens fixes (draft PRs) or files "
                 f"tracking issues. See **CI failures** below.")
        L.append("")

    # --- CI failures first (the actionable signal) -------------------------
    fail_repos = [r for r in rep["repos"] if r["failures"]]
    if fail_repos:
        L.append("## ❌ CI failures")
        L.append("")
        for r in fail_repos:
            L.append(f"### {r['name']} ({r['nwo']})")
            for f in r["failures"]:
                L.append(f"- **{f['workflow']}** → `{f['conclusion']}` · "
                         f"{f['event']} on `{f['branch']}` · {f['created']} · "
                         f"[run {f['run_id']}]({f['url']})")
            L.append("")

    # --- activity by repo --------------------------------------------------
    active = [r for r in rep["repos"] if _has_activity(r)]
    quiet = len(rep["repos"]) - len(active)
    if active:
        L.append("## Activity by repo")
        L.append("")
        for r in sorted(active, key=lambda x: x["name"].lower()):
            tag = " _(external)_" if r["external"] else ""
            L.append(f"### {r['name']}{tag}")
            if r["commits"]:
                cap = "+" if r["commits_capped"] else ""
                L.append(f"- 📦 {len(r['commits'])}{cap} commit(s):")
                for c in r["commits"][:5]:
                    L.append(f"    - [`{c['sha']}`]({c['url']}) {c['message']}")
                if len(r["commits"]) > 5:
                    L.append(f"    - …and {len(r['commits']) - 5} more")
            for label, key in (("🔀 opened", "prs_opened"), ("✅ merged", "prs_merged"),
                               ("🔒 closed", "prs_closed")):
                if r[key]:
                    items = ", ".join(f"[#{p['number']}]({p['url']})" for p in r[key][:8])
                    L.append(f"- PRs {label}: {items}")
            for label, key in (("🆕 opened", "issues_opened"), ("☑️ closed", "issues_closed")):
                if r[key]:
                    items = ", ".join(f"[#{i['number']}]({i['url']})" for i in r[key][:8])
                    L.append(f"- Issues {label}: {items}")
            if r["releases"]:
                items = ", ".join(f"[{x['tag']}]({x['url']})" for x in r["releases"])
                L.append(f"- 🚀 Releases: {items}")
            L.append("")
    if quiet:
        L.append(f"_{quiet} repo(s) had no activity in this window._")
        L.append("")

    L.append("---")
    L.append("")
    L.append("_Generated by `dash-gen daily` "
             "(.github/scripts/dash-gen/daily_report.py) — the daily-repo-analysis "
             "workflow's gather step. Edit the generator, not this file._")
    L.append("")
    return "\n".join(L)


# --------------------------------------------------------------------------- #
# dedupe against open daily-analysis issues
# --------------------------------------------------------------------------- #
def open_markers(repo_slug: str, label: str) -> set[str]:
    import json

    def _list(cmd: list[str]) -> list[dict] | None:
        try:
            out = subprocess.run(cmd, capture_output=True, text=True, timeout=60)
        except (FileNotFoundError, subprocess.TimeoutExpired):
            return None
        if out.returncode != 0:
            return None
        try:
            return json.loads(out.stdout)
        except json.JSONDecodeError:
            return None

    base = ["gh", "issue", "list", "-R", repo_slug, "--state", "open",
            "--json", "number,title,body", "--limit", "200"]
    items = _list(base + ["--label", label])
    if items is None:
        items = _list(base + ["--search", "daily-analysis in:body"])
    markers: set[str] = set()
    for it in items or []:
        for m in re.findall(r'<!-- daily-analysis key="([^"]+)" -->', it.get("body", "") or ""):
            markers.add(m)
    return markers


def collect_failures(rep: dict) -> list[dict]:
    """Flatten per-repo failures into one candidate per failing workflow."""
    by_key: dict[str, dict] = {}
    for r in rep["repos"]:
        for f in r["failures"]:
            key = marker_key(r["name"], f["path"], f["workflow"])
            cand = by_key.setdefault(key, {
                "key": key, "repo": r["name"], "nwo": r["nwo"],
                "repo_url": r["repo_url"], "workflow": f["workflow"],
                "path": f["path"], "runs": [],
            })
            cand["runs"].append(f)
    return list(by_key.values())


def render_workorder(cands: list[dict], rep: dict, cap: int, hub: str) -> str:
    t = rep["totals"]
    L: list[str] = []
    L.append("# Daily repo analysis — reviewer work order")
    L.append("")
    L.append(f"Window: last {rep['window_days']}d · generated {rep['generated_at']} · "
             f"{rep['repos_scanned']} repos scanned")
    L.append(f"Fleet day: {t['commits']} commits · {t['prs_merged']} PRs merged · "
             f"{t['issues_opened']} issues opened · **{t['failures']} CI failure(s)**")
    L.append("")
    if not cands:
        L.append("**No actionable failures** — no CI failures in the window, or every "
                 "failing workflow already has an open `daily-analysis` issue. No action "
                 "needed.")
        L.append("")
        return "\n".join(L)

    L.append(f"**{len(cands)} failing workflow(s)** to review (cap: {cap} this run). For each:")
    L.append("")
    L.append(f"- If the fix is in **{hub}** itself (a hub workflow, script, doc, or config), "
             "open ONE **draft PR** with the surgical fix.")
    L.append(f"- If the failure is inside a **submodule / another repo** (you cannot safely "
             f"fix it from the hub checkout), file ONE **issue** in `{hub}` instead.")
    L.append("- Paste the candidate's **MARKER** line verbatim as the FIRST line of the PR / "
             "issue body so future runs dedupe.")
    L.append("")
    for i, c in enumerate(cands, 1):
        L.append("---")
        L.append("")
        L.append(f"## {i}. {c['repo']}/{c['workflow']}")
        L.append("")
        L.append(f"- **Repo:** {c['repo']} — {c['repo_url']}  "
                 f"({'hub — fix here' if c['nwo'] == hub else 'submodule / external — file an issue'})")
        L.append(f"- **Workflow file:** `{c['path'] or '(unknown path)'}`")
        L.append("- **MARKER** (first body line, verbatim, no bullet/backticks):")
        L.append("")
        L.append(issue_marker(c["key"]))
        L.append("")
        L.append(f"- **Failing runs ({len(c['runs'])}):**")
        for run in c["runs"][:5]:
            L.append(f"    - `{run['conclusion']}` · {run['event']} on `{run['branch']}` · "
                     f"{run['created']} · run `{run['run_id']}` · {run['url']}")
        L.append(f"- **Investigate:** `gh run view -R {c['nwo']} {c['runs'][0]['run_id']} "
                 f"--log-failed` (fall back to `gh run view -R {c['nwo']} "
                 f"{c['runs'][0]['run_id']}` if logs 404).")
        L.append("")
    return "\n".join(L)


# --------------------------------------------------------------------------- #
# index span regeneration
# --------------------------------------------------------------------------- #
def render_index_span(report_dir: Path) -> str:
    files = sorted(
        (p for p in report_dir.glob("*.md") if re.match(r"\d{4}-\d{2}-\d{2}\.md$", p.name)),
        reverse=True,
    )[:INDEX_KEEP]
    if not files:
        return "_No daily reports yet._"
    lines = ["| Date | Report |", "| --- | --- |"]
    for p in files:
        lines.append(f"| {p.stem} | [daily/{p.name}](daily/{p.name}) |")
    return "\n".join(lines)


def update_index(index_path: Path, report_dir: Path) -> None:
    span = render_index_span(report_dir)
    if index_path.exists():
        text = index_path.read_text()
        if INDEX_START in text and INDEX_END in text:
            pre, rest = text.split(INDEX_START, 1)
            _old, post = rest.split(INDEX_END, 1)
            index_path.write_text(f"{pre}{INDEX_START}\n{span}\n{INDEX_END}{post}")
            return
    # No index (or markers missing): write a fresh one.
    index_path.write_text(DEFAULT_INDEX_TEMPLATE.format(
        start=INDEX_START, span=span, end=INDEX_END))


DEFAULT_INDEX_TEMPLATE = """\
# Reports

Generated, committed records produced by the dash's automation. This directory is
`generated` in the SCHEMA pyramid — the files here are written by tooling, not by
hand.

## Daily repo activity

`daily/<date>.md` — one per day, written by the **daily-repo-analysis** workflow
(`.github/scripts/dash-gen/daily_report.py`). Each is a digest of the prior day's
commits, pull requests, issues, releases, and **CI failures** across every repo in
the registry. The same run also hands the failures to an Opus Claude Code agent,
which opens draft PRs (hub-fixable) or files `daily-analysis` issues
(submodule / cross-repo).

See [`docs/DAILY-ANALYSIS.md`](../docs/DAILY-ANALYSIS.md) for the full pipeline.

### Recent reports

{start}
{span}
{end}
"""


# --------------------------------------------------------------------------- #
# entry point
# --------------------------------------------------------------------------- #
def emit_output(key: str, value) -> None:
    path = os.environ.get("GITHUB_OUTPUT")
    if path:
        with open(path, "a") as fh:
            fh.write(f"{key}={value}\n")


def run(args: argparse.Namespace) -> int:
    try:
        from github import Github, Auth
    except ImportError:
        sys.stderr.write("daily_report requires PyGithub: pip install PyGithub\n")
        return 2

    token = actions_analytics.resolve_token()
    if not token:
        sys.stderr.write("No GitHub token (set GH_TOKEN/GITHUB_TOKEN or run `gh auth login`).\n")
        return 2

    with REGISTRY.open() as fh:
        registry = yaml.safe_load(fh) or []

    # The hub isn't a registry project, but its own activity + CI failures are
    # exactly what the implement agent can fix directly — always scan it.
    if not any(actions_analytics.owner_repo(p.get("repo_url", "") or "") == args.repo
               for p in registry):
        registry = [{"name": "bamr87 (hub)",
                     "repo_url": f"https://github.com/{args.repo}",
                     "branch": "main"}] + list(registry)

    date_label = args.date or now_utc().strftime("%Y-%m-%d")
    gh = Github(auth=Auth.Token(token), per_page=100)
    sys.stderr.write(f"Scanning daily activity for {len(registry)} repos (last {args.days}d)…\n")
    rep = build_report(registry, gh, args.days, args.max_runs)

    # 1) committed digest
    report_dir = Path(args.report_dir)
    report_dir.mkdir(parents=True, exist_ok=True)
    report_path = report_dir / f"{date_label}.md"
    report_path.write_text(render_report_md(rep, date_label))
    sys.stderr.write(f"Wrote {report_path}\n")

    # 2) regenerated index span
    update_index(Path(args.index), report_dir)

    # 3) deduped failure work order
    cands = collect_failures(rep)
    if not args.no_dedupe:
        seen = open_markers(args.repo, args.label)
        fresh = [c for c in cands if c["key"] not in seen]
        skipped = len(cands) - len(fresh)
    else:
        fresh, skipped = cands, 0
    fresh = fresh[: args.limit]
    Path(args.workorder).write_text(render_workorder(fresh, rep, args.limit, args.repo))

    emit_output("has_failures", "true" if fresh else "false")
    emit_output("failure_count", len(fresh))
    emit_output("report_path", str(report_path.relative_to(REPO_ROOT))
                if report_path.is_relative_to(REPO_ROOT) else str(report_path))
    emit_output("date", date_label)

    t = rep["totals"]
    sys.stderr.write(
        f"daily: {t['commits']} commits · {t['prs_merged']} merged · "
        f"{t['issues_opened']} issues · {t['failures']} failures "
        f"({len(cands)} candidate workflow(s), {skipped} already-open, "
        f"{len(fresh)} in work order → {args.workorder})\n"
    )
    for c in fresh:
        sys.stderr.write(f"  · {c['repo']}/{c['workflow']} ({len(c['runs'])} run(s))\n")
    return 0


def add_arguments(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("--days", type=int, default=1, metavar="N",
                        help="window in days to analyze (default 1 — the prior day)")
    parser.add_argument("--max-runs", type=int, default=150, metavar="N",
                        help="cap workflow runs scanned per repo (default 150)")
    parser.add_argument("--report-dir", default=str(REPORT_DIR_DEFAULT), metavar="DIR",
                        help="directory for the committed digest (default _reports/daily)")
    parser.add_argument("--index", default=str(INDEX_DEFAULT), metavar="PATH",
                        help="index file whose AUTO span is regenerated (default _reports/README.md)")
    parser.add_argument("--workorder", default=str(WORKORDER_DEFAULT), metavar="PATH",
                        help="ephemeral failure work order (default daily-analysis-workorder.md)")
    parser.add_argument("--date", default=None, metavar="YYYY-MM-DD",
                        help="report date label (default today, UTC)")
    parser.add_argument("--limit", type=int, default=6, metavar="N",
                        help="max failing workflows in the work order (default 6)")
    parser.add_argument("--repo", default="bamr87/bamr87", metavar="OWNER/REPO",
                        help="hub repo for dedupe + PRs/issues (default bamr87/bamr87)")
    parser.add_argument("--label", default="daily-analysis", metavar="LABEL",
                        help="label marking analysis issues (default daily-analysis)")
    parser.add_argument("--no-dedupe", action="store_true",
                        help="skip dedupe against open issues (offline / testing)")
    parser.set_defaults(func=run)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="daily-report", description=__doc__)
    add_arguments(parser)
    args = parser.parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    raise SystemExit(main())
