#!/usr/bin/env python3
"""
dash-gen — registry-driven generator for the bamr87 development dash.

Subcommands:
  health   Gather live GitHub signals (stars, CI, issues, PRs, activity, security)
           for every project in the registry, compute an attention level
           (red/amber/green + reasons), and write dash/_data/project_health.yml.
           This data is EPHEMERAL — generated at deploy time, never committed.

  readme   Regenerate ONLY the <!-- AUTO:projects --> span of the profile README.md
           from the registry's static facts (deterministic; safe to commit).

  ai       Shadow-price local Claude Code usage per repo (scans ~/.claude/projects
           JSONL ledgers, persists a daily ledger, writes _data/ai_activity.yml).
           LOCAL-ONLY and ephemeral — not part of `all`, never runs in CI.
           Implemented in ai_activity.py.

  all      Run health then readme.

The single source of truth is dash/_data/projects.yml. This script never invents
project facts — it only enriches (health) or reformats (readme) what the registry
already declares.

GitHub calls go through the `gh` CLI (`gh api ...`) so auth is inherited from
`gh auth login` locally or GITHUB_TOKEN/GH_TOKEN in CI. Network failures degrade
gracefully: a project that can't be reached yields nulls, not a crash.
"""
from __future__ import annotations

import argparse
import datetime as dt
import json
import subprocess
import sys
from pathlib import Path

import ai_activity

try:
    import yaml
except ImportError:  # pragma: no cover
    sys.stderr.write("dash-gen requires PyYAML: pip install pyyaml\n")
    sys.exit(2)

REPO_ROOT = Path(__file__).resolve().parents[3]
REGISTRY = REPO_ROOT / "_data" / "projects.yml"
THRESHOLDS = REPO_ROOT / "_data" / "health_thresholds.yml"
HEALTH_OUT = REPO_ROOT / "_data" / "project_health.yml"
HEALTH_META = REPO_ROOT / "_data" / "project_health_meta.yml"
README = REPO_ROOT / "README.md"

AUTO_START = "<!-- AUTO:projects START - generated by .github/scripts/dash-gen; edit _data/projects.yml -->"
AUTO_END = "<!-- AUTO:projects END -->"

DEFAULT_THRESHOLDS = {
    "stale_commit_days": 60,
    "stale_issue_days": 30,
    "stale_pr_days": 14,
    "bug_issue_amber": 3,
    "ci_pass_rate_amber": 80,
    "ci_window": 20,
}

CATEGORY_LABELS = [
    ("docs", "### 📚 Documentation & Knowledge Platforms"),
    ("full-stack-ai", "### 🚀 Full-Stack & AI Applications"),
    ("dev-tools", "### 🛠️ Developer Tools & Experiments"),
    ("dash", "### 🛰️ Dash"),
]


# --------------------------------------------------------------------------- #
# helpers
# --------------------------------------------------------------------------- #
def load_registry() -> list[dict]:
    with REGISTRY.open() as fh:
        return yaml.safe_load(fh) or []


def load_thresholds() -> dict:
    if THRESHOLDS.exists():
        with THRESHOLDS.open() as fh:
            data = yaml.safe_load(fh) or {}
        return {**DEFAULT_THRESHOLDS, **data}
    return dict(DEFAULT_THRESHOLDS)


def now_utc() -> dt.datetime:
    return dt.datetime.now(dt.timezone.utc)


def parse_ts(value: str | None) -> dt.datetime | None:
    if not value:
        return None
    try:
        return dt.datetime.fromisoformat(value.replace("Z", "+00:00"))
    except ValueError:
        return None


def days_since(value: str | None) -> int | None:
    ts = parse_ts(value)
    if ts is None:
        return None
    return (now_utc() - ts).days


def owner_repo(repo_url: str) -> str | None:
    """https://github.com/owner/repo[.git] -> owner/repo"""
    if "github.com/" not in repo_url:
        return None
    tail = repo_url.split("github.com/", 1)[1]
    tail = tail.removesuffix(".git").strip("/")
    parts = tail.split("/")
    if len(parts) < 2:
        return None
    return f"{parts[0]}/{parts[1]}"


def gh_api(path: str, *, paginate: bool = False) -> object | None:
    """Call `gh api <path>`; return parsed JSON or None on any failure."""
    cmd = ["gh", "api", path, "-H", "Accept: application/vnd.github+json"]
    if paginate:
        cmd.append("--paginate")
    try:
        out = subprocess.run(cmd, capture_output=True, text=True, timeout=60)
    except (FileNotFoundError, subprocess.TimeoutExpired):
        return None
    if out.returncode != 0:
        return None
    try:
        if paginate:
            # --paginate concatenates JSON arrays; merge them.
            merged: list = []
            decoder = json.JSONDecoder()
            text = out.stdout.strip()
            idx = 0
            while idx < len(text):
                obj, end = decoder.raw_decode(text, idx)
                if isinstance(obj, list):
                    merged.extend(obj)
                else:
                    merged.append(obj)
                idx = end
                while idx < len(text) and text[idx] in " \n\r\t":
                    idx += 1
            return merged
        return json.loads(out.stdout)
    except json.JSONDecodeError:
        return None


# --------------------------------------------------------------------------- #
# health gathering
# --------------------------------------------------------------------------- #
def gather_health(project: dict, th: dict) -> dict:
    name = project["name"]
    repo_url = project["repo_url"]
    branch = project.get("branch") or "main"
    nwo = owner_repo(repo_url)

    health = {
        "name": name,
        "repo_url": repo_url,
        "stars": 0,
        "ci": {"last": None, "pass_rate": 0, "failing": []},
        "issues": {"open": 0, "bugs": 0, "good_first": 0, "stale": 0, "items": []},
        "prs": {"open": 0, "draft": 0, "stale": 0},
        "activity": {"last_commit_days": None, "commits_7d": 0, "commits_30d": 0},
        "security": {"alerts": 0},
        "release": {"tag": None, "age_days": None},
        "attention": {"level": "green", "reasons": []},
        "attention_rank": 2,
    }
    if not nwo:
        return health

    repo = gh_api(f"repos/{nwo}")
    if isinstance(repo, dict):
        health["stars"] = repo.get("stargazers_count", 0)
        health["activity"]["last_commit_days"] = days_since(repo.get("pushed_at"))

    # issues (exclude PRs, which the issues endpoint includes)
    issues = gh_api(f"repos/{nwo}/issues?state=open&per_page=100", paginate=True)
    if isinstance(issues, list):
        real = [i for i in issues if "pull_request" not in i]
        health["issues"]["open"] = len(real)
        for i in real:
            labels = [l.get("name", "").lower() for l in i.get("labels", [])]
            age = days_since(i.get("updated_at"))
            if any("bug" in l for l in labels):
                health["issues"]["bugs"] += 1
            if any("good first issue" in l for l in labels):
                health["issues"]["good_first"] += 1
            if age is not None and age > th["stale_issue_days"]:
                health["issues"]["stale"] += 1
            if len(health["issues"]["items"]) < 10:
                health["issues"]["items"].append(
                    {
                        "number": i.get("number"),
                        "title": i.get("title", "")[:120],
                        "url": i.get("html_url"),
                        "labels": [l.get("name") for l in i.get("labels", [])][:5],
                        "age_days": age,
                    }
                )

    # PRs
    prs = gh_api(f"repos/{nwo}/pulls?state=open&per_page=100", paginate=True)
    if isinstance(prs, list):
        health["prs"]["open"] = len(prs)
        for p in prs:
            if p.get("draft"):
                health["prs"]["draft"] += 1
            age = days_since(p.get("updated_at"))
            if age is not None and age > th["stale_pr_days"]:
                health["prs"]["stale"] += 1

    # CI build stats
    runs = gh_api(
        f"repos/{nwo}/actions/runs?branch={branch}&per_page={th['ci_window']}"
    )
    if isinstance(runs, dict):
        wr = runs.get("workflow_runs", [])
        completed = [r for r in wr if r.get("status") == "completed"]
        if completed:
            health["ci"]["last"] = completed[0].get("conclusion")
            ok = sum(1 for r in completed if r.get("conclusion") == "success")
            health["ci"]["pass_rate"] = round(100 * ok / len(completed))
            health["ci"]["failing"] = sorted(
                {
                    r.get("name")
                    for r in completed
                    if r.get("conclusion") not in ("success", None)
                }
            )

    # activity (commit counts)
    since30 = (now_utc() - dt.timedelta(days=30)).strftime("%Y-%m-%dT%H:%M:%SZ")
    since7 = (now_utc() - dt.timedelta(days=7)).strftime("%Y-%m-%dT%H:%M:%SZ")
    c30 = gh_api(f"repos/{nwo}/commits?sha={branch}&since={since30}&per_page=100", paginate=True)
    if isinstance(c30, list):
        health["activity"]["commits_30d"] = len(c30)
        health["activity"]["commits_7d"] = sum(
            1
            for c in c30
            if (parse_ts((c.get("commit", {}).get("author") or {}).get("date")) or now_utc())
            >= parse_ts(since7)
        )

    # latest release
    rel = gh_api(f"repos/{nwo}/releases/latest")
    if isinstance(rel, dict) and rel.get("tag_name"):
        health["release"]["tag"] = rel.get("tag_name")
        health["release"]["age_days"] = days_since(rel.get("published_at"))

    # security (dependabot alerts; may be 403 without access -> stays 0)
    alerts = gh_api(f"repos/{nwo}/dependabot/alerts?state=open&per_page=100", paginate=True)
    if isinstance(alerts, list):
        health["security"]["alerts"] = len(alerts)

    compute_attention(project, health, th)
    return health


def compute_attention(project: dict, health: dict, th: dict) -> None:
    reasons: list[str] = []
    level = "green"

    if health["ci"]["last"] not in ("success", None):
        reasons.append(f"CI failing ({health['ci']['last']})")
        level = "red"

    lcd = health["activity"]["last_commit_days"]
    if project.get("status") == "active" and lcd is not None and lcd > th["stale_commit_days"]:
        reasons.append(f"no commits in {lcd}d")
        level = "red"

    if health["security"]["alerts"] > 0:
        reasons.append(f"{health['security']['alerts']} security alert(s)")
        level = "red" if level == "red" else "amber"

    if health["issues"]["bugs"] >= th["bug_issue_amber"]:
        reasons.append(f"{health['issues']['bugs']} open bugs")
        if level == "green":
            level = "amber"

    if health["issues"]["stale"] > 0:
        reasons.append(f"{health['issues']['stale']} stale issue(s)")
        if level == "green":
            level = "amber"

    if (
        health["ci"]["last"] == "success"
        and health["ci"]["pass_rate"] < th["ci_pass_rate_amber"]
    ):
        reasons.append(f"CI flaky ({health['ci']['pass_rate']}% pass)")
        if level == "green":
            level = "amber"

    if not reasons:
        reasons.append("healthy")

    health["attention"]["level"] = level
    health["attention"]["reasons"] = reasons
    health["attention_rank"] = {"red": 0, "amber": 1, "green": 2}[level]


def cmd_health(args: argparse.Namespace) -> int:
    registry = load_registry()
    th = load_thresholds()
    results = []
    for project in registry:
        sys.stderr.write(f"  · {project['name']}\n")
        results.append(gather_health(project, th))

    HEALTH_OUT.parent.mkdir(parents=True, exist_ok=True)
    with HEALTH_OUT.open("w") as fh:
        fh.write("# GENERATED by .github/scripts/dash-gen — do not edit or commit.\n")
        yaml.safe_dump(results, fh, sort_keys=False, allow_unicode=True)
    with HEALTH_META.open("w") as fh:
        yaml.safe_dump(
            {"generated_at": now_utc().strftime("%Y-%m-%d %H:%M UTC")},
            fh,
        )
    red = sum(1 for r in results if r["attention"]["level"] == "red")
    amber = sum(1 for r in results if r["attention"]["level"] == "amber")
    sys.stderr.write(f"Wrote {HEALTH_OUT} — 🔴 {red}  🟠 {amber}  🟢 {len(results) - red - amber}\n")
    return 0


# --------------------------------------------------------------------------- #
# readme regeneration
# --------------------------------------------------------------------------- #
def render_projects_block(registry: list[dict]) -> str:
    lines: list[str] = []
    for category, heading in CATEGORY_LABELS:
        in_cat = [p for p in registry if p.get("category") == category]
        if not in_cat:
            continue
        lines.append("")
        lines.append(heading)
        lines.append("")
        for p in in_cat:
            live = f" Live at [{p['live_url']}]({p['live_url']})." if p.get("live_url") else ""
            lines.append(f"- **[{p['name']}]({p['repo_url']})**: {p['description']}{live}")
    lines.append("")
    return "\n".join(lines)


def cmd_readme(args: argparse.Namespace) -> int:
    registry = load_registry()
    text = README.read_text()
    if AUTO_START not in text or AUTO_END not in text:
        sys.stderr.write(
            "ERROR: README.md is missing the AUTO:projects markers.\n"
            f"  Add a block delimited by:\n    {AUTO_START}\n    {AUTO_END}\n"
        )
        return 1
    pre, rest = text.split(AUTO_START, 1)
    _old, post = rest.split(AUTO_END, 1)
    block = render_projects_block(registry)
    new = f"{pre}{AUTO_START}\n{block}\n{AUTO_END}{post}"
    if new == text:
        sys.stderr.write("README.md AUTO:projects already up to date.\n")
        return 0
    if args.check:
        sys.stderr.write("README.md AUTO:projects is STALE (run `tools/dash-gen readme`).\n")
        return 1
    README.write_text(new)
    sys.stderr.write("Updated README.md AUTO:projects section.\n")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="dash-gen", description=__doc__)
    sub = parser.add_subparsers(dest="cmd", required=True)

    p_health = sub.add_parser("health", help="gather GitHub signals -> project_health.yml")
    p_health.set_defaults(func=cmd_health)

    p_readme = sub.add_parser("readme", help="regenerate README AUTO:projects span")
    p_readme.add_argument("--check", action="store_true", help="fail if stale; do not write")
    p_readme.set_defaults(func=cmd_readme)

    p_ai = sub.add_parser(
        "ai", help="shadow-price local Claude Code usage -> ai_activity.yml (local-only)"
    )
    ai_activity.add_arguments(p_ai)

    p_all = sub.add_parser("all", help="health + readme")
    p_all.add_argument("--check", action="store_true")
    p_all.set_defaults(func=lambda a: (cmd_health(a) or cmd_readme(a)))

    args = parser.parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    raise SystemExit(main())
