#!/usr/bin/env python3
"""
fleet_triage — committed fleet-wide snapshot of open issues, PRs, and CI state.

The open-state complement to daily_report (which covers the prior day's
ACTIVITY). Once a day this scans every repo in the registry and inventories
what is OPEN right now:

  - every open issue (count + items, capped per repo, with labels/age/author),
  - every open PR (count + items, with draft/dependabot/CI status/age),
  - every workflow's latest completed conclusion (and the failing ones),

then computes a deterministic attention score per repo and a unified,
prioritized "inbox" of the items most worth acting on. The result is written
to a COMMITTED data file — _data/fleet_triage.yml — rendered by the dash's
/triage/ portal page, so the fleet backlog is reviewable (and diffable) daily.

External mirrors (e.g. microsoft/skills) are shown per-repo but excluded from
fleet totals, attention scores, and the inbox — their backlog isn't ours.

Auth: a token from GH_TOKEN / GITHUB_TOKEN, else `gh auth token`. Unreachable
repos (404 / no access) are recorded in `repos_unreachable`, never fatal.
"""
from __future__ import annotations

import argparse
import datetime as dt
import sys
from pathlib import Path

import actions_analytics  # owner_repo, resolve_token, as_utc

try:
    import yaml
except ImportError:  # pragma: no cover
    sys.stderr.write("fleet_triage requires PyYAML: pip install pyyaml\n")
    sys.exit(2)

REPO_ROOT = Path(__file__).resolve().parents[3]
REGISTRY = REPO_ROOT / "_data" / "projects.yml"
THRESHOLDS = REPO_ROOT / "_data" / "health_thresholds.yml"
OUT_DEFAULT = REPO_ROOT / "_data" / "fleet_triage.yml"

GENERATED_HEADER = (
    "# GENERATED by .github/scripts/dash-gen (fleet_triage) — refreshed daily by "
    "daily-repo-analysis.yml. Edit the generator, not this file.\n"
)

# Latest-run conclusions that mark a workflow as failing (cancelled is noise).
FAILING_CONCLUSIONS = {"failure", "timed_out", "startup_failure"}

DEFAULT_THRESHOLDS = {"stale_issue_days": 30, "stale_pr_days": 14}

# The control-plane repo is not a registry project, but its open state (and
# failing workflows) belong on the portal like everyone else's.
HUB_NWO = "bamr87/bamr87"

ITEMS_CAP = 30          # issue/PR items stored per repo (counts stay exact)
INBOX_CAP = 150         # unified queue length
FAILING_RUNS_SCAN = 80  # newest runs scanned per repo for latest-per-workflow


def now_utc() -> dt.datetime:
    return dt.datetime.now(dt.timezone.utc)


def age_days(value) -> int | None:
    v = actions_analytics.as_utc(value)
    return (now_utc() - v).days if v else None


def load_thresholds() -> dict:
    th = dict(DEFAULT_THRESHOLDS)
    if THRESHOLDS.exists():
        try:
            with THRESHOLDS.open() as fh:
                data = yaml.safe_load(fh) or {}
            th.update({k: data[k] for k in DEFAULT_THRESHOLDS if k in data})
        except yaml.YAMLError:
            pass
    return th


def is_dependabot(login: str) -> bool:
    return login.lower().startswith("dependabot")


def ensure_hub(registry: list[dict]) -> list[dict]:
    """Prepend the hub repo unless the registry already lists it."""
    for p in registry:
        if actions_analytics.owner_repo(p.get("repo_url", "") or "") == HUB_NWO:
            return registry
    return [{"name": "bamr87 (hub)", "repo_url": f"https://github.com/{HUB_NWO}",
             "branch": "main"}] + list(registry)


# --------------------------------------------------------------------------- #
# per-repo collection
# --------------------------------------------------------------------------- #
def pr_ci_state(repo, sha: str) -> str:
    """Reduce a head commit's check runs to pass|fail|pending|none."""
    from github.GithubException import GithubException

    try:
        runs = list(repo.get_commit(sha).get_check_runs())
    except GithubException:
        return ""
    if not runs:
        return "none"
    concl = [(r.conclusion or "") for r in runs]
    if any(c in ("failure", "timed_out", "startup_failure") for c in concl):
        return "fail"
    if any(r.status != "completed" for r in runs):
        return "pending"
    return "pass"


def collect_repo(gh, project: dict, th: dict, pr_ci_cap: int) -> dict | None:
    """Inventory one repo's open state. None when the repo can't be read."""
    from github.GithubException import GithubException

    nwo = actions_analytics.owner_repo(project.get("repo_url", "") or "")
    if not nwo:
        return None
    external = not nwo.startswith("bamr87/")

    try:
        repo = gh.get_repo(nwo)
    except GithubException:
        return None

    rec: dict = {
        "name": project.get("name", nwo),
        "nwo": nwo,
        "repo_url": project.get("repo_url"),
        "external": external,
        "archived": bool(repo.archived),
        "private": bool(repo.private),
        "issues": {"open": 0, "stale": 0, "bugs": 0, "capped": False, "items": []},
        "prs": {"open": 0, "draft": 0, "stale": 0, "dependabot": 0,
                "ci_failing": 0, "capped": False, "items": []},
        "workflows": {"active": 0, "failing": []},
        "attention": {"score": 0, "level": "green", "reasons": []},
    }

    # --- open issues (get_issues includes PRs — filter them out) ------------
    # Inbox candidacy is evaluated over EVERY issue, not just the ITEMS_CAP
    # display list — the busiest repos' oldest bugs must still reach the inbox.
    rec["_issue_flags"] = []
    try:
        for iss in repo.get_issues(state="open"):
            # Raw-payload check: reading iss.pull_request on a list-fetched
            # Issue triggers a hidden per-issue GET (PyGithub lazy completion).
            if "pull_request" in iss._rawData:  # noqa: SLF001 — perf, not laziness
                continue
            rec["issues"]["open"] += 1
            labels = [l.name for l in iss.labels][:5]
            idle = age_days(iss.updated_at)
            stale = idle is not None and idle > th["stale_issue_days"]
            bug = any("bug" in l.lower() for l in labels)
            rec["issues"]["stale"] += 1 if stale else 0
            rec["issues"]["bugs"] += 1 if bug else 0
            if (bug or (idle is not None and idle > 90)) and len(rec["_issue_flags"]) < 40:
                rec["_issue_flags"].append({
                    "number": iss.number, "title": (iss.title or "")[:110],
                    "bug": bug, "idle_days": idle,
                    "age_days": age_days(iss.created_at), "url": iss.html_url,
                })
            if len(rec["issues"]["items"]) < ITEMS_CAP:
                rec["issues"]["items"].append({
                    "number": iss.number,
                    "title": (iss.title or "")[:110],
                    "labels": labels,
                    "author": iss.user.login if iss.user else "?",
                    "age_days": age_days(iss.created_at),
                    "idle_days": idle,
                    "url": iss.html_url,
                })
            else:
                rec["issues"]["capped"] = True
    except GithubException:
        pass

    # --- open PRs ------------------------------------------------------------
    rec["_pr_flags"] = []
    try:
        prs = []
        for pr in repo.get_pulls(state="open", sort="updated", direction="desc"):
            rec["prs"]["open"] += 1
            if len(prs) < 200:
                prs.append(pr)
        ci_checked = 0
        for pr in prs:
            author = pr.user.login if pr.user else "?"
            bot = is_dependabot(author)
            idle = age_days(pr.updated_at)
            stale = idle is not None and idle > th["stale_pr_days"]
            rec["prs"]["draft"] += 1 if pr.draft else 0
            rec["prs"]["dependabot"] += 1 if bot else 0
            rec["prs"]["stale"] += 1 if stale else 0
            ci = ""
            if not external and not pr.draft and ci_checked < pr_ci_cap:
                ci = pr_ci_state(repo, pr.head.sha)
                ci_checked += 1
            if ci == "fail":
                rec["prs"]["ci_failing"] += 1
            if (not pr.draft and (ci == "fail" or (idle is not None and idle > 14))
                    and len(rec["_pr_flags"]) < 40):
                rec["_pr_flags"].append({
                    "number": pr.number, "title": (pr.title or "")[:110],
                    "ci": ci, "idle_days": idle,
                    "age_days": age_days(pr.created_at), "url": pr.html_url,
                })
            if len(rec["prs"]["items"]) < ITEMS_CAP:
                rec["prs"]["items"].append({
                    "number": pr.number,
                    "title": (pr.title or "")[:110],
                    "author": author,
                    "draft": bool(pr.draft),
                    "dependabot": bot,
                    "ci": ci,
                    "age_days": age_days(pr.created_at),
                    "idle_days": idle,
                    "url": pr.html_url,
                })
            else:
                rec["prs"]["capped"] = True
    except GithubException:
        pass

    # --- workflows: active count + latest completed conclusion per workflow --
    try:
        rec["workflows"]["active"] = sum(
            1 for w in repo.get_workflows() if w.state == "active"
        )
    except GithubException:
        pass
    if not external:
        try:
            latest: dict[str, dict] = {}
            seen = 0
            for run in repo.get_workflow_runs():
                seen += 1
                if seen > FAILING_RUNS_SCAN:
                    break
                if run.status != "completed":
                    continue
                key = getattr(run, "path", "") or run.name or "?"
                if key in latest:
                    continue
                created = actions_analytics.as_utc(run.created_at)
                latest[key] = {
                    "workflow": run.name or "(workflow)",
                    "path": getattr(run, "path", "") or "",
                    "conclusion": run.conclusion or "?",
                    "run_url": run.html_url,
                    "run_at": created.strftime("%Y-%m-%d %H:%M UTC") if created else "?",
                }
            rec["workflows"]["failing"] = [
                v for v in latest.values() if v["conclusion"] in FAILING_CONCLUSIONS
            ]
        except GithubException:
            pass

    score_attention(rec)
    return rec


def score_attention(rec: dict) -> None:
    """Deterministic per-repo attention score; externals stay at zero."""
    if rec["external"]:
        rec["attention"]["reasons"] = ["external mirror — informational only"]
        return
    i, p, w = rec["issues"], rec["prs"], rec["workflows"]
    score = (6 * len(w["failing"]) + 4 * p["ci_failing"] + 2 * p["stale"]
             + 2 * i["stale"] + p["open"] + i["open"])
    reasons = []
    if w["failing"]:
        reasons.append(f"{len(w['failing'])} failing workflow(s)")
    if p["ci_failing"]:
        reasons.append(f"{p['ci_failing']} PR(s) with failing checks")
    if p["stale"]:
        reasons.append(f"{p['stale']} stale PR(s)")
    if i["stale"]:
        reasons.append(f"{i['stale']} stale issue(s)")
    if i["bugs"]:
        reasons.append(f"{i['bugs']} open bug(s)")
    if not reasons and (i["open"] or p["open"]):
        reasons.append("open backlog")
    if not reasons:
        reasons.append("clear")
    level = "green"
    if w["failing"] or p["ci_failing"]:
        level = "red"
    elif p["stale"] or i["stale"] or i["bugs"]:
        level = "amber"
    rec["attention"] = {"score": score, "level": level, "reasons": reasons}


# --------------------------------------------------------------------------- #
# report assembly
# --------------------------------------------------------------------------- #
def build_inbox(repos: list[dict]) -> list[dict]:
    """One prioritized queue across the fleet (bamr87-owned repos only).

    Consumes the _issue_flags/_pr_flags candidate lists gathered over the FULL
    iteration (not the ITEMS_CAP display lists), so capped repos still surface
    their oldest flagged items.
    """
    inbox: list[dict] = []
    for r in repos:
        if r["external"]:
            continue
        for f in r["workflows"]["failing"]:
            inbox.append({
                "kind": "workflow", "repo": r["name"], "nwo": r["nwo"],
                "ref": f["path"] or f["workflow"], "title": f["workflow"],
                "why": f"latest run {f['conclusion']}", "age_days": None,
                "url": f["run_url"], "priority": 90,
            })
        for p in r.get("_pr_flags", []):
            if p["ci"] == "fail":
                pri, why = 70, "PR checks failing"
            else:
                pri, why = 55, f"PR idle {p['idle_days']}d"
            inbox.append({
                "kind": "pr", "repo": r["name"], "nwo": r["nwo"],
                "ref": f"#{p['number']}", "title": p["title"], "why": why,
                "age_days": p["age_days"], "url": p["url"], "priority": pri,
            })
        for i in r.get("_issue_flags", []):
            if i["bug"]:
                pri, why = 60, "bug label"
            else:
                pri, why = 40, f"issue idle {i['idle_days']}d"
            inbox.append({
                "kind": "issue", "repo": r["name"], "nwo": r["nwo"],
                "ref": f"#{i['number']}", "title": i["title"], "why": why,
                "age_days": i["age_days"], "url": i["url"], "priority": pri,
            })
    inbox.sort(key=lambda x: (-x["priority"], -(x["age_days"] or 0)))
    return inbox[:INBOX_CAP]


def build_report(registry: list[dict], gh, th: dict, pr_ci_cap: int) -> dict:
    repos: list[dict] = []
    unreachable: list[str] = []
    for project in registry:
        nwo = actions_analytics.owner_repo(project.get("repo_url", "") or "")
        if not nwo:
            continue
        sys.stderr.write(f"  · {nwo}\n")
        try:
            rec = collect_repo(gh, project, th, pr_ci_cap)
        except Exception as exc:  # one unreadable repo must never sink the snapshot
            sys.stderr.write(f"    ! {nwo} skipped: {type(exc).__name__}: {exc}\n")
            rec = None
        if rec is None:
            unreachable.append(nwo)
        else:
            repos.append(rec)

    fleet = [r for r in repos if not r["external"]]
    ext = [r for r in repos if r["external"]]
    totals = {
        "open_issues": sum(r["issues"]["open"] for r in fleet),
        "stale_issues": sum(r["issues"]["stale"] for r in fleet),
        "open_bugs": sum(r["issues"]["bugs"] for r in fleet),
        "open_prs": sum(r["prs"]["open"] for r in fleet),
        "draft_prs": sum(r["prs"]["draft"] for r in fleet),
        "stale_prs": sum(r["prs"]["stale"] for r in fleet),
        "dependabot_prs": sum(r["prs"]["dependabot"] for r in fleet),
        "prs_ci_failing": sum(r["prs"]["ci_failing"] for r in fleet),
        "failing_workflows": sum(len(r["workflows"]["failing"]) for r in fleet),
        "repos_red": sum(1 for r in fleet if r["attention"]["level"] == "red"),
        "repos_amber": sum(1 for r in fleet if r["attention"]["level"] == "amber"),
        "external_open_issues": sum(r["issues"]["open"] for r in ext),
        "external_open_prs": sum(r["prs"]["open"] for r in ext),
    }
    repos.sort(key=lambda r: (-r["attention"]["score"], r["name"].lower()))
    inbox = build_inbox(repos)
    for r in repos:  # candidate scratch lists never reach the YAML
        r.pop("_issue_flags", None)
        r.pop("_pr_flags", None)
    return {
        "generated_at": now_utc().strftime("%Y-%m-%d %H:%M UTC"),
        "repos_scanned": len(repos),
        "repos_unreachable": unreachable,
        "totals": totals,
        "inbox": inbox,
        "by_repo": repos,
        "note": (
            "Open-state snapshot of every registry repo: all open issues and PRs "
            f"(items capped at {ITEMS_CAP}/repo; counts exact), plus each workflow's "
            "latest completed conclusion. External mirrors are excluded from totals, "
            "scores, and the inbox. PR CI state is checked for the most recently "
            "updated non-draft PRs per repo."
        ),
    }


# --------------------------------------------------------------------------- #
# entry point
# --------------------------------------------------------------------------- #
def run(args: argparse.Namespace) -> int:
    try:
        from github import Github, Auth
    except ImportError:
        sys.stderr.write("fleet_triage requires PyGithub: pip install PyGithub\n")
        return 2

    token = actions_analytics.resolve_token()
    if not token:
        sys.stderr.write("No GitHub token (set GH_TOKEN/GITHUB_TOKEN or run `gh auth login`).\n")
        return 2

    with REGISTRY.open() as fh:
        registry = yaml.safe_load(fh) or []

    registry = ensure_hub(registry)
    th = load_thresholds()
    gh = Github(auth=Auth.Token(token), per_page=100)
    sys.stderr.write(f"Triaging open state for {len(registry)} repos…\n")
    rep = build_report(registry, gh, th, args.pr_ci_cap)

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    with out.open("w") as fh:
        fh.write(GENERATED_HEADER)
        yaml.safe_dump(rep, fh, sort_keys=False, allow_unicode=True)

    t = rep["totals"]
    sys.stderr.write(
        f"Wrote {out} — {t['open_issues']} open issues · {t['open_prs']} open PRs "
        f"({t['prs_ci_failing']} failing checks) · {t['failing_workflows']} failing "
        f"workflow(s) · 🔴 {t['repos_red']} 🟠 {t['repos_amber']} · "
        f"{len(rep['inbox'])} inbox item(s)\n"
    )
    if args.print:
        for item in rep["inbox"][:20]:
            sys.stdout.write(f"{item['priority']:>3}  {item['kind']:<8} "
                             f"{item['repo']}/{item['ref']}  {item['why']}  {item['title']}\n")
    return 0


def add_arguments(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("--out", default=str(OUT_DEFAULT), metavar="PATH",
                        help="output YAML (default _data/fleet_triage.yml, committed)")
    parser.add_argument("--pr-ci-cap", type=int, default=8, metavar="N",
                        help="max non-draft PRs per repo to check CI state for (default 8)")
    parser.add_argument("--print", action="store_true",
                        help="also print the top of the inbox to stdout")
    parser.set_defaults(func=run)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="fleet-triage", description=__doc__)
    add_arguments(parser)
    args = parser.parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    raise SystemExit(main())
