#!/usr/bin/env python3
"""
harness_registry — the fleet-wide AI HARNESS + SCHEDULE inventory.

`harness.py` (singular) watches the hub's own six layers; THIS module watches
what is DEPLOYED: every AI harness call site and every cron schedule across
every registry repo, graded against the `harnesses:` contract in
_data/fleet.yml. It is the central-management surface the fleet lacked — the
one place that answers, for ~40 repos at once:

  OBSERVE    which repos carry which harness workflows (mention handlers,
             scheduled agents), on which claude-code-action ref, with which
             auth shape (OAuth-first is the house convention), which model and
             turn budget, and which agent-context kit version stamped them;
  SCHEDULES  every cron in the fleet — AI and not — normalized into estimated
             fires/day and a single UTC calendar, so standing load is a table
             rather than 40 repos' worth of workflow files;
  THROUGHPUT estimated scheduled AI runs/day (per repo and fleet-wide) versus
             the caps the contract declares, plus UTC-hour adjacency — the
             three Claude loops already share one OAuth account's rate limit;
  COST       spend trends from the committed usage ledgers (ai_usage.yml,
             actions_usage.yml): week-over-week growth and a projected monthly
             figure versus the declared budget ceilings;
  DRIFT      per-repo baseline coverage (mention handler, agent context,
             OAuth secret) and kit-version drift — the `gaps` feed that
             harness-fanout.yml and `dash harnesses deploy --gaps` target.
  FACTORY    GitFactory (bamr87/gitorio) provenance, in that app's own
             vocabulary: which repos carry a `.factory/` design (blueprints),
             which workflows are compiled LINES (the `⚙ GENERATED BY
             GITFACTORY` header + blueprint path/hash), and which scheduled
             agents are gated on a `vars.*_ENABLED` kill switch — the
             `gate` pattern that lets a line be disarmed without a commit.

This file is a CONSUMED INTERFACE: GitFactory's Fleet Studio (gitorio
specs/012-fleet-studio) reads the committed output as its fleet roster and
contract source. The `schema:` marker is the compatibility promise —
additive changes are free; a rename or removal bumps the marker
(docs/HARNESS-OPS.md, "Consumed by GitFactory").

Two halves, split on network:

  scan       PyGithub over each owned registry repo's .github/workflows/ (same
             auth conventions as fleet_triage/ai_usage_collector). Degrades:
             without a token (or with --offline) the previous committed scan
             is REUSED and only the offline analytics refresh, so a local
             `dash harnesses` run never needs credentials.
  analytics  pure functions over committed inputs — deterministic, offline,
             fixture-tested (test_harness_registry.py). Cron math is an
             ESTIMATE (documented per function), good for load planning, not
             for predicting exact fire times.

Output: _data/harness_registry.yml (committed, refreshed daily by
fleet-pulse.yml's pulse job, rendered at /harnesses/). Everything here is
read-only observation: a finding is an attention item for a human or for the
fan-out's dry-run PR path — never an auto-write into a fleet repo.
Full doc: docs/HARNESS-OPS.md
"""
from __future__ import annotations

import argparse
import datetime as dt
import math
import os
import re
import sys
from pathlib import Path

try:
    import yaml
except ImportError:  # pragma: no cover
    sys.stderr.write("harness_registry requires PyYAML: pip install pyyaml\n")
    sys.exit(2)

import actions_analytics  # registry loading + owner_repo + token resolution

REPO_ROOT = Path(__file__).resolve().parents[3]
FLEET_DEFAULT = REPO_ROOT / "_data" / "fleet.yml"
AI_USAGE_DEFAULT = REPO_ROOT / "_data" / "ai_usage.yml"
ACTIONS_DEFAULT = REPO_ROOT / "_data" / "actions_usage.yml"
ROTATION_DEFAULT = REPO_ROOT / "_data" / "token_rotation.yml"
OUT_DEFAULT = REPO_ROOT / "_data" / "harness_registry.yml"
KIT_VERSION_FILE = REPO_ROOT / "templates" / "agent-context" / "VERSION"

CLAUDE_ACTION_MARKER = "anthropics/claude-code-action"
ACTION_REF_RX = re.compile(r"anthropics/claude-code-action@(\S+)")
MODEL_RX = re.compile(r"--model\s+([\w.@-]+)")
MAX_TURNS_RX = re.compile(r"--max-turns\s+(\d+)")
KIT_STAMP_RX = re.compile(r"#\s*kit:\s*agent-context\s+v([0-9][\w.-]*)")
CRON_FALLBACK_RX = re.compile(r"cron:\s*['\"]([^'\"]+)['\"]")
# GitFactory provenance — the same expressions the app's fleet/facts.ts uses,
# so "factory-managed" means one thing on both sides of the seam.
FACTORY_HEADER_RX = re.compile(r"GENERATED BY GITFACTORY")
FACTORY_BLUEPRINT_RX = re.compile(r"blueprint:\s*(\S+)")
FACTORY_HASH_RX = re.compile(r"hash:\s*([0-9a-f]+)")
SWITCH_RX = re.compile(r"vars\.([A-Z][A-Z0-9_]*_ENABLED)\b")
FACTORY_DIR = ".factory"
BLUEPRINT_SUFFIX = ".blueprint.json"
SCHEMA_MARKER = "harness-registry/v1"  # bump on a breaking (non-additive) change

DAY_NAMES = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"]
AVG_DAYS_PER_MONTH = 30.44

# Root files that count as agent context, in detection order (mirrors
# tools/fanout.sh's agent-context guard).
AGENT_CONTEXT_FILES = ["CLAUDE.md", "AGENTS.md", ".cursorrules"]
COPILOT_CONTEXT_PATH = ".github/copilot-instructions.md"
MANIFEST_FILE = "fleet.manifest.yml"  # fleet/v1 lane manifest (bamr87/wtd spec)

# Mirrors the `harnesses:` block in _data/fleet.yml — that file is the
# contract, these are the fallbacks when a key (or the whole block) is absent.
DEFAULT_BASELINE = {
    "require_mention_handler": True,
    "require_agent_context": True,
    "require_oauth_secret": True,
}
DEFAULT_THROUGHPUT = {
    "max_scheduled_ai_per_day_fleet": 30,
    "max_scheduled_ai_per_day_repo": 8,
    "max_ai_crons_per_utc_hour": 3,
}
DEFAULT_BUDGET = {
    "monthly_ai_usd": 75,
    "monthly_actions_minutes": 120000,
    "trend_warn_pct": 50,
}
DEFAULT_INVENTORY = {
    "max_workflow_files": 40,
    "schedule_limit": 120,
}
DEFAULT_ATTENTION_MAX = 20


# --------------------------------------------------------------------------- #
# config
# --------------------------------------------------------------------------- #
def load_yaml(path: Path) -> dict:
    if not path.exists():
        return {}
    try:
        with path.open() as fh:
            data = yaml.safe_load(fh)
    except yaml.YAMLError:
        return {}
    return data if isinstance(data, dict) else {}


def load_config(fleet_path: Path) -> dict:
    fleet = load_yaml(fleet_path)
    cfg = fleet.get("harnesses") or {}
    return {
        "hub_nwo": (fleet.get("hub") or {}).get("repo") or "bamr87/bamr87",
        "kit": cfg.get("kit", "agent-context"),
        "baseline": {**DEFAULT_BASELINE, **(cfg.get("baseline") or {})},
        "exempt": list(cfg.get("exempt") or []),
        "throughput": {**DEFAULT_THROUGHPUT, **(cfg.get("throughput") or {})},
        "budget": {**DEFAULT_BUDGET, **(cfg.get("budget") or {})},
        "inventory": {**DEFAULT_INVENTORY, **(cfg.get("inventory") or {})},
        "attention_max": int(cfg.get("attention_max") or DEFAULT_ATTENTION_MAX),
    }


def hub_kit_version(path: Path = KIT_VERSION_FILE) -> str | None:
    """The kit version the fleet is graded against — read from the kit itself
    (templates/agent-context/VERSION), never duplicated into the contract."""
    try:
        for line in path.read_text().splitlines():
            if line.startswith("version:"):
                return line.split(":", 1)[1].strip()
    except OSError:
        pass
    return None


def _ver_tuple(v: str) -> tuple:
    parts = []
    for p in re.split(r"[.-]", v):
        parts.append(int(p) if p.isdigit() else 0)
    return tuple(parts or [0])


def kit_status(stamp: str | None, hub_version: str | None) -> str:
    """The stamp is the OBSERVABLE drift signal; whether an upgrade may be
    auto-applied stays fanout.sh's byte-compare decision (machine_seeded)."""
    if stamp is None:
        return "unstamped"
    if hub_version is None:
        return "unknown"
    a, b = _ver_tuple(stamp), _ver_tuple(hub_version)
    if a == b:
        return "current"
    return "upgradeable" if a < b else "ahead"


# --------------------------------------------------------------------------- #
# cron math (deterministic ESTIMATES — load planning, not fire prediction)
# --------------------------------------------------------------------------- #
def _parse_cron_field(field: str, lo: int, hi: int) -> set[int] | None:
    """One 5-field cron field -> the set of matching values, or None when the
    field is unparseable (names, L/W/# extensions). Numeric Vixie subset only:
    `*`, steps, ranges, lists."""
    values: set[int] = set()
    for part in field.split(","):
        part = part.strip()
        step = 1
        if "/" in part:
            part, step_s = part.split("/", 1)
            if not step_s.isdigit() or int(step_s) < 1:
                return None
            step = int(step_s)
        if part == "*":
            start, end = lo, hi
        elif "-" in part:
            a, _, b = part.partition("-")
            if not (a.isdigit() and b.isdigit()):
                return None
            start, end = int(a), int(b)
        elif part.isdigit():
            # `N/step` means N through hi in Vixie cron; a bare `N` is just N.
            start = int(part)
            end = hi if step > 1 else start
        else:
            return None
        if start < lo or end > hi or start > end:
            return None
        values.update(range(start, end + 1, step))
    return values


def parse_cron(cron: str) -> dict | None:
    """Parse a 5-field cron into value sets. dow 7 normalizes to 0 (Sunday)."""
    fields = cron.split()
    if len(fields) != 5:
        return None
    minutes = _parse_cron_field(fields[0], 0, 59)
    hours = _parse_cron_field(fields[1], 0, 23)
    doms = _parse_cron_field(fields[2], 1, 31)
    months = _parse_cron_field(fields[3], 1, 12)
    dows = _parse_cron_field(fields[4], 0, 7)
    if None in (minutes, hours, doms, months, dows):
        return None
    dows = {d % 7 for d in dows}
    return {
        "minutes": minutes, "hours": hours, "doms": doms,
        "months": months, "dows": dows,
        "dom_restricted": doms != set(range(1, 32)),
        "dow_restricted": dows != set(range(0, 7)),
        "month_restricted": months != set(range(1, 13)),
    }


def cron_fires_per_day(cron: str) -> float | None:
    """Average fires per calendar day. Approximation, documented:
    a day-of-week restriction scales by k/7, a day-of-month one by k/30.44,
    and when BOTH are restricted Vixie semantics are OR — approximated as the
    capped sum. Good enough to compare standing load against a cap; not a
    scheduler."""
    p = parse_cron(cron)
    if p is None:
        return None
    per_matching_day = len(p["minutes"]) * len(p["hours"])
    if p["dow_restricted"] and p["dom_restricted"]:
        frac = min(1.0, len(p["dows"]) / 7 + len(p["doms"]) / AVG_DAYS_PER_MONTH)
    elif p["dow_restricted"]:
        frac = len(p["dows"]) / 7
    elif p["dom_restricted"]:
        frac = min(1.0, len(p["doms"]) / AVG_DAYS_PER_MONTH)
    else:
        frac = 1.0
    if p["month_restricted"]:
        frac *= len(p["months"]) / 12
    return round(per_matching_day * frac, 3)


def describe_cron(cron: str) -> str:
    """Short human summary for the calendar; falls back to the raw expression."""
    p = parse_cron(cron)
    if p is None:
        return cron
    if len(p["minutes"]) == 1 and len(p["hours"]) == 1:
        t = f"{next(iter(p['hours'])):02d}:{next(iter(p['minutes'])):02d}"
        if p["dow_restricted"] and len(p["dows"]) == 1:
            return f"{DAY_NAMES[next(iter(p['dows']))]} {t} UTC weekly"
        if p["dom_restricted"] and len(p["doms"]) == 1:
            return f"day {next(iter(p['doms']))} {t} UTC monthly"
        if not p["dow_restricted"] and not p["dom_restricted"]:
            return f"daily {t} UTC"
        return f"{t} UTC ({cron})"
    if len(p["hours"]) == 24 and len(p["minutes"]) == 1:
        return f"hourly at :{next(iter(p['minutes'])):02d}"
    if len(p["minutes"]) > 1 and len(p["hours"]) == 24:
        step = 60 // len(p["minutes"])
        if len(p["minutes"]) in (2, 3, 4, 6, 12) and p["minutes"] == set(range(0, 60, step)):
            return f"every {step} min"
    if len(p["hours"]) > 1 and len(p["minutes"]) == 1 and len(p["hours"]) in (2, 3, 4, 6, 8, 12):
        step = 24 // len(p["hours"])
        if p["hours"] == set(range(0, 24, step)):
            return f"every {step}h at :{next(iter(p['minutes'])):02d}"
    return cron


# --------------------------------------------------------------------------- #
# workflow classification (pure text -> facts; no network)
# --------------------------------------------------------------------------- #
def classify_workflow(path: str, text: str) -> dict:
    """Extract the inventory facts from one workflow file's content.

    Tolerant by design: an unparseable YAML file still yields the regex-visible
    facts (claude marker, crons) plus parse_error=True, because a fleet scan
    that dies on one repo's broken workflow reports nothing about the other 39.
    """
    info: dict = {
        "path": path,
        "name": None,
        "triggers": [],
        "crons": [],
        "ai": CLAUDE_ACTION_MARKER in text,
        "parse_error": False,
    }
    data = None
    try:
        data = yaml.safe_load(text)
    except yaml.YAMLError:
        info["parse_error"] = True
    if isinstance(data, dict):
        name = data.get("name")
        info["name"] = str(name) if name is not None else None
        # YAML 1.1 parses a bare `on:` key as boolean True.
        on = data.get("on", data.get(True))
        if isinstance(on, dict):
            info["triggers"] = sorted(str(k) for k in on)
            sched = on.get("schedule")
            if isinstance(sched, list):
                info["crons"] = [
                    str(e["cron"]).strip() for e in sched
                    if isinstance(e, dict) and e.get("cron")
                ]
        elif isinstance(on, list):
            info["triggers"] = sorted(str(t) for t in on)
        elif isinstance(on, str):
            info["triggers"] = [on]
    else:
        info["parse_error"] = info["parse_error"] or data is not None or not text.strip()
        info["crons"] = CRON_FALLBACK_RX.findall(text)
        if "schedule" in text and info["crons"]:
            info["triggers"] = ["schedule"]
    if info["name"] is None:
        info["name"] = Path(path).stem
    # A compiled GitFactory line announces itself in its header, with the
    # blueprint it was compiled from and that blueprint's hash; a kill switch
    # is any repo variable named *_ENABLED the workflow reads (the `gate` job
    # pattern: an unset variable reads as idle, never as "safe to run").
    if FACTORY_HEADER_RX.search(text):
        bp = FACTORY_BLUEPRINT_RX.search(text)
        h = FACTORY_HASH_RX.search(text)
        info["factory"] = {"blueprint": bp.group(1) if bp else None,
                           "hash": h.group(1) if h else None}
    else:
        info["factory"] = None
    m = SWITCH_RX.search(text)
    info["switch"] = m.group(1) if m else None
    if info["ai"]:
        m = ACTION_REF_RX.search(text)
        info["action_ref"] = m.group(1) if m else None
        has_oauth = "claude_code_oauth_token" in text
        has_key = "anthropic_api_key" in text
        info["auth"] = (
            "oauth-first" if has_oauth and has_key
            else "oauth-only" if has_oauth
            else "api-key" if has_key
            else "none"
        )
        m = MODEL_RX.search(text)
        info["model"] = m.group(1) if m else None
        m = MAX_TURNS_RX.search(text)
        info["max_turns"] = int(m.group(1)) if m else None
        m = KIT_STAMP_RX.search(text)
        info["kit"] = m.group(1) if m else None
        # A prose "@claude" in a header comment must not read as a handler —
        # only a workflow that can actually RECEIVE a mention counts.
        mention_triggers = {"issue_comment", "issues",
                            "pull_request_review", "pull_request_review_comment"}
        info["mention_handler"] = (
            "@claude" in text and bool(mention_triggers & set(info["triggers"]))
        )
        info["kind"] = (
            "scheduled-agent" if info["crons"]
            else "mention-handler" if info["mention_handler"]
            else "event-agent"
        )
    return info


# --------------------------------------------------------------------------- #
# joins (committed ledgers -> per-repo / per-harness numbers; pure)
# --------------------------------------------------------------------------- #
def rotation_secret_states(rotation: dict, name: str = "CLAUDE_CODE_OAUTH_TOKEN") -> dict[str, str]:
    for token in rotation.get("tokens") or []:
        if isinstance(token, dict) and token.get("name") == name:
            return {
                r.get("nwo"): str(r.get("state"))
                for r in token.get("repos") or []
                if isinstance(r, dict) and r.get("nwo")
            }
    return {}


def join_usage(repos: list[dict], ai_usage: dict, actions_usage: dict) -> None:
    """Annotate scan rows in place with the committed ledgers' numbers. The
    windows are whatever those ledgers carry — echoed, never recomputed here."""
    ai_by_repo = {r.get("repo"): r for r in ai_usage.get("by_repo") or [] if isinstance(r, dict)}
    ai_by_wf = {
        w.get("workflow"): w for w in ai_usage.get("by_workflow") or [] if isinstance(w, dict)
    }
    act_by_path = {
        (w.get("repo"), w.get("path")): w
        for w in actions_usage.get("workflows") or []
        if isinstance(w, dict)
    }
    for repo in repos:
        a = ai_by_repo.get(repo.get("repo"))
        if a:
            repo["ai_usage"] = {
                "runs": a.get("runs"),
                "cost_usd": a.get("cost_usd"),
                "minutes": a.get("minutes"),
                "unpriced_runs": a.get("unpriced_runs"),
            }
        else:
            repo["ai_usage"] = None
        for h in repo.get("harnesses") or []:
            wf_key = f"{repo.get('repo')}/{h.get('workflow')}"
            u = ai_by_wf.get(wf_key)
            h["cost_usd_window"] = u.get("cost_usd") if u else None
            h["runs_window"] = u.get("runs") if u else None
            act = act_by_path.get((repo.get("repo"), h.get("path")))
            if act:
                h["last_conclusion"] = act.get("last_conclusion")
                h["flags"] = act.get("flags") or []
                if h.get("runs_window") is None:
                    h["runs_window"] = act.get("runs")
            else:
                h.setdefault("last_conclusion", None)
                h.setdefault("flags", [])


def evaluate_coverage(repo: dict, cfg: dict) -> None:
    """Grade one repo against the baseline. External upstreams, archived repos,
    unscanned rows, and explicit exemptions are excused, not failed."""
    baseline = cfg["baseline"]
    excused = (
        repo.get("external")
        or repo.get("archived")
        or not repo.get("scanned")
        or repo.get("status") == "archived"
        or repo.get("repo") in cfg["exempt"]
    )
    missing: list[str] = []
    if not excused:
        if baseline.get("require_mention_handler") and not any(
            h.get("mention_handler") for h in repo.get("harnesses") or []
        ):
            missing.append("mention-handler")
        if baseline.get("require_agent_context") and not repo.get("agent_context"):
            missing.append("agent-context")
        if baseline.get("require_oauth_secret") and repo.get("oauth_secret") in ("missing",):
            missing.append("oauth-secret")
    repo["coverage"] = {"exempt": bool(excused), "ok": not missing, "missing": missing}


def repo_schedule_load(repo: dict) -> float:
    """Estimated cron-driven AI workflow runs/day for one repo."""
    parts = [cron_fires_per_day(cron) or 0.0
             for h in repo.get("harnesses") or []
             for cron in h.get("crons") or []]
    return round(math.fsum(parts), 3)


def build_throughput(repos: list[dict], cfg: dict, ai_usage: dict) -> dict:
    caps = cfg["throughput"]
    # fsum, not sum: the per-repo estimates are floats whose plain left-to-right
    # total lands on rounding knife-edges (10.605 → 10.6 or 10.61 depending on
    # repo order), which churned this committed file on every daily refresh.
    fleet_est = round(math.fsum(r.get("est_scheduled_ai_per_day") or 0 for r in repos), 2)
    over_repo = [
        {"repo": r["repo"], "est_per_day": r["est_scheduled_ai_per_day"],
         "cap": caps["max_scheduled_ai_per_day_repo"]}
        for r in repos
        if (r.get("est_scheduled_ai_per_day") or 0) > caps["max_scheduled_ai_per_day_repo"]
    ]
    # UTC-hour adjacency: only single-shot AI crons (fixed hour set) count —
    # an hourly agent is a per-repo/fleet cap problem, not an adjacency one.
    hour_load: dict[int, list[str]] = {}
    for r in repos:
        for h in r.get("harnesses") or []:
            for cron in h.get("crons") or []:
                p = parse_cron(cron)
                if p is None or len(p["hours"]) > 3:
                    continue
                for hour in p["hours"]:
                    hour_load.setdefault(hour, []).append(f"{r['repo']}:{h['workflow']}")
    collisions = [
        {"utc_hour": f"{hour:02d}:00", "count": len(entries), "entries": sorted(entries)}
        for hour, entries in sorted(hour_load.items())
        if len(entries) > caps["max_ai_crons_per_utc_hour"]
    ]
    observed = None
    totals = ai_usage.get("totals") or {}
    window = ai_usage.get("window_days")
    if totals.get("ci_runs") is not None and window:
        observed = round(totals["ci_runs"] / float(window), 1)
    return {
        "est_scheduled_ai_per_day": fleet_est,
        "cap_fleet": caps["max_scheduled_ai_per_day_fleet"],
        "fleet_over_cap": fleet_est > caps["max_scheduled_ai_per_day_fleet"],
        "observed_ai_runs_per_day": observed,  # all triggers, from ai_usage.yml
        "repos_over_cap": over_repo,
        "hour_collisions": collisions,
        "cap_per_repo": caps["max_scheduled_ai_per_day_repo"],
        "cap_per_utc_hour": caps["max_ai_crons_per_utc_hour"],
    }


def _series_trend(series: list[tuple[str, float]], budget_monthly: float | None,
                  warn_pct: float) -> dict:
    """Window totals, week-over-week delta, and a projected monthly figure from
    one (day, value) series. Projection = last-7-day daily average × 30.44,
    falling back to the whole window when the series is shorter."""
    days = sorted(series)
    total = round(math.fsum(v for _, v in days), 2)
    out: dict = {
        "window_total": total,
        "daily_avg": round(total / len(days), 3) if days else None,
        "last7": None, "prior7": None, "wow_delta_pct": None,
        "projected_monthly": None,
        "budget_monthly": budget_monthly,
        "status": "no-data",
    }
    if not days:
        return out
    last_day = dt.date.fromisoformat(days[-1][0])
    cut7 = (last_day - dt.timedelta(days=6)).isoformat()
    cut14 = (last_day - dt.timedelta(days=13)).isoformat()
    last7 = round(math.fsum(v for d, v in days if d >= cut7), 2)
    prior7 = round(math.fsum(v for d, v in days if cut14 <= d < cut7), 2)
    out["last7"] = last7
    out["prior7"] = prior7
    if prior7 > 0:
        out["wow_delta_pct"] = round(100.0 * (last7 - prior7) / prior7, 1)
    daily = last7 / 7.0 if last7 or prior7 else (total / len(days))
    out["projected_monthly"] = round(daily * AVG_DAYS_PER_MONTH, 2)
    if budget_monthly is not None and out["projected_monthly"] > budget_monthly:
        out["status"] = "breach"
    elif out["wow_delta_pct"] is not None and out["wow_delta_pct"] > warn_pct:
        out["status"] = "growing"
    else:
        out["status"] = "ok"
    return out


def build_trends(ai_usage: dict, actions_usage: dict, cfg: dict) -> dict:
    budget = cfg["budget"]
    ai_series = [
        (str(r.get("day")), float(r.get("cost_usd") or 0))
        for r in ai_usage.get("by_day") or [] if isinstance(r, dict) and r.get("day")
    ]
    act_series = [
        (str(r.get("date")), float(r.get("total_min") or 0))
        for r in actions_usage.get("by_day") or [] if isinstance(r, dict) and r.get("date")
    ]
    return {
        "ai_cost_usd": _series_trend(ai_series, budget.get("monthly_ai_usd"),
                                     budget["trend_warn_pct"]),
        "actions_minutes": _series_trend(act_series, budget.get("monthly_actions_minutes"),
                                         budget["trend_warn_pct"]),
    }


# --------------------------------------------------------------------------- #
# attention (ranked findings — observations with the lever named, never writes)
# --------------------------------------------------------------------------- #
def build_attention(repos: list[dict], throughput: dict, trends: dict, cfg: dict) -> list[dict]:
    items: list[dict] = []

    def add(severity: int, kind: str, summary: str, action: str, repo: str | None = None):
        row = {"severity": severity, "kind": kind, "summary": summary, "action": action}
        if repo:
            row["repo"] = repo
        items.append(row)

    for key, label, unit in (("ai_cost_usd", "Claude CI spend", "USD"),
                             ("actions_minutes", "Actions minutes", "min")):
        t = trends.get(key) or {}
        if t.get("status") == "breach":
            add(90, "budget-breach",
                f"projected monthly {label} {t['projected_monthly']} {unit} exceeds the "
                f"{t['budget_monthly']} {unit} ceiling",
                "retune the loops' cadence/caps, or raise harnesses.budget in _data/fleet.yml")
        elif t.get("status") == "growing":
            add(50, "cost-trend",
                f"{label} grew {t['wow_delta_pct']}% week-over-week "
                f"(last 7d: {t['last7']} {unit})",
                "check /harnesses/ trends and the actions/ai-usage boards for the driver")

    if throughput.get("fleet_over_cap"):
        add(85, "throughput-fleet",
            f"estimated scheduled AI runs/day {throughput['est_scheduled_ai_per_day']} exceeds "
            f"the fleet cap {throughput['cap_fleet']}",
            "retire or slow a cron, or raise harnesses.throughput in _data/fleet.yml")
    for v in throughput.get("repos_over_cap") or []:
        add(80, "throughput-repo",
            f"estimated scheduled AI runs/day {v['est_per_day']} exceeds the per-repo cap {v['cap']}",
            "retune that repo's agent crons", repo=v["repo"])
    for c in throughput.get("hour_collisions") or []:
        add(70, "schedule-collision",
            f"{c['count']} AI crons share {c['utc_hour']} UTC: {', '.join(c['entries'][:6])}",
            "stagger the crons — the Claude loops share one OAuth account's rate limit")

    for r in repos:
        for h in r.get("harnesses") or []:
            if h.get("last_conclusion") == "failure" or "failing" in (h.get("flags") or []):
                add(75, "harness-failing",
                    f"{h['path']} last run failed",
                    "the fleet-pulse doctor queue owns the fix; see /triage/", repo=r["repo"])
            if h.get("auth") in ("api-key", "none"):
                add(60, "auth-drift",
                    f"{h['path']} auth is '{h['auth']}' (house convention is OAuth-first)",
                    "dispatch harness-fanout with upgrade, or align the call site by hand",
                    repo=r["repo"])
        cov = r.get("coverage") or {}
        for gap in cov.get("missing") or []:
            if gap == "oauth-secret":
                add(65, "coverage-gap",
                    "CLAUDE_CODE_OAUTH_TOKEN missing (per the rotation ledger)",
                    "token-rotation.yml enrols it weekly; `dash secrets rotate --apply` does it now",
                    repo=r["repo"])
            else:
                add(58 if gap == "mention-handler" else 55, "coverage-gap",
                    f"baseline artifact missing: {gap}",
                    "dispatch harness-fanout (target: gaps), or `dash harnesses deploy --gaps`",
                    repo=r["repo"])
        # A gap the kit could close on a repo the fan-out cannot reach: real
        # work, but `harness-fanout` is the wrong lever and would no-op.
        if (r.get("coverage") or {}).get("missing") and r.get("submodule") is False:
            closeable = set((r["coverage"]["missing"])) & {"mention-handler", "agent-context"}
            if closeable:
                add(35, "gap-not-deployable",
                    f"baseline gap the kit could close ({', '.join(sorted(closeable))}) but the "
                    "repo is not a submodule, so the fan-out cannot target it",
                    "add it to .gitmodules + the registry's submodule_path (`dash adopt`/onboard-dir), "
                    "or seed the kit by hand",
                    repo=r["repo"])
        upgradeable = [h["path"] for h in r.get("harnesses") or []
                       if h.get("kit_status") == "upgradeable"]
        if upgradeable:
            add(40, "kit-drift",
                f"machine-seeded harness behind the current kit: {', '.join(upgradeable)}",
                "dispatch harness-fanout with upgrade=true (byte-identical seeds only)",
                repo=r["repo"])
        # A scheduled agent is a standing commitment; without a repo-variable
        # kill switch the only way to stop it is a commit to its workflow.
        # Mention handlers are excused — they run only when asked.
        unswitched = [h["path"] for h in r.get("harnesses") or []
                      if h.get("kind") == "scheduled-agent" and not h.get("switch")]
        if unswitched:
            add(45, "switch-missing",
                f"scheduled agent without a vars.*_ENABLED kill switch: {', '.join(unswitched)}",
                "gate the line on a repo variable (GitFactory's `gate` job pattern) so it can be "
                "disarmed without a commit",
                repo=r["repo"])

    items.sort(key=lambda i: (-i["severity"], i.get("repo") or "", i["kind"]))
    return items[: cfg["attention_max"]]


# --------------------------------------------------------------------------- #
# fleet scan (the network half)
# --------------------------------------------------------------------------- #
def scan_repo(gh, project: dict, cfg: dict, secret_states: dict[str, str],
              hub_version: str | None) -> dict:
    name = project.get("name")
    nwo = actions_analytics.owner_repo(project.get("repo_url", ""))
    row: dict = {
        "repo": name,
        "nwo": nwo,
        "category": project.get("category"),
        "status": project.get("status"),
        "external": bool(nwo) and not nwo.startswith("bamr87/"),
        # fanout.sh resolves a --target through .gitmodules, so a registry repo
        # with no submodule_path cannot be deployed to no matter what its
        # coverage says. Recorded here so the board and `--gaps` agree.
        "submodule": bool(project.get("submodule_path")),
        "archived": False,
        "scanned": False,
        "manifest": False,
        "factory": False,
        "factory_blueprints": [],
        "agent_context": None,
        "oauth_secret": secret_states.get(nwo, "unknown"),
        "workflows_total": 0,
        "harnesses": [],
        "scheduled": [],
    }
    if nwo == cfg.get("hub_nwo"):
        row["oauth_secret"] = "hub"  # the canonical copy every rotation writes FROM
    if not nwo or row["external"]:
        return row
    try:
        repo = gh.get_repo(nwo)
        row["archived"] = bool(repo.archived)
    except Exception:
        return row
    try:
        root_names = {c.name for c in repo.get_contents("")}
    except Exception:
        root_names = set()
    row["manifest"] = MANIFEST_FILE in root_names
    # `.factory/` presence comes from the root listing already fetched (no
    # extra request); the blueprint NAMES cost one listing, only for repos
    # that actually carry the design directory.
    row["factory"] = FACTORY_DIR in root_names
    if row["factory"]:
        try:
            listing = repo.get_contents(FACTORY_DIR)
            if not isinstance(listing, list):
                listing = [listing]
            row["factory_blueprints"] = sorted(
                c.name for c in listing if c.name.endswith(BLUEPRINT_SUFFIX))
        except Exception:
            pass
    for cand in AGENT_CONTEXT_FILES:
        if cand in root_names:
            row["agent_context"] = cand
            break
    if row["agent_context"] is None:
        try:
            repo.get_contents(COPILOT_CONTEXT_PATH)
            row["agent_context"] = COPILOT_CONTEXT_PATH
        except Exception:
            pass
    try:
        listing = repo.get_contents(".github/workflows")
    except Exception:
        listing = []
    if not isinstance(listing, list):
        listing = [listing]
    files = [c for c in listing if c.name.endswith((".yml", ".yaml"))]
    files = files[: cfg["inventory"]["max_workflow_files"]]
    for entry in files:
        try:
            text = repo.get_contents(entry.path).decoded_content.decode("utf-8", "replace")
        except Exception:
            continue
        row["workflows_total"] += 1
        info = classify_workflow(entry.path, text)
        for cron in info["crons"]:
            row["scheduled"].append({
                "workflow": info["name"],
                "path": info["path"],
                "cron": cron,
                "human": describe_cron(cron),
                "est_per_day": cron_fires_per_day(cron),
                "ai": info["ai"],
            })
        if info["ai"]:
            row["harnesses"].append({
                "workflow": info["name"],
                "path": info["path"],
                "kind": info["kind"],
                "triggers": info["triggers"],
                "crons": info["crons"],
                "action_ref": info.get("action_ref"),
                "auth": info.get("auth"),
                "model": info.get("model"),
                "max_turns": info.get("max_turns"),
                "kit": info.get("kit"),
                "kit_status": kit_status(info.get("kit"), hub_version),
                "mention_handler": bool(info.get("mention_handler")),
                "switch": info.get("switch"),
                "factory": info.get("factory"),
            })
    row["scanned"] = True
    return row


def ensure_hub(registry: list[dict], cfg: dict) -> list[dict]:
    """The registry lists the PROJECTS; the hub itself is not one of them —
    yet it runs the fleet's heaviest scheduled agents (doctor, pipeline tiers,
    evolution). An inventory of "all the harnesses across all the repos" that
    omitted the control plane's own would be lying by omission, so the hub is
    injected as a scan target when the registry doesn't already carry it."""
    hub_nwo = cfg["hub_nwo"]
    url = f"https://github.com/{hub_nwo}"
    if any((p.get("repo_url") or "").rstrip("/").removesuffix(".git") == url
           for p in registry):
        return list(registry)
    hub_row = {"name": hub_nwo.split("/", 1)[-1], "repo_url": url,
               "category": "dash", "status": "active"}
    return [hub_row] + list(registry)


def collect_fleet(gh, registry: list[dict], cfg: dict, rotation: dict,
                  hub_version: str | None) -> list[dict]:
    secret_states = rotation_secret_states(rotation)
    rows = []
    for project in ensure_hub(registry, cfg):
        sys.stderr.write(f"  harness · {project.get('name')}\n")
        rows.append(scan_repo(gh, project, cfg, secret_states, hub_version))
    return rows


# --------------------------------------------------------------------------- #
# assembly
# --------------------------------------------------------------------------- #
def finalize(repos: list[dict], cfg: dict, hub_version: str | None, ai_usage: dict,
             actions_usage: dict, scan_mode: str, scanned_at: str | None,
             now: dt.datetime) -> dict:
    join_usage(repos, ai_usage, actions_usage)
    # Deployability is a registry fact, so stamp it in BOTH modes — a reused
    # scan predates the field, and without it the board, the attention queue
    # and `--gaps` would disagree about which gaps the fan-out can close.
    subs = submodule_names()
    for r in repos:
        r["submodule"] = r["repo"] in subs
        r["est_scheduled_ai_per_day"] = repo_schedule_load(r)
        evaluate_coverage(r, cfg)
    throughput = build_throughput(repos, cfg, ai_usage)
    trends = build_trends(ai_usage, actions_usage, cfg)
    attention = build_attention(repos, throughput, trends, cfg)

    calendar = []
    for r in repos:
        for s in r.get("scheduled") or []:
            calendar.append({"repo": r["repo"], **s})
    # AI crons first, then heaviest standing load — the operator's reading order.
    calendar.sort(key=lambda s: (not s["ai"], -(s.get("est_per_day") or 0),
                                 s["repo"], s["path"]))
    calendar = calendar[: cfg["inventory"]["schedule_limit"]]

    graded = [r for r in repos if not (r.get("coverage") or {}).get("exempt")]
    all_harnesses = [h for r in repos for h in r.get("harnesses") or []]
    totals = {
        "repos": len(repos),
        "repos_scanned": sum(1 for r in repos if r.get("scanned")),
        "repos_with_ai": sum(1 for r in repos if r.get("harnesses")),
        "ai_workflows": len(all_harnesses),
        "mention_handlers": sum(1 for h in all_harnesses if h.get("mention_handler")),
        "scheduled_agents": sum(1 for h in all_harnesses if h.get("kind") == "scheduled-agent"),
        "scheduled_workflows": sum(len(r.get("scheduled") or []) for r in repos),
        "est_scheduled_ai_per_day": throughput["est_scheduled_ai_per_day"],
        "baseline_ok": sum(1 for r in graded if (r.get("coverage") or {}).get("ok")),
        "baseline_gaps": sum(1 for r in graded if not (r.get("coverage") or {}).get("ok")),
        "kit_upgradeable": sum(1 for h in all_harnesses if h.get("kit_status") == "upgradeable"),
        "factory_repos": sum(1 for r in repos if r.get("factory")),
        "factory_lines": sum(1 for h in all_harnesses if h.get("factory")),
        "scheduled_switched": sum(1 for h in all_harnesses
                                  if h.get("kind") == "scheduled-agent" and h.get("switch")),
        "attention": len(attention),
    }
    return {
        "schema": SCHEMA_MARKER,
        "generated_at": now.strftime("%Y-%m-%d %H:%M UTC"),
        "scan": {"mode": scan_mode, "scanned_at": scanned_at},
        "contract": {
            "kit": cfg["kit"],
            "kit_version": hub_version,
            "baseline": cfg["baseline"],
            "exempt": cfg["exempt"],
            "throughput": cfg["throughput"],
            "budget": cfg["budget"],
        },
        "totals": totals,
        "trends": trends,
        "throughput": throughput,
        "attention": attention,
        "schedule": calendar,
        "repos": sorted(repos, key=lambda r: (
            (r.get("coverage") or {}).get("ok", True), -len(r.get("harnesses") or []),
            r.get("repo") or "")),
        "note": (
            "Fleet AI-harness + schedule inventory: deployments, crons, throughput, "
            "and cost trends graded against _data/fleet.yml `harnesses:` "
            "(docs/HARNESS-OPS.md). Read-only observation — the fixes belong to "
            "harness-fanout (deploy/upgrade), token-rotation (secrets), and the "
            "fleet-pulse doctor (failures). Consumed by GitFactory's Fleet Studio "
            "(bamr87/gitorio specs/012) — `schema` is the compatibility marker: "
            "additive changes are free, renames/removals bump it."
        ),
    }


def submodule_names(projects_path: Path | None = None) -> set[str]:
    """Registry entries that are checked-out submodules — the only targets
    fanout.sh can resolve (it looks a --target up in .gitmodules)."""
    path = Path(projects_path or actions_analytics.REGISTRY)
    if not path.exists():
        return set()
    try:
        with path.open() as fh:
            # the registry is a bare list; load_yaml() is dict-only and would
            # silently flatten it to {} — hence the direct read.
            data = yaml.safe_load(fh) or []
    except yaml.YAMLError:
        return set()
    projects = data.get("projects") if isinstance(data, dict) else data
    return {p["name"] for p in (projects or [])
            if isinstance(p, dict) and p.get("submodule_path") and p.get("name")}


def gap_candidates(registry_path: Path) -> list[dict]:
    """Every repo whose coverage the KIT could close, deployable or not."""
    data = load_yaml(registry_path)
    out = []
    for r in data.get("repos") or []:
        missing = set((r.get("coverage") or {}).get("missing") or [])
        upgradeable = any(
            h.get("kit_status") == "upgradeable" for h in r.get("harnesses") or []
        )
        if r.get("repo") and ((missing & {"mention-handler", "agent-context"}) or upgradeable):
            out.append(r)
    return out


def fanout_gaps(registry_path: Path, projects_path: Path | None = None) -> list[str]:
    """Repo names the fan-out can actually help: a kit-deployable baseline gap
    (mention handler / agent context) or an upgradeable machine seed. Secret
    gaps are token-rotation's lane and are deliberately not deploy targets.

    NON-SUBMODULE registry entries are excluded. fanout.sh resolves --target
    through .gitmodules and skips anything absent from it, so emitting one here
    produced a target list the deploy lever silently no-opped on — the whole
    `--gaps` run printing `skip X: not in .gitmodules` and exiting 0. Those
    repos surface as a `gap-not-deployable` attention item instead, which names
    the lever that CAN close them."""
    subs = submodule_names(projects_path)
    # `submodule` is absent from a scan committed before it was recorded, so
    # fall back to the registry rather than dropping every target.
    return [r["repo"] for r in gap_candidates(registry_path)
            if (r["submodule"] if "submodule" in r else r["repo"] in subs)]


# --------------------------------------------------------------------------- #
# entry point
# --------------------------------------------------------------------------- #
def run(args: argparse.Namespace) -> int:
    out_path = Path(args.out)
    if args.gaps:
        gaps = fanout_gaps(out_path)
        if not out_path.exists():
            sys.stderr.write(
                f"harnesses: no committed inventory at {out_path} — run "
                "`dash harnesses` first; emitting no targets.\n")
        for name in gaps:
            print(name)
        return 0

    now = dt.datetime.now(dt.timezone.utc)
    cfg = load_config(Path(args.fleet))
    hub_version = hub_kit_version()
    ai_usage = load_yaml(Path(args.ai_usage))
    actions_usage = load_yaml(Path(args.actions_usage))
    rotation = load_yaml(Path(args.rotation))

    token = None if args.offline else actions_analytics.resolve_token()
    repos: list[dict] = []
    scan_mode, scanned_at = "none", None
    if token:
        try:
            from github import Github, Auth
        except ImportError:
            sys.stderr.write("harnesses scan requires PyGithub: pip install PyGithub\n")
            token = None
        if token:
            gh = Github(auth=Auth.Token(token), per_page=100)
            with actions_analytics.REGISTRY.open() as fh:
                registry = yaml.safe_load(fh) or []
            repos = collect_fleet(gh, registry, cfg, rotation, hub_version)
            scan_mode, scanned_at = "live", now.strftime("%Y-%m-%d %H:%M UTC")
    if not repos:
        # No credentials (or --offline): reuse the previous committed scan so
        # the offline analytics still refresh — same degrade-don't-die posture
        # as every other gather step.
        prior = load_yaml(out_path)
        repos = prior.get("repos") or []
        scan_mode = "reused" if repos else "none"
        scanned_at = (prior.get("scan") or {}).get("scanned_at") or prior.get("generated_at")
        if not repos:
            sys.stderr.write(
                "harnesses: no GitHub token and no prior inventory to reuse — "
                "writing contract + trends only.\n")

    out = finalize(repos, cfg, hub_version, ai_usage, actions_usage,
                   scan_mode, scanned_at, now)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with out_path.open("w") as fh:
        fh.write(
            "# GENERATED by .github/scripts/dash-gen (harness_registry) — refreshed "
            "daily by fleet-pulse.yml. Edit the generator, not this file.\n"
        )
        yaml.safe_dump(out, fh, sort_keys=False, allow_unicode=True)

    t = out["totals"]
    if not args.quiet:
        sys.stderr.write(
            f"Wrote {out_path} — {t['ai_workflows']} AI workflows in "
            f"{t['repos_with_ai']}/{t['repos_scanned']} repos (scan: {scan_mode}), "
            f"{t['scheduled_workflows']} crons, "
            f"~{t['est_scheduled_ai_per_day']}/day scheduled AI, "
            f"{t['attention']} attention item(s)\n")
        for item in out["attention"][:5]:
            where = f" [{item['repo']}]" if item.get("repo") else ""
            sys.stderr.write(f"  ⚠ {item['kind']}{where}: {item['summary']}\n")

    gh_out = os.environ.get("GITHUB_OUTPUT")
    if gh_out:
        with open(gh_out, "a") as fh:
            fh.write(f"ai_workflows={t['ai_workflows']}\n")
            fh.write(f"attention_count={t['attention']}\n")
    return 0


def add_arguments(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("--fleet", default=str(FLEET_DEFAULT),
                        help="fleet.yml (harnesses: contract)")
    parser.add_argument("--ai-usage", default=str(AI_USAGE_DEFAULT),
                        help="ai_usage.yml input (cost joins + trends)")
    parser.add_argument("--actions-usage", default=str(ACTIONS_DEFAULT),
                        help="actions_usage.yml input (run joins + trends)")
    parser.add_argument("--rotation", default=str(ROTATION_DEFAULT),
                        help="token_rotation.yml input (secret presence)")
    parser.add_argument("--out", default=str(OUT_DEFAULT), help="output path")
    parser.add_argument("--days", type=int, default=14,
                        help="accepted for symmetry with the other gathers; the "
                             "joined windows are whatever the committed ledgers carry")
    parser.add_argument("--offline", action="store_true",
                        help="skip the GitHub scan; reuse the previous committed scan")
    parser.add_argument("--gaps", action="store_true",
                        help="print fan-out-deployable gap repos from the committed "
                             "inventory, one per line (offline; feeds harness-fanout)")
    parser.add_argument("--quiet", action="store_true", help="suppress the summary lines")
    parser.set_defaults(func=run)


if __name__ == "__main__":
    ap = argparse.ArgumentParser(description=__doc__)
    add_arguments(ap)
    raise SystemExit(run(ap.parse_args()))
