#!/usr/bin/env python3
"""
issue_pipeline — the deterministic half of the fleet's three-tier issue pipeline.

The fleet already has a loop that FIXES BROKEN WORKFLOWS (fleet-pulse → doctor).
This is the loop that RESOLVES ISSUES, and it runs in three tiers:

  T1  INTAKE     every new open issue is enriched: gaps in the report are filled,
                 the body is rewritten into the house template, an isolated
                 virtual environment reproduces it and attaches real EVIDENCE
                 (install/lint/test/build logs, screenshots, candidate files),
                 then type / priority / size / owner labels are applied.
  T2  IMPLEMENT  an issue that reached `agent:ready` is implemented on a branch
                 and lands as a DRAFT pull request.
  T3  COMPLETE   that PR is driven to mergeable: CI green, tests and docs
                 present, body accurate — then marked ready for review.

This module owns everything DETERMINISTIC about that: which issues are at which
tier, what is missing from each, how urgent it is, how big it is, who owns it,
whether it may proceed autonomously, and how much work each tier may take on.
The AI tiers only ever act on a pre-vetted, capped, deduped queue — the same
guarantee that keeps the remediation loop from spamming the fleet.

STATE LIVES IN LABELS, NOT IN A DATABASE
----------------------------------------
Every stage transition is a GitHub label (`agent:ready`, `agent:in-pr`, …).
That choice is deliberate:

  * it survives a lost run, a cancelled job, and a rewritten data file — the
    pipeline is a SWEEP over current state, not a chain of events that dies
    silently when one link doesn't fire (the exact failure that froze this
    fleet's data for three weeks);
  * a human can re-queue, skip, or stop any issue by editing a label, with no
    tooling and no commit;
  * `agent:hold` and `human-review` are honoured everywhere, so opting out is
    always one click.

Hidden markers in comments/PR bodies are the audit trail and the second dedupe
guard; the labels are the state machine.

Auth: a token from GH_TOKEN / GITHUB_TOKEN, else `gh auth token`. Unreachable
repos are recorded, never fatal. Exit status is 0 with an empty queue — a fleet
with nothing to triage is the healthy steady state.
"""
from __future__ import annotations

import argparse
import datetime as dt
import json
import os
import re
import sys
from pathlib import Path

import actions_analytics  # owner_repo, resolve_token, as_utc

try:
    import yaml
except ImportError:  # pragma: no cover
    sys.stderr.write("issue_pipeline requires PyYAML: pip install pyyaml\n")
    sys.exit(2)

REPO_ROOT = Path(__file__).resolve().parents[3]
REGISTRY = REPO_ROOT / "_data" / "projects.yml"
FLEET = REPO_ROOT / "_data" / "fleet.yml"
TRIAGE = REPO_ROOT / "_data" / "fleet_triage.yml"
OUT_DEFAULT = REPO_ROOT / "_data" / "issue_pipeline.yml"

GENERATED_HEADER = (
    "# GENERATED by .github/scripts/dash-gen (issue_pipeline) — refreshed by "
    "issue-pipeline.yml. Edit the generator, not this file.\n"
)

HUB_NWO = "bamr87/bamr87"

# --------------------------------------------------------------------------- #
# defaults — every one of these is overridable from _data/fleet.yml.
# The module must work with the block absent, so nothing here may be required.
# --------------------------------------------------------------------------- #
DEFAULT_STATE_LABELS = {
    "queued": "agent:queued",
    "ready": "agent:ready",
    "blocked": "agent:blocked",
    "in_pr": "agent:in-pr",
    "done": "agent:done",
    "hold": "agent:hold",
    "human_review": "human-review",
}

DEFAULT_TYPES = ["bug", "feature", "docs", "chore", "ci", "refactor",
                 "test", "security", "question"]
DEFAULT_PRIORITIES = ["P0", "P1", "P2", "P3"]
DEFAULT_SIZES = ["size:xs", "size:s", "size:m", "size:l", "size:xl"]

DEFAULT_CONFIG = {
    "enabled": True,
    "hub": HUB_NWO,
    "branch_prefix": "agent/issue",
    "tiers": {
        "intake": {"max_issues": 8, "max_per_repo": 3},
        "implement": {"max_issues": 3, "max_cross_repo": 2},
        "complete": {"max_prs": 4},
    },
    "evidence": {"enabled": True, "max_runs": 6, "ttl_days": 7,
                 "timeout_minutes": 12, "screenshots": True},
    "readiness": {"min_score": 70},
    "autonomy": {
        "default": "auto",
        "never_merge": True,
        "assisted_types": ["security"],
        "assisted_sizes": ["size:xl"],
        "assisted_priorities": [],
    },
    "owners": {"default": "bamr87", "by_category": {}, "by_repo": {}},
    "labels": {"state": DEFAULT_STATE_LABELS, "types": DEFAULT_TYPES,
               "priorities": DEFAULT_PRIORITIES, "sizes": DEFAULT_SIZES},
}

# Label colours for `--sync-labels`. Kept beside the taxonomy so a new label can
# never be created by three tiers with three different colours.
LABEL_COLORS = {
    "agent:queued": ("FBCA04", "Issue pipeline — picked up for intake"),
    "agent:ready": ("0E8A16", "Issue pipeline — enriched and ready to implement"),
    "agent:blocked": ("B60205", "Issue pipeline — needs a human decision"),
    "agent:in-pr": ("1D76DB", "Issue pipeline — a pull request is open for this"),
    "agent:done": ("5319E7", "Issue pipeline — pull request is ready for review"),
    "agent:hold": ("000000", "Issue pipeline — do not touch this issue"),
    "human-review": ("D93F0B", "Human review required before merge"),
    "bug": ("D73A4A", "Something isn't working"),
    "feature": ("A2EEEF", "New capability"),
    "docs": ("0075CA", "Documentation"),
    "chore": ("FEF2C0", "Maintenance"),
    "ci": ("BFD4F2", "Build / CI / automation"),
    "refactor": ("C2E0C6", "Internal restructuring, no behaviour change"),
    "test": ("D4C5F9", "Test coverage"),
    "security": ("B60205", "Security-relevant"),
    "question": ("CC317C", "Needs clarification"),
    "P0": ("B60205", "Urgent — broken, unsafe, or blocking"),
    "P1": ("D93F0B", "High"),
    "P2": ("FBCA04", "Normal"),
    "P3": ("C5DEF5", "Low / someday"),
    "size:xs": ("EDEDED", "Under an hour"),
    "size:s": ("EDEDED", "A few hours"),
    "size:m": ("EDEDED", "About a day"),
    "size:l": ("EDEDED", "Several days"),
    "size:xl": ("EDEDED", "Multi-week — split it"),
    "automation": ("BFD4F2", "Automated / bot-generated"),
}

# --------------------------------------------------------------------------- #
# text signals
# --------------------------------------------------------------------------- #
# Ordered, not scored: the FIRST pattern that matches wins, so "crash leaking
# the API key" is security rather than whichever pattern happened to match more
# often. `ci` precedes `bug` because most auto-filed issues in this fleet are
# workflow problems, and "CI is red" is a more actionable type than "bug".
TYPE_PATTERNS = [
    # Deliberately narrow. A broad security pattern is worse than none: these
    # issues quote workflow YAML, and matching a bare `credential`/`injection`
    # typed every fleet-doctor ticket that mentioned `secrets.FLEET_TOKEN` as
    # security — which forced P0 and human review on routine CI fixes.
    # A leak is "leak" NEAR a credential noun, in either order and within one
    # clause — "leaks the API token", "the deploy token was leaked". Requiring
    # them adjacent missed both real phrasings; matching the noun alone typed
    # every workflow that referenced a secret as a security issue.
    ("security", r"\b(?:security|vulnerabilit|CVE-\d|exploit|XSS|CSRF|RCE|"
                 r"SQL injection)\b"
                 r"|\bleak(?:s|ed|ing)?\b[^.\n]{0,40}"
                 r"\b(?:token|secret|key|credential|password)s?\b"
                 r"|\b(?:token|secret|key|credential|password)s?\b[^.\n]{0,40}"
                 r"\bleak(?:s|ed|ing)?\b"),
    ("ci", r"\b(CI|workflow|github actions|pipeline|build fails?|lint fails?|"
           r"deploy(?:ment)? fails?)\b"),
    ("bug", r"\b(bug|broken|fails?|failing|error|crash|exception|traceback|"
            r"regression|does ?n[o']t work|incorrect|wrong|500|404|NPE|panic)\b"),
    ("docs", r"\b(docs?|documentation|readme|typo|wording|changelog)\b"),
    ("test", r"\b(tests?|coverage|spec|fixture|flaky)\b"),
    ("refactor", r"\b(refactor|clean ?up|restructure|simplif|dedup|tech debt)\b"),
    ("feature", r"\b(add|support|implement|feature|enhance|introduce|"
                r"would be nice|request)\b"),
    ("chore", r"\b(chore|bump|upgrade|dependenc|maintenance|housekeep)\b"),
    ("question", r"\b(question|how do i|how to|clarif|unclear|why does)\b"),
]
TYPE_RES = [(t, re.compile(p, re.I)) for t, p in TYPE_PATTERNS]

SEVERITY_RE = re.compile(
    r"\b(data ?loss|corrupt|outage|down|unusable|blocker|urgent|critical|"
    r"cannot|can'?t|crash|hang|deadlock|security|leak|regression|prod(uction)?)\b",
    re.I)
REPRO_RE = re.compile(
    r"(steps? to reproduce|repro(duction|duce)?\b|^\s*\d+[.)]\s+\S|```|"
    r"^\s*\$ |to reproduce)", re.I | re.M)
EXPECTED_RE = re.compile(r"\b(expected|should (be|happen|return)|instead)\b", re.I)
ACTUAL_RE = re.compile(r"\b(actual|but (it|the)|observed|currently)\b", re.I)
ENVIRONMENT_RE = re.compile(
    r"\b(version|v?\d+\.\d+\.\d+|os:|macos|linux|ubuntu|windows|browser|chrome|"
    r"firefox|safari|node|python|ruby|docker|branch:)\b", re.I)
ACCEPTANCE_RE = re.compile(
    r"(acceptance criteria|definition of done|done when|^\s*[-*]\s*\[[ xX]\])",
    re.I | re.M)
# A path-ish token: `src/thing.ts`, `tools/dash`, `_data/fleet.yml`.
PATH_RE = re.compile(r"[\w.\-/]+\.[A-Za-z0-9]{1,6}\b|\b(?:tools|src|lib|app|"
                     r"_data|docs|\.github)/[\w.\-/]+")
LINK_RE = re.compile(r"https?://\S+")
IMAGE_RE = re.compile(r"!\[[^\]]*\]\(\S+\)|<img\s|\.(png|jpe?g|gif|webp)\b", re.I)
LOG_RE = re.compile(r"```[\s\S]{80,}?```|Traceback|at .*\(.*:\d+:\d+\)|"
                    r"^\s*(ERROR|FATAL|WARN)\b", re.I | re.M)
BIG_WORK_RE = re.compile(
    r"\b(rewrite|migrat|overhaul|redesign|architect|multi[- ]repo|fleet[- ]wide|"
    r"breaking change|epic|rollout)\b", re.I)
SMALL_WORK_RE = re.compile(
    r"\b(typo|rename|one[- ]liner|bump|tweak|copy ?edit|wording|comment)\b", re.I)

MARKER_RE = re.compile(r'<!-- issue-pipeline tier="(\d)" key="([^"]+)" -->')
EVIDENCE_MARKER_RE = re.compile(r'<!-- issue-evidence key="([^"]+)"'
                                r'(?: at="([^"]*)")? -->')
CLOSES_RE = re.compile(r"\b(clos(?:e|es|ed)|fix(?:e[sd])?|resolv(?:e|es|ed))\s+"
                       r"#(\d+)\b", re.I)


def now_utc() -> dt.datetime:
    return dt.datetime.now(dt.timezone.utc)


def age_days(value) -> int | None:
    v = actions_analytics.as_utc(value)
    return (now_utc() - v).days if v else None


def deep_merge(base: dict, over: dict) -> dict:
    out = dict(base)
    for k, v in (over or {}).items():
        if isinstance(v, dict) and isinstance(out.get(k), dict):
            out[k] = deep_merge(out[k], v)
        else:
            out[k] = v
    return out


def load_yaml(path: Path) -> dict:
    if not path.exists():
        return {}
    try:
        with path.open() as fh:
            return yaml.safe_load(fh) or {}
    except yaml.YAMLError:
        return {}


def load_config(path: Path) -> dict:
    return deep_merge(DEFAULT_CONFIG, load_yaml(path).get("issue_pipeline") or {})


# --------------------------------------------------------------------------- #
# pure analysis — everything below is testable without a network
# --------------------------------------------------------------------------- #
def marker(tier: int, key: str) -> str:
    return f'<!-- issue-pipeline tier="{tier}" key="{key}" -->'


def issue_key(nwo: str, number: int) -> str:
    return f"{nwo}#{number}"


def detect_type(title: str, body: str, labels: list[str], types: list[str]) -> str:
    """Existing type label wins, then the title, then the body.

    The TITLE is consulted before the body on purpose. A title is a deliberate
    one-line summary; a body is a transcript that quotes logs, stack traces, and
    workflow YAML belonging to something else entirely. Matching over the
    concatenation let a 6 KB body's incidental `secrets.FLEET_TOKEN` retype a
    translation bug as a security issue — which then forced it to P0 and to
    human review. Title-first is both more accurate and more explainable.
    """
    for lab in labels:
        low = lab.lower()
        if low in types:
            return low
        if low in ("enhancement", "feature request"):
            return "feature"
        if low in ("documentation",):
            return "docs"
    for source in (title or "", body or ""):
        for name, rx in TYPE_RES:
            if name in types and rx.search(source):
                return name
    return "chore" if "chore" in types else (types[0] if types else "chore")


def detect_gaps(*, title: str, body: str, labels: list[str], itype: str,
                has_assignee: bool, has_evidence: bool, cfg: dict) -> list[dict]:
    """What this issue is missing before an agent could implement it unattended.

    Each gap says who can close it: `agent` gaps are T1's job (it can read the
    code and run the evidence harness); `human` gaps are product decisions no
    amount of evidence resolves, and they are what puts an issue on
    `agent:blocked` instead of `agent:ready`.
    """
    body = body or ""
    text = f"{title}\n{body}"
    lab = {l.lower() for l in labels}
    tax = cfg["labels"]
    gaps: list[dict] = []

    def add(gid, weight, by, what, how):
        gaps.append({"id": gid, "weight": weight, "by": by, "what": what, "how": how})

    if len(body.strip()) < 60:
        add("no-body", 30, "human" if len(title) < 25 else "agent",
            "the issue body is empty or a single line",
            "reconstruct intent from the title, the referenced code, and the "
            "evidence run; if intent is genuinely ambiguous, ask and block")
    if itype in ("bug", "security", "ci"):
        if not REPRO_RE.search(text):
            add("no-repro", 20, "agent",
                "no reproduction steps or command",
                "derive a minimal reproduction and prove it in the evidence "
                "workspace; paste the exact command and its output")
        if not (EXPECTED_RE.search(text) and ACTUAL_RE.search(text)):
            add("no-expected-actual", 12, "agent",
                "expected vs actual behaviour is not stated",
                "state both explicitly, citing the evidence log for 'actual'")
        if not ENVIRONMENT_RE.search(text):
            add("no-environment", 8, "agent",
                "no environment/version information",
                "fill it from the evidence run's env.md (toolchain versions, "
                "commit SHA, OS)")
        if not LOG_RE.search(text):
            add("no-logs", 8, "agent",
                "no logs, stack trace, or command output",
                "attach the failing excerpt from the evidence logs — trimmed to "
                "the relevant lines, in a fenced block")
    if not ACCEPTANCE_RE.search(text):
        add("no-acceptance", 15, "agent",
            "no acceptance criteria",
            "write a checkbox list a reviewer could verify mechanically; each "
            "item must be observable (a test, a command, a rendered page)")
    if not PATH_RE.search(text):
        add("no-scope", 12, "agent",
            "no files, modules, or paths identified",
            "list the candidate files from the evidence grep, ranked, with why")
    if not LINK_RE.search(text):
        add("no-references", 4, "agent",
            "no references (docs, prior issues, upstream links)",
            "link the relevant doc, SCHEMA.md row, prior issue, or upstream "
            "changelog entry")
    # Case-insensitive on both sides: GitHub label names preserve case but match
    # case-insensitively, and the taxonomy mixes cases (`bug`, `P1`, `size:s`).
    # Comparing a lowercased label set against the raw taxonomy silently reports
    # every `P1` issue as unprioritised.
    if not (lab & {t.lower() for t in tax["types"]}):
        add("no-type-label", 6, "agent", "no type label",
            f"apply exactly one of: {', '.join(tax['types'])}")
    if not (lab & {t.lower() for t in tax["priorities"]}):
        add("no-priority-label", 6, "agent", "no priority label",
            "apply the computed priority label")
    if not (lab & {t.lower() for t in tax["sizes"]}):
        add("no-size-label", 4, "agent", "no size estimate",
            "apply the computed size label")
    if not has_assignee:
        add("no-owner", 4, "agent", "no assignee",
            "assign the configured owner for this repo")
    if cfg["evidence"]["enabled"] and not has_evidence:
        add("no-evidence", 20, "agent",
            "no evidence bundle attached",
            "run tools/issue-evidence.sh and post the summary comment")
    return gaps


def readiness(gaps: list[dict]) -> int:
    """0–100. 100 means an agent could start implementing right now."""
    return max(0, 100 - sum(g["weight"] for g in gaps))


def score_priority(*, itype: str, title: str, body: str, age: int | None,
                   comments: int, reactions: int, repo_status: str,
                   repo_red: bool) -> int:
    base = {"security": 45, "bug": 32, "ci": 28, "test": 14, "feature": 16,
            "refactor": 10, "docs": 10, "chore": 6, "question": 8}
    score = base.get(itype, 10)
    text = f"{title}\n{body or ''}"
    if SEVERITY_RE.search(text):
        score += 22
    if repo_red and itype in ("bug", "ci", "security"):
        # The repo's CI is already red — an issue about it is blocking whatever
        # that pipeline gates, which is strictly more urgent than the same
        # report against a green repo.
        score += 12
    if repo_status == "active":
        score += 8
    elif repo_status in ("archived", "experiment"):
        score -= 8
    score += min(12, comments * 2) + min(8, reactions)
    if age is not None:
        # Age raises urgency, but slowly and with a ceiling: an old issue is not
        # automatically more important than a fresh outage.
        score += min(10, age // 30 * 2)
    return max(0, min(100, score))


def priority_label(score: int, priorities: list[str]) -> str:
    thresholds = [80, 55, 30]
    for i, t in enumerate(thresholds):
        if score >= t and i < len(priorities):
            return priorities[i]
    return priorities[-1] if priorities else "P3"


def estimate_size(*, title: str, body: str, itype: str, sizes: list[str]) -> str:
    """Coarse, deliberately pessimistic-on-the-tails size estimate."""
    text = f"{title}\n{body or ''}"
    paths = len(set(PATH_RE.findall(text)))
    idx = 1  # size:s
    if itype in ("docs", "chore") or SMALL_WORK_RE.search(text):
        idx = 0
    if itype in ("feature", "refactor"):
        idx = 2
    if paths >= 4 or len(text) > 2500:
        idx += 1
    if BIG_WORK_RE.search(text):
        idx = max(idx, 3)
        if paths >= 6 or "fleet" in text.lower():
            idx = 4
    idx = max(0, min(idx, len(sizes) - 1))
    return sizes[idx]


def decide_autonomy(*, itype: str, size: str, prio: str, labels: list[str],
                    cfg: dict) -> tuple[str, str]:
    """auto | assisted | blocked, plus the reason.

    `assisted` still gets a PR — it just never gets marked ready-for-review by
    T3. That is the whole meaning of the `human-review` tag: the machine does
    all the work and stops one step short of asking for a merge.
    """
    aut = cfg["autonomy"]
    state = cfg["labels"]["state"]
    lab = {l.lower() for l in labels}
    if state["hold"].lower() in lab:
        return "blocked", f"`{state['hold']}` label — excluded by a human"
    if state["human_review"].lower() in lab:
        return "assisted", f"`{state['human_review']}` label — human merges"
    if itype in (aut.get("assisted_types") or []):
        return "assisted", f"type `{itype}` always gets human review"
    if size in (aut.get("assisted_sizes") or []):
        return "assisted", f"size `{size}` is too large to land unattended"
    if prio in (aut.get("assisted_priorities") or []):
        return "assisted", f"priority `{prio}` always gets human review"
    return aut.get("default", "auto"), "no gate matched"


def classify_stage(labels: list[str], cfg: dict, *, has_open_pr: bool) -> str:
    """intake | ready | in-pr | blocked | done | hold — the label state machine."""
    state = cfg["labels"]["state"]
    lab = {l.lower() for l in labels}
    if state["hold"].lower() in lab:
        return "hold"
    if state["done"].lower() in lab:
        return "done"
    if has_open_pr or state["in_pr"].lower() in lab:
        return "in-pr"
    if state["blocked"].lower() in lab:
        return "blocked"
    if state["ready"].lower() in lab:
        return "ready"
    return "intake"


def resolve_owner(cfg: dict, *, nwo: str, category: str) -> str:
    owners = cfg["owners"]
    return (owners.get("by_repo", {}).get(nwo)
            or owners.get("by_category", {}).get(category)
            or owners.get("default", "")
            or "")


# --------------------------------------------------------------------------- #
# collection
# --------------------------------------------------------------------------- #
def red_repos(triage: dict) -> set[str]:
    """Repos whose latest workflow run is failing, per the daily triage snapshot."""
    out = set()
    for r in triage.get("by_repo", []) or []:
        if (r.get("workflows") or {}).get("failing"):
            out.add(r.get("nwo") or "")
    return {x for x in out if x}


def ensure_hub(registry: list[dict]) -> list[dict]:
    for p in registry:
        if actions_analytics.owner_repo(p.get("repo_url", "") or "") == HUB_NWO:
            return registry
    return [{"name": "bamr87 (hub)", "repo_url": f"https://github.com/{HUB_NWO}",
             "branch": "main", "status": "active", "category": "dash"}] + list(registry)


def linked_issue_numbers(pr_body: str) -> set[int]:
    return {int(m.group(2)) for m in CLOSES_RE.finditer(pr_body or "")}


def collect_repo(gh, project: dict, cfg: dict, reds: set[str]) -> tuple[dict | None, str]:
    """Inventory one repo's open issues + pipeline PRs.

    Returns `(record, "")` on success, or `(None, reason)`. The reason matters:
    "I deliberately skip upstream mirrors" and "my token cannot see this repo"
    are different findings, and reporting the first as the second sends you
    chasing access problems that do not exist — the same distinction
    reconcile.py draws for 404s.
    """
    from github.GithubException import GithubException

    nwo = actions_analytics.owner_repo(project.get("repo_url", "") or "")
    if not nwo:
        return None, "no-repo-url"
    # A queue whose output is pull requests must never include a repo we do not
    # own. Derived from the owner, never read from a possibly-absent flag.
    if not nwo.startswith(f"{cfg['hub'].split('/', 1)[0]}/"):
        return None, "external"
    try:
        repo = gh.get_repo(nwo)
    except GithubException:
        return None, "unreachable"
    if repo.archived:
        return None, "archived"

    state = cfg["labels"]["state"]
    rec = {
        "nwo": nwo,
        "name": project.get("name", nwo),
        "repo_url": project.get("repo_url") or f"https://github.com/{nwo}",
        "category": project.get("category", ""),
        "status": project.get("status", ""),
        "default_branch": project.get("branch") or repo.default_branch,
        "private": bool(repo.private),
        "stack": project.get("stack") or [],
        "issues": [],
        "prs": [],
        "counts": {"intake": 0, "ready": 0, "in-pr": 0, "blocked": 0,
                   "done": 0, "hold": 0},
    }

    # --- pipeline PRs first: an issue with an open PR is at T3, not T1 -------
    linked: dict[int, dict] = {}
    try:
        for pr in repo.get_pulls(state="open", sort="updated", direction="desc")[:60]:
            labels = [l.name for l in pr.labels]
            body = pr.body or ""
            nums = linked_issue_numbers(body)
            branch = pr.head.ref if pr.head else ""
            is_pipeline = (state["in_pr"] in labels
                           or branch.startswith(cfg["branch_prefix"])
                           or bool(MARKER_RE.search(body)))
            prec = {
                "number": pr.number,
                "title": (pr.title or "")[:140],
                "url": pr.html_url,
                "draft": bool(pr.draft),
                "branch": branch,
                "labels": labels,
                "linked_issues": sorted(nums),
                "pipeline": is_pipeline,
                "human_review": state["human_review"] in labels,
                "age_days": age_days(pr.created_at),
                "idle_days": age_days(pr.updated_at),
                "ci": "",
                "mergeable_state": "",
                "head_sha": pr.head.sha if pr.head else "",
            }
            if is_pipeline:
                try:
                    prec["ci"] = _pr_ci_state(repo, prec["head_sha"])
                    prec["mergeable_state"] = pr.mergeable_state or ""
                except GithubException:
                    pass
                rec["prs"].append(prec)
            for n in nums:
                linked[n] = prec
    except GithubException:
        pass

    # --- open issues ---------------------------------------------------------
    try:
        for iss in repo.get_issues(state="open"):
            # Raw-payload check: touching iss.pull_request on a list-fetched
            # Issue triggers a hidden per-issue GET (PyGithub lazy completion).
            if "pull_request" in iss._rawData:  # noqa: SLF001 — perf, not laziness
                continue
            labels = [l.name for l in iss.labels]
            body = iss.body or ""
            title = iss.title or ""
            pr = linked.get(iss.number)
            stage = classify_stage(labels, cfg, has_open_pr=pr is not None)
            rec["counts"][stage] = rec["counts"].get(stage, 0) + 1
            itype = detect_type(title, body, labels, cfg["labels"]["types"])
            prio_score = score_priority(
                itype=itype, title=title, body=body,
                age=age_days(iss.created_at), comments=iss.comments or 0,
                reactions=_reactions(iss), repo_status=rec["status"],
                repo_red=nwo in reds)
            prio = priority_label(prio_score, cfg["labels"]["priorities"])
            size = estimate_size(title=title, body=body, itype=itype,
                                 sizes=cfg["labels"]["sizes"])
            autonomy, autonomy_why = decide_autonomy(
                itype=itype, size=size, prio=prio, labels=labels, cfg=cfg)
            # Preliminary gap analysis, assuming no evidence: it costs nothing
            # (no extra API call) and it is what makes `readiness` a real
            # tiebreaker during queue selection. enrich_candidates() recomputes
            # it for the shortlist once the evidence comment is actually known.
            gaps = detect_gaps(title=title, body=body, labels=labels,
                               itype=itype, has_assignee=bool(iss.assignees),
                               has_evidence=False, cfg=cfg)
            rec["issues"].append({
                "number": iss.number,
                "key": issue_key(nwo, iss.number),
                "title": title[:140],
                "url": iss.html_url,
                "author": iss.user.login if iss.user else "?",
                "labels": labels,
                "assignees": [a.login for a in iss.assignees],
                "comments": iss.comments or 0,
                "age_days": age_days(iss.created_at),
                "idle_days": age_days(iss.updated_at),
                "body_chars": len(body),
                "has_images": bool(IMAGE_RE.search(body)),
                "stage": stage,
                "type": itype,
                "priority": prio,
                "priority_score": prio_score,
                "size": size,
                "autonomy": autonomy,
                "autonomy_reason": autonomy_why,
                "owner": resolve_owner(cfg, nwo=nwo, category=rec["category"]),
                "pr": {"number": pr["number"], "url": pr["url"]} if pr else None,
                # refined in the bounded second pass (needs a comments fetch)
                "evidence": None,
                "gaps": gaps,
                "readiness": readiness(gaps),
                "_body": body,
            })
    except GithubException:
        pass
    return rec, ""


def _reactions(iss) -> int:
    try:
        return int((iss._rawData.get("reactions") or {}).get("total_count", 0))  # noqa: SLF001
    except (AttributeError, TypeError, ValueError):
        return 0


def _pr_ci_state(repo, sha: str) -> str:
    """pass | fail | pending | none for a PR head commit."""
    from github.GithubException import GithubException
    if not sha:
        return ""
    try:
        runs = list(repo.get_commit(sha).get_check_runs())
    except GithubException:
        return ""
    if not runs:
        return "none"
    concl = [(r.conclusion or "") for r in runs]
    if any(c in ("failure", "timed_out", "startup_failure") for c in concl):
        return "fail"
    if any(r.status != "completed" for r in runs):
        return "pending"
    return "pass"


def enrich_candidates(gh, cands: list[dict], cfg: dict) -> None:
    """Second pass over the CAPPED shortlist only: comments → evidence freshness.

    Comment fetches are per-issue and the fleet has hundreds of open issues, so
    this deliberately runs after the cap rather than during collection — the API
    cost is bounded by the queue size, not by the backlog size.
    """
    from github.GithubException import GithubException

    ttl = cfg["evidence"]["ttl_days"]
    for c in cands:
        nwo, num = c["key"].split("#")
        seen_tiers: set[int] = set()
        evidence = None
        try:
            issue = gh.get_repo(nwo).get_issue(int(num))
            for com in issue.get_comments():
                cbody = com.body or ""
                for m in MARKER_RE.finditer(cbody):
                    seen_tiers.add(int(m.group(1)))
                if EVIDENCE_MARKER_RE.search(cbody):
                    age = age_days(com.created_at)
                    evidence = {"at": str(com.created_at), "age_days": age,
                                "url": com.html_url,
                                "fresh": age is not None and age <= ttl}
        except (GithubException, ValueError):
            pass
        c["evidence"] = evidence
        c["tiers_seen"] = sorted(seen_tiers)
        c["needs_evidence"] = bool(cfg["evidence"]["enabled"]
                                   and not (evidence and evidence["fresh"]))
        c["gaps"] = detect_gaps(
            title=c["title"], body=c.get("_body", ""), labels=c["labels"],
            itype=c["type"], has_assignee=bool(c["assignees"]),
            has_evidence=bool(evidence and evidence["fresh"]), cfg=cfg)
        c["readiness"] = readiness(c["gaps"])
        c["blocking_gaps"] = [g["id"] for g in c["gaps"] if g["by"] == "human"]


# --------------------------------------------------------------------------- #
# queue selection
# --------------------------------------------------------------------------- #
def queue_sort_key(c: dict):
    """Priority first, then how nearly ready it is, then age.

    Readiness ranks ABOVE age on purpose: at T2 the nearly-complete issue is the
    one an agent can actually finish today, and shipping it clears the queue
    faster than starting the oldest half-specified one.
    """
    order = {"P0": 0, "P1": 1, "P2": 2, "P3": 3}
    return (order.get(c["priority"], 9), -c["readiness"], -(c["age_days"] or 0))


def build_queues(repos: list[dict], cfg: dict) -> dict[str, list[dict]]:
    t = cfg["tiers"]
    intake: list[dict] = []
    ready: list[dict] = []
    complete: list[dict] = []

    for r in repos:
        per_repo = 0
        for i in sorted(r["issues"], key=queue_sort_key):
            item = dict(i)
            item.update({"nwo": r["nwo"], "repo": r["name"],
                         "repo_url": r["repo_url"], "category": r["category"],
                         "status": r["status"], "stack": r["stack"],
                         "private": r["private"],
                         "default_branch": r["default_branch"]})
            if item["stage"] == "intake" and item["autonomy"] != "blocked":
                if per_repo < t["intake"]["max_per_repo"]:
                    intake.append(item)
                    per_repo += 1
            elif item["stage"] == "ready" and item["autonomy"] != "blocked":
                ready.append(item)
        for p in r["prs"]:
            if not p["pipeline"]:
                continue
            # Nothing to do for a PR that is already green, non-draft, and
            # merge-ready — T3's job is finished on it.
            if not p["draft"] and p["ci"] == "pass":
                continue
            complete.append({**p, "nwo": r["nwo"], "repo": r["name"],
                             "repo_url": r["repo_url"],
                             "default_branch": r["default_branch"]})

    intake.sort(key=queue_sort_key)
    ready.sort(key=queue_sort_key)
    # Red CI first, then drafts waiting to be finished, then the stalest.
    complete.sort(key=lambda p: (0 if p["ci"] == "fail" else 1,
                                 0 if p["draft"] else 1,
                                 -(p["idle_days"] or 0)))

    hub = cfg["hub"]
    capped_ready: list[dict] = []
    cross = 0
    for c in ready:
        if c["nwo"] != hub:
            if cross >= t["implement"]["max_cross_repo"]:
                continue
            cross += 1
        capped_ready.append(c)
        if len(capped_ready) >= t["implement"]["max_issues"]:
            break

    return {
        "intake": intake[: t["intake"]["max_issues"]],
        "implement": capped_ready,
        "complete": complete[: t["complete"]["max_prs"]],
    }


# --------------------------------------------------------------------------- #
# work orders
# --------------------------------------------------------------------------- #
def _hdr(title: str, cfg: dict, counts: dict) -> list[str]:
    return [
        f"# {title}",
        "",
        f"Generated {now_utc().strftime('%Y-%m-%d %H:%M UTC')} · fleet "
        f"{counts['repos']} repo(s) · {counts['open_issues']} open issue(s) · "
        f"queue caps from `_data/fleet.yml` → `issue_pipeline.tiers`.",
        "",
    ]


def render_t1(q: list[dict], cfg: dict, counts: dict) -> str:
    L = _hdr("Tier 1 — issue intake work order", cfg, counts)
    if not q:
        L += ["**Nothing to intake.** Every open issue is already enriched, "
              "blocked on a human, in a PR, or on hold. Do not invent work.", ""]
        return "\n".join(L)
    ev = cfg["evidence"]
    L += [f"{len(q)} issue(s) queued. Evidence runs are capped at "
          f"{ev['max_runs']} this pass (TTL {ev['ttl_days']}d, "
          f"{ev['timeout_minutes']}m each).", ""]
    for i, c in enumerate(q, 1):
        L += ["---", "",
              f"## {i}. {c['nwo']}#{c['number']} — {c['title']}", "",
              f"- **URL:** {c['url']}",
              f"- **Reported by:** @{c['author']} · {c['age_days']}d old · "
              f"{c['comments']} comment(s) · body {c['body_chars']} chars"
              + (" · has images" if c["has_images"] else ""),
              f"- **Repo:** `{c['nwo']}` ({c['category'] or 'uncategorised'} · "
              f"{c.get('status') or 'status unknown'}) · stack: "
              f"{', '.join(c['stack']) or 'unknown'} · default branch "
              f"`{c['default_branch']}`"
              + ("  _(private)_" if c.get("private") else ""),
              f"- **Computed:** type `{c['type']}` · priority `{c['priority']}` "
              f"(score {c['priority_score']}) · size `{c['size']}` · owner "
              f"`{c['owner'] or 'unassigned'}` · autonomy `{c['autonomy']}` "
              f"({c['autonomy_reason']})",
              f"- **Readiness:** {c['readiness']}/100 "
              f"(target ≥ {cfg['readiness']['min_score']})",
              "- **MARKER** — the enrichment comment's FIRST line must be exactly "
              "this, verbatim, or the next run re-enriches it:", "",
              marker(1, c["key"]), ""]
        if c.get("needs_evidence"):
            L += [f"- **Evidence: REQUIRED.** Run:", "",
                  f"  ```bash",
                  f"  tools/issue-evidence.sh --repo {c['nwo']} --issue {c['number']} \\",
                  f"      --ref {c['default_branch']} --out evidence/{c['nwo'].split('/')[-1]}-{c['number']}",
                  f"  ```", ""]
        else:
            e = c.get("evidence") or {}
            L += [f"- **Evidence:** already attached "
                  f"({e.get('age_days')}d old) — {e.get('url')}", ""]
        L += ["- **Gaps to close** (`agent` = you close it; `human` = ask, then "
              "apply `agent:blocked`):", ""]
        for g in c["gaps"]:
            L.append(f"    - `{g['id']}` ({g['by']}, −{g['weight']}) — "
                     f"{g['what']}. → {g['how']}")
        if not c["gaps"]:
            L.append("    - _none — apply labels and mark ready._")
        L += ["", f"- **Exit:** apply `{cfg['labels']['state']['ready']}` when "
              f"readiness would reach ≥ {cfg['readiness']['min_score']} with no "
              f"`human` gaps left; otherwise apply "
              f"`{cfg['labels']['state']['blocked']}` and say exactly what you "
              f"need.", ""]
    return "\n".join(L)


def render_t2(q: list[dict], cfg: dict, counts: dict) -> str:
    L = _hdr("Tier 2 — implementation work order", cfg, counts)
    if not q:
        L += ["**Nothing to implement.** No issue is at `agent:ready` without an "
              "open PR. Do not pull work forward from tier 1.", ""]
        return "\n".join(L)
    L += [f"{len(q)} issue(s) queued (cap {cfg['tiers']['implement']['max_issues']}, "
          f"≤{cfg['tiers']['implement']['max_cross_repo']} outside the hub). "
          f"Every PR is a DRAFT.", ""]
    for i, c in enumerate(q, 1):
        slug = f"{cfg['branch_prefix']}-{c['number']}"
        L += ["---", "",
              f"## {i}. {c['nwo']}#{c['number']} — {c['title']}", "",
              f"- **URL:** {c['url']}",
              f"- **Computed:** `{c['type']}` · `{c['priority']}` · `{c['size']}` "
              f"· autonomy `{c['autonomy']}` ({c['autonomy_reason']})",
              f"- **Readiness:** {c['readiness']}/100",
              f"- **Fix location:** "
              + ("this checkout — branch, commit, and open the PR here."
                 if c["nwo"] == cfg["hub"] else
                 f"**{c['nwo']}** — clone it to a scratch dir (never into "
                 f"`projects/`), branch there, and open the PR in THAT repo."),
              f"- **Branch:** `{slug}` off `{c['default_branch']}`",
              f"- **Stack:** {', '.join(c['stack']) or 'detect from the repo'}",
              "- **MARKER** — first line of the PR body, verbatim:", "",
              marker(2, c["key"]), "",
              f"- **Link the issue:** the PR body must contain "
              f"`Closes #{c['number']}` (same-repo) so the state machine can "
              f"pair them.",
              f"- **On success:** label the issue "
              f"`{cfg['labels']['state']['in_pr']}` and remove "
              f"`{cfg['labels']['state']['ready']}`.", ""]
        if c["autonomy"] == "assisted":
            L += [f"- ⚠️ **Assisted:** {c['autonomy_reason']}. Implement fully, "
                  f"but tier 3 will NOT mark this ready for review — a human "
                  f"does.", ""]
    return "\n".join(L)


def render_t3(q: list[dict], cfg: dict, counts: dict) -> str:
    L = _hdr("Tier 3 — completion work order", cfg, counts)
    if not q:
        L += ["**Nothing to complete.** Every pipeline PR is green, non-draft, "
              "and waiting on a human. Do not touch PRs the pipeline did not "
              "open.", ""]
        return "\n".join(L)
    L += [f"{len(q)} pull request(s) queued (cap "
          f"{cfg['tiers']['complete']['max_prs']}). Never merge — "
          f"`issue_pipeline.autonomy.never_merge` is "
          f"`{cfg['autonomy']['never_merge']}`.", ""]
    for i, p in enumerate(q, 1):
        L += ["---", "",
              f"## {i}. {p['nwo']}#{p['number']} — {p['title']}", "",
              f"- **URL:** {p['url']}",
              f"- **State:** {'draft' if p['draft'] else 'ready'} · CI "
              f"`{p['ci'] or 'unknown'}` · mergeable "
              f"`{p['mergeable_state'] or 'unknown'}` · {p['age_days']}d old · "
              f"idle {p['idle_days']}d",
              f"- **Branch:** `{p['branch']}` → `{p['default_branch']}`",
              f"- **Closes:** "
              + (", ".join(f"#{n}" for n in p["linked_issues"]) or "_nothing linked_"),
              f"- **Read CI:** `gh pr checks {p['number']} -R {p['nwo']}` then "
              f"`gh run view -R {p['nwo']} <run_id> --log-failed`", ""]
        if p["ci"] == "fail":
            L.append("- 🔴 **CI is red — fixing it is this PR's whole job.** Read "
                     "the failing log, fix the cause, push. Do not add "
                     "`continue-on-error`, do not delete the failing test.")
        L += ["- **Definition of done:** CI green · tests cover the change · docs "
              "and the nearest `README.md`/`SCHEMA.md` updated · PR body accurate "
              "and still carrying its marker · no unrelated diff.", ""]
        if p["human_review"]:
            L += [f"- ⚠️ **`{cfg['labels']['state']['human_review']}` is set** — "
                  f"finish the work, leave the PR as a DRAFT, and comment that "
                  f"it awaits human review. Do NOT mark it ready.", ""]
        else:
            L += [f"- **On green:** `gh pr ready {p['number']} -R {p['nwo']}` and "
                  f"label the linked issue(s) "
                  f"`{cfg['labels']['state']['done']}`.", ""]
    return "\n".join(L)


# --------------------------------------------------------------------------- #
# report + outputs
# --------------------------------------------------------------------------- #
def build_report(repos: list[dict], queues: dict, cfg: dict,
                 skipped: dict[str, list[str]]) -> dict:
    stage_totals: dict[str, int] = {}
    for r in repos:
        for k, v in r["counts"].items():
            stage_totals[k] = stage_totals.get(k, 0) + v
    by_repo = []
    for r in sorted(repos, key=lambda r: (-len(r["issues"]), r["name"].lower())):
        if not r["issues"] and not r["prs"]:
            continue
        by_repo.append({
            "name": r["name"], "nwo": r["nwo"], "repo_url": r["repo_url"],
            "category": r["category"], "stages": r["counts"],
            "open_issues": len(r["issues"]),
            "pipeline_prs": len(r["prs"]),
        })

    def slim(item: dict) -> dict:
        return {k: v for k, v in item.items()
                if not k.startswith("_") and k not in ("stack",)}

    return {
        "generated_at": now_utc().strftime("%Y-%m-%d %H:%M UTC"),
        "enabled": bool(cfg["enabled"]),
        "repos_scanned": len(repos),
        # Split by REASON. "deliberately out of scope" and "my token cannot see
        # it" look identical in a flat list, and conflating them sends you
        # chasing access problems that do not exist.
        "repos_skipped": skipped,
        "repos_unreachable": skipped.get("unreachable", []),
        "totals": {
            "open_issues": sum(len(r["issues"]) for r in repos),
            "pipeline_prs": sum(len(r["prs"]) for r in repos),
            "stages": stage_totals,
            "queued_intake": len(queues["intake"]),
            "queued_implement": len(queues["implement"]),
            "queued_complete": len(queues["complete"]),
        },
        "caps": cfg["tiers"],
        "labels": cfg["labels"],
        "queues": {k: [slim(i) for i in v] for k, v in queues.items()},
        "by_repo": by_repo,
        "note": (
            "Three-tier issue pipeline state. Stage is derived from labels, so a "
            "human can re-queue, skip, or stop any issue by editing one label. "
            "Queues are the CAPPED shortlists the agent tiers act on this run; "
            "`stages` counts the whole fleet. Generated by "
            ".github/workflows/issue-pipeline.yml."
        ),
    }


def emit_output(key: str, value) -> None:
    path = os.environ.get("GITHUB_OUTPUT")
    if path:
        with open(path, "a") as fh:
            fh.write(f"{key}={value}\n")


def sync_labels(nwos: list[str], taxonomy: dict, apply: bool) -> int:
    """Create/refresh the pipeline's labels in each target repo.

    T1 cannot apply a label that does not exist, and `gh issue edit --add-label`
    fails the whole call when ANY label is unknown — so one missing label in one
    repo silently costs that issue its entire triage. Creating them up front is
    cheaper than discovering that per-repo.
    """
    import subprocess
    names = ([*taxonomy["state"].values(), *taxonomy["types"],
              *taxonomy["priorities"], *taxonomy["sizes"], "automation"])
    rc = 0
    for nwo in nwos:
        for name in names:
            color, desc = LABEL_COLORS.get(name, ("EDEDED", "Issue pipeline"))
            cmd = ["gh", "label", "create", name, "-R", nwo, "--color", color,
                   "--description", desc, "--force"]
            if not apply:
                sys.stdout.write(f"[dry-run] {' '.join(cmd)}\n")
                continue
            out = subprocess.run(cmd, capture_output=True, text=True)
            if out.returncode != 0:
                sys.stderr.write(f"  ! {nwo}: {name}: "
                                 f"{(out.stderr or '').strip()[:120]}\n")
                rc = 1
    return rc


# --------------------------------------------------------------------------- #
# entry point
# --------------------------------------------------------------------------- #
def run(args: argparse.Namespace) -> int:
    cfg = load_config(Path(args.config))
    if args.hub:
        cfg["hub"] = args.hub
    for key, val in (("intake", args.max_intake), ("implement", args.max_implement),
                     ("complete", args.max_complete)):
        if val is not None:
            k = "max_prs" if key == "complete" else "max_issues"
            cfg["tiers"][key][k] = val

    registry = ensure_hub(load_registry(Path(args.registry)))
    if args.repos:
        wanted = {w.strip().lower() for w in args.repos.split(",") if w.strip()}
        registry = [p for p in registry
                    if (actions_analytics.owner_repo(p.get("repo_url", "") or "") or "").lower() in wanted
                    or (p.get("slug") or "").lower() in wanted
                    or (p.get("name") or "").lower() in wanted]
        if not registry:
            sys.stderr.write(f"No registry repo matched --repos {args.repos}\n")
            return 2

    if args.sync_labels:
        nwos = [actions_analytics.owner_repo(p.get("repo_url", "") or "")
                for p in registry]
        return sync_labels([n for n in nwos if n], cfg["labels"], args.apply)

    if not cfg["enabled"] and not args.force:
        sys.stderr.write("issue_pipeline is disabled in _data/fleet.yml "
                         "(issue_pipeline.enabled: false); pass --force to override.\n")
        for k in ("intake", "implement", "complete"):
            emit_output(f"has_{k}", "false")
            emit_output(f"{k}_count", 0)
        return 0

    try:
        from github import Github, Auth
    except ImportError:
        sys.stderr.write("issue_pipeline requires PyGithub: pip install PyGithub\n")
        return 2
    token = actions_analytics.resolve_token()
    if not token:
        sys.stderr.write("No GitHub token (set GH_TOKEN/GITHUB_TOKEN or run "
                         "`gh auth login`).\n")
        return 2

    gh = Github(auth=Auth.Token(token), per_page=100)
    reds = red_repos(load_yaml(Path(args.triage)))
    sys.stderr.write(f"Scanning issues across {len(registry)} repo(s)…\n")

    repos: list[dict] = []
    skipped: dict[str, list[str]] = {}
    for project in registry:
        nwo = actions_analytics.owner_repo(project.get("repo_url", "") or "")
        if not nwo:
            continue
        try:
            rec, why = collect_repo(gh, project, cfg, reds)
        except Exception as exc:  # one bad repo must never sink the sweep
            sys.stderr.write(f"    ! {nwo}: {type(exc).__name__}: {exc}\n")
            rec, why = None, "error"
        if rec is None:
            skipped.setdefault(why, []).append(nwo)
            continue
        repos.append(rec)
        if rec["issues"] or rec["prs"]:
            sys.stderr.write(f"  · {nwo}: {len(rec['issues'])} issue(s), "
                             f"{len(rec['prs'])} pipeline PR(s)\n")
    for why, nwos in sorted(skipped.items()):
        sys.stderr.write(f"  ~ {len(nwos)} repo(s) skipped ({why})\n")

    queues = build_queues(repos, cfg)
    # Gap analysis needs each issue's comment history; run it only over the two
    # capped issue queues so the API cost tracks the queue, not the backlog.
    enrich_candidates(gh, queues["intake"] + queues["implement"], cfg)
    # Evidence caps apply after enrichment, once we know who actually needs one.
    need_ev = [c for c in queues["intake"] if c.get("needs_evidence")]
    for c in need_ev[cfg["evidence"]["max_runs"]:]:
        c["needs_evidence"] = False
        c["evidence_deferred"] = True

    counts = {"repos": len(repos),
              "open_issues": sum(len(r["issues"]) for r in repos)}
    out_dir = Path(args.workorder_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "issue-workorder-t1.md").write_text(render_t1(queues["intake"], cfg, counts))
    (out_dir / "issue-workorder-t2.md").write_text(render_t2(queues["implement"], cfg, counts))
    (out_dir / "issue-workorder-t3.md").write_text(render_t3(queues["complete"], cfg, counts))

    report = build_report(repos, queues, cfg, skipped)
    if not args.no_snapshot:
        out = Path(args.out)
        out.parent.mkdir(parents=True, exist_ok=True)
        with out.open("w") as fh:
            fh.write(GENERATED_HEADER)
            yaml.safe_dump(report, fh, sort_keys=False, allow_unicode=True)
        sys.stderr.write(f"Wrote {out}\n")

    for name, key in (("intake", "intake"), ("implement", "implement"),
                      ("complete", "complete")):
        n = len(queues[key])
        emit_output(f"{name}_count", n)
        emit_output(f"has_{name}", "true" if n else "false")
    emit_output("evidence_count", sum(1 for c in queues["intake"]
                                      if c.get("needs_evidence")))
    emit_output("evidence_targets", json.dumps(
        [{"nwo": c["nwo"], "number": c["number"], "ref": c["default_branch"],
          "slug": f"{c['nwo'].split('/')[-1]}-{c['number']}"}
         for c in queues["intake"] if c.get("needs_evidence")]))

    t = report["totals"]
    sys.stderr.write(
        f"issue-pipeline: {t['open_issues']} open issue(s) · stages "
        f"{t['stages']} · queued T1={t['queued_intake']} "
        f"T2={t['queued_implement']} T3={t['queued_complete']} → {out_dir}\n")
    if args.print:
        for tier, key in ((1, "intake"), (2, "implement"), (3, "complete")):
            for c in queues[key]:
                sys.stdout.write(
                    f"T{tier}  {c.get('priority', '--'):<3} "
                    f"{c['nwo']}#{c['number']}  {c['title'][:70]}\n")
    return 0


def load_registry(path: Path) -> list[dict]:
    with path.open() as fh:
        return yaml.safe_load(fh) or []


def add_arguments(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("--out", default=str(OUT_DEFAULT), metavar="PATH",
                        help="snapshot output (default _data/issue_pipeline.yml, committed)")
    parser.add_argument("--workorder-dir", default=str(REPO_ROOT), metavar="DIR",
                        help="where to write the three tier work orders (default repo root)")
    parser.add_argument("--config", default=str(FLEET), metavar="PATH",
                        help="fleet config (default _data/fleet.yml)")
    parser.add_argument("--registry", default=str(REGISTRY), metavar="PATH",
                        help="project registry (default _data/projects.yml)")
    parser.add_argument("--triage", default=str(TRIAGE), metavar="PATH",
                        help="triage snapshot used for the repo-is-red signal")
    parser.add_argument("--repos", default="", metavar="LIST",
                        help="comma-separated owner/repo, slug, or name filter")
    parser.add_argument("--hub", default="", metavar="OWNER/REPO",
                        help="override the control-plane repo")
    parser.add_argument("--max-intake", type=int, default=None, metavar="N")
    parser.add_argument("--max-implement", type=int, default=None, metavar="N")
    parser.add_argument("--max-complete", type=int, default=None, metavar="N")
    parser.add_argument("--no-snapshot", action="store_true",
                        help="build the work orders without rewriting the committed YAML")
    parser.add_argument("--sync-labels", action="store_true",
                        help="create/refresh the pipeline's label taxonomy in every target repo")
    parser.add_argument("--apply", action="store_true",
                        help="with --sync-labels, actually write (default dry-run)")
    parser.add_argument("--force", action="store_true",
                        help="run even when issue_pipeline.enabled is false")
    parser.add_argument("--print", action="store_true",
                        help="also print the queues to stdout")
    parser.set_defaults(func=run)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="issue-pipeline", description=__doc__)
    add_arguments(parser)
    args = parser.parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    raise SystemExit(main())
