#!/usr/bin/env bash
#
# audit-git-hooks.sh
#
# Answers the "Husky vs. pre-commit" question for this repository by running
# the concrete checks that determine which hook manager is actually live.
#
# Background:
#   * Husky installs by setting `core.hooksPath` to `.husky`.
#   * The `pre-commit` tool writes its shim into the default hooks directory
#     (usually `.git/hooks`).
#   * Setting `core.hooksPath` makes Git ignore the default hooks directory
#     entirely. So only ONE of the two can be in effect at a time, and
#     whichever installer ran last wins. A repo that carries config for both
#     will behave differently per clone depending on whether a contributor ran
#     `npm install` or `pre-commit install` -- a common cause of inconsistent
#     formatting.
#
# Usage:
#   bash scripts/audit-git-hooks.sh
#   # or, once the file has its executable bit set:
#   ./scripts/audit-git-hooks.sh
#
# This script is READ-ONLY: it never installs, uninstalls, or rewrites config.
# It always exits 0 so it is safe to run in CI as a diagnostic rather than a
# gate.
#
# `set -e` is intentionally NOT used: we want every check to run and report,
# even when earlier ones find nothing.
set -u

PRECOMMIT_MARKER="generated by pre-commit"

say()  { printf '%s\n' "$*"; }
head2() { printf '\n%s\n' "$*"; printf '%s\n' "------------------------------------------------------------"; }
yes_()  { printf '  [yes] %s\n' "$*"; }
no_()   { printf '  [ no] %s\n' "$*"; }
warn_() { printf '  [ !!] %s\n' "$*"; }
info_() { printf '       %s\n' "$*"; }

# --------------------------------------------------------------------------
# 0. Locate the repository
# --------------------------------------------------------------------------
if ! command -v git >/dev/null 2>&1; then
  say "ERROR: git not found on PATH; cannot audit."
  exit 0
fi

REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || true)"
if [ -z "$REPO_ROOT" ]; then
  say "ERROR: not inside a Git work tree; run this from the repository."
  exit 0
fi
cd "$REPO_ROOT" || exit 0

say "Git hook manager audit"
say "repository root: $REPO_ROOT"

# --------------------------------------------------------------------------
# 1. core.hooksPath -- the switch that decides who wins
# --------------------------------------------------------------------------
head2 "1. core.hooksPath"

# `git config --get` exits non-zero when the key is unset; swallow that.
HOOKS_PATH="$(git config --get core.hooksPath 2>/dev/null || true)"

# Resolve the directory Git will actually consult. Using `--git-path` keeps us
# correct inside worktrees and submodules, where `.git` is a file.
EFFECTIVE_HOOKS_DIR="$(git rev-parse --git-path hooks 2>/dev/null || true)"
[ -n "$EFFECTIVE_HOOKS_DIR" ] || EFFECTIVE_HOOKS_DIR=".git/hooks"

if [ -n "$HOOKS_PATH" ]; then
  yes_ "core.hooksPath is set to: $HOOKS_PATH"
  info_ "Git will look for hooks there and IGNORE $EFFECTIVE_HOOKS_DIR."
else
  no_ "core.hooksPath is not set."
  info_ "Git will use the default hooks directory: $EFFECTIVE_HOOKS_DIR"
fi

# --------------------------------------------------------------------------
# 2. Husky artifacts
# --------------------------------------------------------------------------
head2 "2. Husky (.husky/)"

HUSKY_DIR_PRESENT=0
HUSKY_HOOK_PRESENT=0
HUSKY_HOOK_EXEC=0

if [ -d ".husky" ]; then
  HUSKY_DIR_PRESENT=1
  yes_ ".husky/ exists"
  ls -l .husky/ 2>/dev/null | sed 's/^/       /'

  if [ -f ".husky/pre-commit" ]; then
    HUSKY_HOOK_PRESENT=1
    yes_ ".husky/pre-commit exists"
    if [ -x ".husky/pre-commit" ]; then
      HUSKY_HOOK_EXEC=1
      yes_ ".husky/pre-commit is executable"
    else
      warn_ ".husky/pre-commit is NOT executable -- Git will refuse to run it."
      info_ "Fix: chmod +x .husky/pre-commit && git update-index --chmod=+x .husky/pre-commit"
    fi
  else
    no_ ".husky/pre-commit does not exist"
  fi
else
  no_ ".husky/ does not exist"
fi

# --------------------------------------------------------------------------
# 3. Root package.json -- does anything try to install Husky?
# --------------------------------------------------------------------------
head2 "3. Root package.json prepare script"

PKG_HUSKY_PREPARE=0
if [ -f "package.json" ]; then
  yes_ "package.json exists at the repository root"
  # Deliberately a grep, not a JSON parse, so this script needs no jq/node.
  if grep -n '"prepare"' package.json 2>/dev/null | grep -qi 'husky'; then
    PKG_HUSKY_PREPARE=1
    yes_ 'a "prepare" script referencing husky is present:'
    grep -n '"prepare"' package.json 2>/dev/null | sed 's/^/       /'
    info_ "This means `npm install` will (re)install Husky and set core.hooksPath."
  else
    no_ 'no "prepare" script referencing husky'
    if grep -qi '"husky"' package.json 2>/dev/null; then
      warn_ "husky appears in package.json but no prepare hook installs it:"
      grep -ni 'husky' package.json 2>/dev/null | sed 's/^/       /'
    fi
  fi
else
  no_ "no package.json at the repository root"
fi

# --------------------------------------------------------------------------
# 4. pre-commit framework artifacts
# --------------------------------------------------------------------------
head2 "4. pre-commit framework"

PRECOMMIT_SHIM=0
PRECOMMIT_CONFIG=0
MIRRORS_PRETTIER=0

DEFAULT_HOOK="$EFFECTIVE_HOOKS_DIR/pre-commit"
if [ -f "$DEFAULT_HOOK" ]; then
  yes_ "$DEFAULT_HOOK exists"
  ls -l "$DEFAULT_HOOK" 2>/dev/null | sed 's/^/       /'
  if grep -q "$PRECOMMIT_MARKER" "$DEFAULT_HOOK" 2>/dev/null; then
    PRECOMMIT_SHIM=1
    yes_ "it carries the pre-commit marker ('$PRECOMMIT_MARKER')"
  else
    no_ "it does NOT carry the pre-commit marker (hand-written or other tool)"
  fi
else
  no_ "$DEFAULT_HOOK does not exist"
fi

if [ -f ".pre-commit-config.yaml" ]; then
  PRECOMMIT_CONFIG=1
  yes_ ".pre-commit-config.yaml exists"
  if grep -qi 'mirrors-prettier' .pre-commit-config.yaml 2>/dev/null; then
    MIRRORS_PRETTIER=1
    yes_ "it includes a mirrors-prettier entry:"
    grep -ni 'mirrors-prettier' .pre-commit-config.yaml 2>/dev/null | sed 's/^/       /'
  else
    no_ "no mirrors-prettier entry"
  fi
else
  no_ ".pre-commit-config.yaml does not exist"
fi

# --------------------------------------------------------------------------
# 5. Verdict
# --------------------------------------------------------------------------
head2 "5. Verdict"

# Husky is live when core.hooksPath points at a directory that holds a runnable
# pre-commit hook. pre-commit is live only when core.hooksPath is unset AND the
# default hook carries its marker.
HUSKY_LIVE=0
if [ -n "$HOOKS_PATH" ] && [ -x "$HOOKS_PATH/pre-commit" ]; then
  HUSKY_LIVE=1
fi

PRECOMMIT_LIVE=0
if [ -z "$HOOKS_PATH" ] && [ "$PRECOMMIT_SHIM" -eq 1 ]; then
  PRECOMMIT_LIVE=1
fi

HUSKY_CONFIGURED=0
if [ "$HUSKY_DIR_PRESENT" -eq 1 ] || [ "$PKG_HUSKY_PREPARE" -eq 1 ]; then
  HUSKY_CONFIGURED=1
fi

PRECOMMIT_CONFIGURED=0
if [ "$PRECOMMIT_CONFIG" -eq 1 ] || [ "$PRECOMMIT_SHIM" -eq 1 ]; then
  PRECOMMIT_CONFIGURED=1
fi

if [ "$HUSKY_LIVE" -eq 1 ]; then
  say "VERDICT: HUSKY is live (core.hooksPath=$HOOKS_PATH, runnable pre-commit hook)."
elif [ "$PRECOMMIT_LIVE" -eq 1 ]; then
  say "VERDICT: PRE-COMMIT is live (core.hooksPath unset, marker found in $DEFAULT_HOOK)."
elif [ "$HUSKY_CONFIGURED" -eq 1 ] || [ "$PRECOMMIT_CONFIGURED" -eq 1 ]; then
  say "VERDICT: hook config is present but NOTHING is currently live in this clone."
  say "         Nobody ran the installer here, so no pre-commit hook fires."
else
  say "VERDICT: no Git hook manager is configured in this repository."
fi

if [ "$HUSKY_CONFIGURED" -eq 1 ] && [ "$PRECOMMIT_CONFIGURED" -eq 1 ]; then
  say ""
  say "CONFLICT: this repo carries config for BOTH Husky and pre-commit."
  say "          Only one can ever be live, and whichever installer ran last"
  say "          wins -- which differs per contributor. That is the likely"
  say "          source of inconsistent formatting. Pick one and delete the"
  say "          other's config."
fi

if [ "$HUSKY_HOOK_PRESENT" -eq 1 ] && [ "$HUSKY_HOOK_EXEC" -eq 0 ]; then
  say ""
  say "NOTE: .husky/pre-commit exists but is not executable, so even with"
  say "      core.hooksPath set it would silently not run."
fi

say ""
say "(read-only diagnostic; nothing was changed)"
exit 0
