#!/usr/bin/env python3
# ============================================================================
# File:          tools/fleet-compose.py
# Description:   Projects _data/ports.yml onto the fleet dev stack — generates
#                .env.fleet, the hub-owned compose/overrides/*.yml, and
#                compose.fleet.yml, and validates the whole allocation.
# Author:        bamr87
# Created:       2026-09-20
# Last Modified: 2026-09-20
# Version:       1.0.0
# Usage:
#   tools/fleet-compose.py check          # gate: bands, collisions, override staleness
#   tools/fleet-compose.py sync           # (re)generate .env.fleet + overrides + include
#   tools/fleet-compose.py env            # write .env.fleet only
#   tools/fleet-compose.py show [project] # print the allocation table
# ============================================================================
#
# WHY THIS EXISTS
#
# The submodules are separate repos; the hub cannot commit to them. But Compose
# `include:` accepts a LIST of paths — the first is the base, the rest are
# overrides — and resolves every relative path (build contexts above all)
# against the BASE file's directory. So the hub can remap a submodule's ports,
# container_name and networks from a file it owns, with the submodule's own
# docker-compose.yml untouched and still standalone-runnable.
#
# That is the whole trick. The generated overrides are a hub-side projection of
# _data/ports.yml, never hand-edited; when a submodule later adopts the
# parameterized form upstream, its override shrinks to nothing and is dropped.

import json
import os
import re
import sys
import argparse

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
# One port parser for the whole toolchain: the harmonizer that rewrites the
# submodules and this generator that overrides them must agree byte-for-byte on
# what `${BIND_HOST:-127.0.0.1}:${PORT:-5433}:5432` means.
from docker_harmonize import parse_port, rewrite_host_port_refs  # noqa: E402

try:
    import yaml
except ImportError:  # pragma: no cover - environment problem, not a code path
    sys.stderr.write(
        "fleet-compose: PyYAML is required (pip install pyyaml, or run inside devenv)\n")
    raise SystemExit(2)

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PORTS_YML = os.path.join(ROOT, "_data", "ports.yml")
OVERRIDE_DIR = os.path.join(ROOT, "compose", "overrides")
ENV_FILE = os.path.join(ROOT, ".env.fleet")
INCLUDE_FILE = os.path.join(ROOT, "compose.fleet.yml")

GENERATED = "# GENERATED by tools/fleet-compose.py from _data/ports.yml — do not hand-edit."

# Services the shared stack replaces: service name -> shared key in ports.yml.
# Only entries whose shared service is `default: true` are actually profiled
# out; the rest are merely deconflicted.
REPLACED_BY_SHARED = {"phoenix": "phoenix"}


# ---------------------------------------------------------------------------
# Loading
# ---------------------------------------------------------------------------
def load_registry():
    with open(PORTS_YML) as fh:
        return yaml.safe_load(fh) or {}


def submodule_present(pspec):
    """Is this project's compose file actually on disk?

    `gen_override()` returns None for BOTH "no override needed" and "submodule
    not checked out", and conflating the two was doubly wrong: CI checks out
    WITHOUT submodules, so every override read as stale and check (m) failed
    every PR — and `sync` in that state DELETED the 15 committed override files.
    """
    rel = (pspec or {}).get("compose")
    return bool(rel) and os.path.exists(os.path.join(ROOT, rel))


def load_compose(path):
    """Parse a submodule compose file. Missing is not fatal: a submodule can be
    un-checked-out, and the gate must still run in CI."""
    full = os.path.join(ROOT, path)
    if not os.path.exists(full):
        return None
    with open(full) as fh:
        try:
            return yaml.safe_load(fh) or {}
        except yaml.YAMLError as exc:
            raise SystemExit(f"fleet-compose: cannot parse {path}: {exc}")


# ---------------------------------------------------------------------------
# Validation
# ---------------------------------------------------------------------------
def validate(reg):
    """Return a list of problem strings. Empty list == the allocation is sound."""
    problems = []
    bands = reg.get("bands") or {}
    shared = reg.get("shared") or {}
    projects = reg.get("projects") or {}

    seen = {}   # port -> "project/service"

    def claim(port, who):
        if port in seen:
            problems.append(f"port {port} claimed twice: {seen[port]} and {who}")
        else:
            seen[port] = who

    # Shared services own their ports before anyone else.
    for name, spec in shared.items():
        for label, port in (spec.get("ports") or {}).items():
            claim(int(port), f"shared/{name}.{label}")

    for pname, pspec in projects.items():
        pspec = pspec or {}
        allocs = list((pspec.get("services") or {}).items())
        allocs += list((pspec.get("debug") or {}).items())

        for sname, alloc in allocs:
            alloc = alloc or {}
            port = alloc.get("port")
            band = alloc.get("band")
            if port is None:
                problems.append(f"{pname}/{sname}: no port")
                continue
            claim(int(port), f"{pname}/{sname}")

            # Band conformance — the point of having bands at all.
            if band not in bands:
                problems.append(f"{pname}/{sname}: unknown band '{band}'")
            else:
                lo, hi = bands[band]["range"]
                if not (lo <= int(port) <= hi):
                    problems.append(
                        f"{pname}/{sname}: port {port} outside band '{band}' [{lo}-{hi}]")

            if not alloc.get("var"):
                problems.append(f"{pname}/{sname}: no env var name")

            lr = alloc.get("livereload")
            if lr is not None:
                claim(int(lr), f"{pname}/{sname}.livereload")
                lo, hi = bands["livereload"]["range"]
                if not (lo <= int(lr) <= hi):
                    problems.append(
                        f"{pname}/{sname}: livereload {lr} outside band [{lo}-{hi}]")

        # `unique:` ports are declared-as-is; still claim them so a future
        # allocation cannot land on top of neo4j or ollama.
        for sname, ports in (pspec.get("unique") or {}).items():
            for port in ports:
                claim(int(port), f"{pname}/{sname} (unique)")

        # The compose file the allocation talks about must exist and must
        # actually define the services named.
        if pspec.get("host") == "compose":
            rel = pspec.get("compose")
            if not rel:
                problems.append(f"{pname}: host=compose but no `compose:` path")
                continue
            doc = load_compose(rel)
            if doc is None:
                continue  # submodule not checked out; not this gate's business
            defined = set((doc.get("services") or {}).keys())
            for sname, _ in allocs:
                if sname not in defined:
                    problems.append(
                        f"{pname}: '{sname}' allocated but not a service in {rel}"
                        f" (has: {', '.join(sorted(defined)) or 'none'})")

    return problems


def audit_submodule_ports(reg):
    """Report submodule compose files still publishing a hardcoded, contended
    port. Advisory: the hub override neutralizes it for the fleet stack, but it
    still collides for anyone running that repo standalone alongside another."""
    findings = []
    projects = reg.get("projects") or {}
    for pname, pspec in projects.items():
        pspec = pspec or {}
        if pspec.get("host") != "compose":
            continue
        doc = load_compose(pspec.get("compose") or "")
        if doc is None:
            continue
        for sname, svc in (doc.get("services") or {}).items():
            svc = svc or {}
            if svc.get("container_name"):
                findings.append(
                    f"{pname}/{sname}: sets container_name "
                    f"'{svc['container_name']}' (global to the daemon)")
            for entry in svc.get("ports") or []:
                published, target, _ = parse_port(entry)
                if published and "$" not in str(published):
                    findings.append(
                        f"{pname}/{sname}: hardcoded published port {published}"
                        f"->{target} (not env-overridable)")
    return findings


# ---------------------------------------------------------------------------
# Generation
# ---------------------------------------------------------------------------
def gen_env(reg):
    """The flat, namespaced env file every include entry reads."""
    lines = [
        GENERATED,
        "#",
        "# The fleet dev stack's port assignments, one namespaced variable per",
        "# allocation. Namespaced because the submodules' own names collide:",
        "# djangoerp and barodybroject both read POSTGRES_PORT, zer0-cms and",
        "# zer0-image-generator both read PORT. Sourced by compose.fleet.yml.",
        "#",
        "# Regenerate: tools/fleet-compose.py env",
        "",
    ]
    shared = reg.get("shared") or {}
    lines.append("# ---- shared services (one instance, hub-owned) ----")
    for name, spec in shared.items():
        for label, port in (spec.get("ports") or {}).items():
            var = f"FLEET_{name.upper()}_{label.upper()}_PORT"
            lines.append(f"{var}={port}")
    lines.append("")

    for pname, pspec in (reg.get("projects") or {}).items():
        pspec = pspec or {}
        allocs = list((pspec.get("services") or {}).items())
        allocs += list((pspec.get("debug") or {}).items())
        if not allocs:
            continue
        lines.append(f"# ---- {pname} ({pspec.get('host', '?')}) ----")
        for sname, alloc in allocs:
            alloc = alloc or {}
            lines.append(f"{alloc['var']}={alloc['port']}")
            if alloc.get("livereload") is not None:
                lines.append(
                    f"{alloc['var'].replace('_PORT', '')}_LIVERELOAD_PORT="
                    f"{alloc['livereload']}")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def gen_override(reg, pname, pspec):
    """Build one hub-owned override file, or None when the project needs none.

    One block per service. An earlier cut emitted a second block for a service
    that had both an allocation and a debug port, and YAML's last-key-wins
    silently threw the `!override` ports away — so every directive for a
    service is accumulated here and emitted exactly once.
    """
    doc = load_compose(pspec.get("compose") or "")
    if doc is None:
        return None
    defined = doc.get("services") or {}
    allocs = pspec.get("services") or {}
    debug = pspec.get("debug") or {}

    # service name -> {container_name, ports[list of str], profiles, why[list]}
    blocks = {}

    def block(name):
        return blocks.setdefault(
            name, {"container_name": None, "ports": None, "profiles": None,
                   "depends_on": None, "env_file": None, "env": None, "why": []})

    # Services the fleet stack must not start: superseded by a shared service,
    # or explicitly excluded by the registry (a production-only service, say).
    excluded = dict(pspec.get("exclude") or {})
    superseded = {
        s for s in defined
        if (reg.get("shared") or {}).get(REPLACED_BY_SHARED.get(s, ""), {}).get("default")
    } | set(excluded) & set(defined)

    # Which services actually need the SHARED network.
    #
    # Attaching everything to `fleet-net` looked harmless and was not: Docker
    # registers a container's SERVICE NAME as an alias on every network it
    # joins, so one shared network re-created the very collisions that running
    # each repo as its own compose project had just solved. `redis` resolved to
    # three containers, `jekyll` to four — and fredgar-ai's web reached
    # djangoerp's Postgres, failing with `password authentication failed for
    # user "fredgar"` against a database that was perfectly healthy.
    #
    # So membership is earned, not default: a service joins only if it talks to
    # a service the shared tier supersedes — by `depends_on` or by naming it in
    # its own environment (law-ai and bashos both hardcode
    # PHOENIX_COLLECTOR_ENDPOINT=http://phoenix:6006) — or if the registry opts
    # it in explicitly. Everything else stays on its project's own network,
    # where `db` and `redis` mean what that repo intends.
    needs_net = set()
    for sname, svc in defined.items():
        svc = svc or {}
        dep = svc.get("depends_on") or {}
        names = list(dep.keys()) if isinstance(dep, dict) else list(dep)
        if superseded & set(names):
            needs_net.add(sname)
            continue
        env = svc.get("environment") or {}
        values = env if isinstance(env, list) else [f"{k}={v}" for k, v in env.items()]
        if any(any(f"//{t}:" in str(v) or f"@{t}:" in str(v) for t in superseded)
               for v in values):
            needs_net.add(sname)
    for sname, alloc in (allocs or {}).items():
        if (alloc or {}).get("fleet_net"):
            needs_net.add(sname)
    needs_net &= set(defined)
    needs_net -= superseded

    # A repo that has adopted UPS-REPO-34 publishes
    # `127.0.0.1:${VAR:-<port>}:<target>`. The override for such a service is
    # redundant ONLY when VAR is the variable this registry allocates AND its
    # default is the allocated port — otherwise the hub must still override.
    #
    # Testing merely for "is it parameterized" was wrong and put five services
    # back on top of each other: the harmonizer parameterizes with the repo's
    # OWN historical default (correct for a standalone run), so barodybroject's
    # `${JEKYLL_PORT:-4002}` read .env.fleet's JEKYLL_PORT=4000 — the hub dash —
    # and djangoerp's `${DJANGO_PORT:-8000}` collided with devenv's MkDocs.
    def adopted_port_spec(sname, alloc):
        raw = ((defined.get(sname) or {}).get("ports")) or []
        if not raw:
            return False
        want_var, want_port = alloc["var"], str(alloc["port"])
        pubs = [parse_port(e)[0] for e in raw]
        pubs = [p for p in pubs if p is not None]
        if not pubs:
            return False
        m = re.fullmatch(r"\$\{([A-Za-z_][A-Za-z0-9_]*)(?::-(\d+))?\}", str(pubs[0]))
        return bool(m) and m.group(1) == want_var and (m.group(2) or want_port) == want_port

    adopted = {sname for sname, alloc in (allocs or {}).items()
               if sname in defined and adopted_port_spec(sname, alloc)}

    # host port -> (variable, fleet default) for every published port this
    # project's registry entries remap. Used below to repoint URLs that a
    # browser or a peer still aims at the OLD number.
    portmap = {}
    for sname, alloc in allocs.items():
        raw = [parse_port(e) for e in (((defined.get(sname) or {}).get("ports")) or [])]
        pubs = [x for x in raw if x[0] and str(x[0]).isdigit()]
        if pubs:
            portmap[str(pubs[0][0])] = (alloc["var"], alloc["port"])
        if alloc.get("livereload") is not None and len(pubs) > 1:
            portmap[str(pubs[1][0])] = (
                alloc["var"].replace("_PORT", "") + "_LIVERELOAD_PORT", alloc["livereload"])
    for sname, alloc in debug.items():
        raw = [parse_port(e) for e in (((defined.get(sname) or {}).get("ports")) or [])]
        for pub, target, _p in raw:
            if pub and str(pub).isdigit() and target == str(alloc.get("container_port", 5678)):
                portmap[str(pub)] = (alloc["var"], alloc["port"])

    for sname, alloc in allocs.items():
        svc = defined.get(sname)
        if svc is None:
            continue
        svc = svc or {}
        b = block(sname)

        # container_name is global to the daemon — the root cause of the
        # bamr87-wiki double-claim. Namespace it rather than dropping it so
        # `docker ps` still reads clearly.
        if svc.get("container_name"):
            b["container_name"] = f"fleet-{pname}-{sname}"

        if sname in adopted:
            continue

        parsed = [parse_port(e) for e in (svc.get("ports") or [])]
        ports = []
        primary_target = parsed[0][1] if parsed else str(alloc["port"])
        ports.append(
            f'      - "127.0.0.1:${{{alloc["var"]}:-{alloc["port"]}}}:{primary_target}"')
        consumed = 1
        if alloc.get("livereload") is not None and len(parsed) > 1:
            lr_target = parsed[1][1] or str(alloc["livereload"])
            lr_var = alloc["var"].replace("_PORT", "") + "_LIVERELOAD_PORT"
            ports.append(
                f'      - "127.0.0.1:${{{lr_var}:-{alloc["livereload"]}}}:{lr_target}"')
            consumed = 2
        # Remaining published ports pass through on loopback, EXCEPT a debugger
        # port, which the `debug:` allocation below owns.
        for published, target, proto in parsed[consumed:]:
            if target == "5678" and sname in debug:
                continue
            suffix = f"/{proto}" if proto and proto != "tcp" else ""
            ports.append(f'      - "127.0.0.1:{published}:{target}{suffix}"')
        b["ports"] = ports

    # Debug ports join the SAME service block. `!override` on a list means a
    # separate additive entry is not an option — it has to be one list.
    for sname, alloc in debug.items():
        if sname not in defined or sname in adopted:
            continue
        b = block(sname)
        if b["ports"] is None:
            # No allocation for this service: rebuild its published list so the
            # override stays a faithful replacement, not a truncation.
            b["ports"] = []
            for published, target, proto in (
                    parse_port(e) for e in (defined[sname] or {}).get("ports") or []):
                if target == str(alloc.get("container_port", 5678)):
                    continue
                suffix = f"/{proto}" if proto and proto != "tcp" else ""
                b["ports"].append(f'      - "127.0.0.1:{published}:{target}{suffix}"')
            if (defined[sname] or {}).get("container_name"):
                b["container_name"] = f"fleet-{pname}-{sname}"
        b["ports"].append(
            f'      - "127.0.0.1:${{{alloc["var"]}:-{alloc["port"]}}}:'
            f'{alloc.get("container_port", 5678)}"')
        b["why"].append("debugpy attach point (see .vscode/launch.json)")

    # Services the shared stack supersedes.
    for sname in defined:
        key = REPLACED_BY_SHARED.get(sname)
        if key and (reg.get("shared") or {}).get(key, {}).get("default"):
            b = block(sname)
            b["profiles"] = "[standalone]"
            b["ports"] = None
            b["why"].append(
                f"superseded by the shared fleet-{key}; reachable at its own "
                f"hostname through the fleet-net alias")
    for sname, reason in excluded.items():
        if sname not in defined:
            continue
        b = block(sname)
        b["profiles"] = "[standalone]"
        b["ports"] = None
        b["why"].append(f"excluded from the fleet stack: {reason}")

    # A service excluded by a profile cannot be the target of `depends_on` —
    # Compose rejects the whole project ("depends on undefined service"). So
    # every dependent has to drop the edge in the same override that profiles
    # the service out. law-ai's backend, worker and langgraph-api all wait on
    # its phoenix; the shared one is a sibling project, started separately.
    for sname, svc in defined.items():
        dep = (svc or {}).get("depends_on")
        if not dep:
            continue
        names = list(dep.keys()) if isinstance(dep, dict) else list(dep)
        dropped = [d for d in names if d in superseded]
        if not dropped:
            continue
        b = block(sname)
        kept = [d for d in names if d not in superseded]
        if isinstance(dep, dict):
            lines = []
            for d in kept:
                cond = (dep[d] or {}).get("condition", "service_started")
                lines.append(f"      {d}:")
                lines.append(f"        condition: {cond}")
            b["depends_on"] = ("map", lines)
        else:
            b["depends_on"] = ("list", [f"      - {d}" for d in kept])
        b["why"].append(
            f"depends_on: dropped {', '.join(dropped)} (superseded by the "
            f"shared service, which lives in another compose project)")

    # container_name is global to the DAEMON, so every service that sets one
    # has to be namespaced — not just the ones with a port allocation. A first
    # cut only renamed allocated services, which left aieo's qdrant/mcp-server/
    # mcp-audit holding unqualified global names.
    for sname, svc in defined.items():
        if (svc or {}).get("container_name"):
            block(sname)["container_name"] = f"fleet-{pname}-{sname}"

    # `unique:` ports are collision-free fleet-wide, but "unique" is not
    # "unmanaged": left alone they bind 0.0.0.0, which put neo4j, ollama and
    # qdrant on every interface of the machine. Rebind to loopback, same number.
    for sname, ports in (pspec.get("unique") or {}).items():
        svc = defined.get(sname)
        if svc is None:
            continue
        b = block(sname)
        if b["ports"] is not None:
            continue
        rebound = []
        for published, target, proto in (
                parse_port(e) for e in (svc or {}).get("ports") or []):
            suffix = f"/{proto}" if proto and proto != "tcp" else ""
            rebound.append(
                f'      - "127.0.0.1:{published or target}:{target}{suffix}"')
        if rebound:
            b["ports"] = rebound
            b["why"].append("bound to loopback (was published on every interface)")

    # Browser- and peer-facing URLs that still name a host port this file has
    # just remapped. Remapping law-ai's backend from 8000 to 8110 leaves
    # NEXT_PUBLIC_WS_URL=ws://localhost:8000 pointing at nothing; ai-seed's
    # VITE_API_URL and fredgar's CORS allow-list have the same shape. Compose
    # merges `environment` by key, so only the changed entries are emitted.
    if portmap:
        for sname, svc in defined.items():
            if sname in excluded or sname in superseded:
                continue
            env = (svc or {}).get("environment")
            if not env:
                continue
            pairs = (list(env.items()) if isinstance(env, dict)
                     else [tuple(str(e).split("=", 1)) for e in env if "=" in str(e)])
            changed = {}
            for k, v in pairs:
                new = rewrite_host_port_refs(str(v), portmap)
                if new != str(v):
                    changed[k] = new
            if changed:
                b = block(sname)
                b["env"] = changed
                b["why"].append("environment: URLs repointed at the remapped host port(s)")

    # A missing `env_file` is fatal unless the entry is the long form with
    # `required: false`. it-journey names a `.env` that a fresh clone does not
    # have, so the whole project refuses to resolve. law-ai already uses the
    # long form; this gives everyone else the same tolerance without an
    # upstream commit.
    compose_dir = os.path.dirname(os.path.join(ROOT, pspec.get("compose") or ""))
    for sname, svc in defined.items():
        ef = (svc or {}).get("env_file")
        if not ef:
            continue
        entries = ef if isinstance(ef, list) else [ef]
        rewritten, missing = [], False
        for e in entries:
            path = e.get("path") if isinstance(e, dict) else e
            required = e.get("required", True) if isinstance(e, dict) else True
            if required and not os.path.exists(os.path.join(compose_dir, str(path))):
                missing = True
            rewritten.append(f"      - path: {path}\n        required: false")
        if missing:
            b = block(sname)
            b["env_file"] = rewritten
            b["why"].append(
                "env_file: made optional (named file absent from a fresh clone)")

    if not blocks:
        return None

    body = []
    for sname, b in blocks.items():
        chunk = [f"  {sname}:"]
        for why in b["why"]:
            chunk.append(f"    # {why}")
        if b["container_name"]:
            chunk.append(f"    container_name: {b['container_name']}")
        if b["profiles"]:
            chunk.append(f"    profiles: {b['profiles']}")
        if b["env"]:
            chunk.append("    environment:")
            for k, v in b["env"].items():
                chunk.append(f"      {k}: {json.dumps(v, ensure_ascii=False)}")
        if b["env_file"] is not None:
            chunk.append("    env_file: !override")
            chunk.extend(b["env_file"])
        if b["depends_on"] is not None:
            kind, lines = b["depends_on"]
            if lines:
                chunk.append("    depends_on: !override")
                chunk.extend(lines)
            else:
                chunk.append("    depends_on: !reset []")
        if b["ports"] is not None:
            if b["ports"]:
                chunk.append("    ports: !override")
                chunk.extend(b["ports"])
            else:
                chunk.append("    ports: !reset []")
        # Additive on purpose: `!override` here would drop a project's own
        # network (barodybroject's barody-network) and break its internal DNS.
        if sname in needs_net:
            chunk.append("    networks:")
            chunk.append("      - fleet-net")
        body.append("\n".join(chunk))

    header = [
        GENERATED,
        f"# Hub-side overrides for projects/{pname} — the submodule's own",
        "# docker-compose.yml is untouched and still runs standalone.",
        "#",
        "# `!override` replaces the ports list rather than appending to it, which",
        "# is what lets a hardcoded `8000:8000` become a fleet allocation with no",
        "# upstream commit. `networks:` stays additive so the project keeps its own.",
        "",
        "services:",
    ]
    tail = ["", "networks:", "  fleet-net:", "    external: true", ""] \
        if needs_net else [""]
    return "\n".join(header) + "\n" + "\n".join(body) + "\n" + "\n".join(tail)


def gen_hub_override(reg):
    """devenv's port list for FLEET mode, derived from the registry.

    The hub's docker-compose.yml publishes devenv as broad ranges
    (`4010-4020`, `35730-35740`) from when every submodule server was an
    `exec devenv` away. Now that it-journey, zer0-mistakes, bashconsultants and
    the zer0-pages pair each run their own compose project, those ranges sit on
    top of five projects' real ports — which is a bind failure at `up`, not a
    warning. So in fleet mode devenv publishes EXACTLY the allocations whose
    `host:` is devenv, and nothing else. Plain `docker compose up -d` is
    untouched and keeps the broad ranges.
    """
    projects = reg.get("projects") or {}
    lines = []
    hub = (projects.get("bamr87") or {}).get("services") or {}
    for sname, alloc in hub.items():
        # Only the ports devenv itself serves. A hub entry that names a real
        # compose service (console, mkdocs) publishes its own, and having devenv
        # claim it too is a bind conflict inside one compose project.
        if (alloc or {}).get("served_by") != "devenv":
            continue
        lines.append(
            f'      - "127.0.0.1:${{{alloc["var"]}:-{alloc["port"]}}}:{alloc["port"]}"')

    for pname, pspec in projects.items():
        pspec = pspec or {}
        if pspec.get("host") != "devenv":
            continue
        for sname, alloc in (pspec.get("services") or {}).items():
            lines.append(
                f'      - "127.0.0.1:${{{alloc["var"]}:-{alloc["port"]}}}:{alloc["port"]}"'
                f'   # {pname}')
            if alloc.get("livereload") is not None:
                lr_var = alloc["var"].replace("_PORT", "") + "_LIVERELOAD_PORT"
                lines.append(
                    f'      - "127.0.0.1:${{{lr_var}:-{alloc["livereload"]}}}'
                    f':{alloc["livereload"]}"   # {pname} livereload')

    return "\n".join([
        GENERATED,
        "# devenv's FLEET-mode port map: exactly the allocations hosted inside",
        "# devenv, replacing the broad ranges the hub's own compose publishes.",
        "#",
        "# A server started with `docker compose exec devenv` must bind the same",
        "# number inside the container as the one published here, so every entry",
        "# is `N:N` — that is what the launch.json devenv configs pass as --port.",
        "",
        "services:",
        "  devenv:",
        "    ports: !override",
        *lines,
        "",
    ])


def gen_include(reg):
    """The hub's own stack plus the shared-services layer.

    NOT the submodules. Compose `include:` merges every included file into ONE
    project namespace, and across 16 independent repos the service names
    collide hard — `jekyll` is claimed by 5 projects, `redis` by 4, `worker`,
    `frontend` and `web` by 3 each. Merging them would silently fuse
    law-ai's frontend with ai-seed's. So each submodule runs as its OWN compose
    project, joined to the others by the external `fleet-net`; tools/fleet-dev.sh
    is the one command that drives them. See docs/FLEET-COMPOSE.md.
    """
    projects = [p for p, spec in (reg.get("projects") or {}).items()
                if (spec or {}).get("host") == "compose"]
    return "\n".join([
        GENERATED,
        "#",
        "# compose.fleet.yml — the HUB half of the fleet dev stack: the hub's own",
        "# services plus the shared-services layer that publishes `fleet-net` and",
        "# the Phoenix alias every submodule's tracing points at.",
        "#",
        "#   tools/fleet-dev.sh up hub          # this file",
        f"#   tools/fleet-dev.sh up law-ai       # one of the {len(projects)} submodule projects",
        "#   tools/fleet-dev.sh up --all        # everything",
        "#",
        "# The submodules are deliberately NOT included here. `include:` merges",
        "# into a single project namespace and their service names collide —",
        "# `jekyll` is claimed by 5 repos, `redis` by 4 — so each runs as its own",
        "# compose project on the shared network instead. docs/FLEET-COMPOSE.md",
        "# has the reasoning; tools/fleet-dev.sh is the single entry point.",
        "",
        "name: fleet-hub",
        "",
        "include:",
        "  - path:",
        "      - docker-compose.yml",
        "      - compose/shared.yml",
        "      - compose/overrides/hub.yml",
        "    env_file: .env.fleet",
        "",
    ])


# ---------------------------------------------------------------------------
# Commands
# ---------------------------------------------------------------------------
def cmd_check(reg, args):
    problems = validate(reg)
    for p in problems:
        print(f"  ✗ {p}")

    stale, unchecked = [], []
    for pname, pspec in (reg.get("projects") or {}).items():
        pspec = pspec or {}
        if pspec.get("host") != "compose":
            continue
        if not submodule_present(pspec):
            # Cannot regenerate what is not on disk, so staleness is unknowable
            # here. This is the NORMAL case in CI.
            unchecked.append(pname)
            continue
        want = gen_override(reg, pname, pspec)
        path = os.path.join(OVERRIDE_DIR, f"{pname}.yml")
        have = open(path).read() if os.path.exists(path) else None
        if want is None and have is None:
            continue
        if want != have:
            stale.append(pname)
    if stale:
        problems.append(f"stale overrides: {', '.join(stale)}")
        print(f"  ✗ stale compose/overrides: {', '.join(stale)}"
              f" — run tools/fleet-compose.py sync")
    if unchecked:
        print(f"  ! {len(unchecked)} override(s) not verified "
              f"(submodule not checked out) — normal in CI")

    hub_ov = os.path.join(OVERRIDE_DIR, "hub.yml")
    if os.path.exists(hub_ov) and open(hub_ov).read() != gen_hub_override(reg):
        problems.append("stale compose/overrides/hub.yml")
        print("  ✗ compose/overrides/hub.yml is stale — run tools/fleet-compose.py sync")

    if os.path.exists(INCLUDE_FILE) and open(INCLUDE_FILE).read() != gen_include(reg):
        problems.append("stale compose.fleet.yml")
        print("  ✗ compose.fleet.yml is stale — run tools/fleet-compose.py sync")

    if args.audit:
        for f in audit_submodule_ports(reg):
            print(f"  ! {f}")

    if not problems:
        total = sum(len((p or {}).get("services") or {})
                    for p in (reg.get("projects") or {}).values())
        print(f"  ✓ {total} allocations across "
              f"{len(reg.get('projects') or {})} projects — no collisions, all in band")
    return 1 if problems else 0


def cmd_sync(reg, args):
    os.makedirs(OVERRIDE_DIR, exist_ok=True)
    written, skipped = [], []

    with open(ENV_FILE, "w") as fh:
        fh.write(gen_env(reg))
    written.append(".env.fleet")

    for pname, pspec in (reg.get("projects") or {}).items():
        pspec = pspec or {}
        if pspec.get("host") != "compose":
            continue
        path = os.path.join(OVERRIDE_DIR, f"{pname}.yml")
        if not submodule_present(pspec):
            # NEVER delete a committed override just because the submodule is not
            # checked out — `sync` on a fresh clone would wipe all of them.
            if os.path.exists(path):
                skipped.append(pname)
            continue
        text = gen_override(reg, pname, pspec)
        if text is None:
            if os.path.exists(path):
                os.remove(path)
                written.append(f"compose/overrides/{pname}.yml (removed)")
            continue
        with open(path, "w") as fh:
            fh.write(text)
        written.append(f"compose/overrides/{pname}.yml")

    with open(os.path.join(OVERRIDE_DIR, "hub.yml"), "w") as fh:
        fh.write(gen_hub_override(reg))
    written.append("compose/overrides/hub.yml")

    with open(INCLUDE_FILE, "w") as fh:
        fh.write(gen_include(reg))
    written.append("compose.fleet.yml")

    for w in written:
        print(f"  wrote {w}")
    if skipped:
        print(f"  kept {len(skipped)} override(s) untouched "
              f"(submodule not checked out): {', '.join(skipped)}")
    return 0


def cmd_env(reg, args):
    with open(ENV_FILE, "w") as fh:
        fh.write(gen_env(reg))
    print(f"  wrote .env.fleet")
    return 0


def cmd_show(reg, args):
    projects = reg.get("projects") or {}
    if args.project:
        projects = {k: v for k, v in projects.items() if k == args.project}
        if not projects:
            print(f"no such project: {args.project}")
            return 1

    print(f"{'PROJECT':24} {'SERVICE':18} {'PORT':>6}  {'BAND':10} HOST")
    print("-" * 78)
    for name, spec in (reg.get("shared") or {}).items():
        for label, port in (spec.get("ports") or {}).items():
            flag = "shared" if spec.get("default") else "shared(opt-in)"
            print(f"{'(shared)':24} {name + '.' + label:18} {port:>6}  {'-':10} {flag}")
    print("-" * 78)
    for pname, pspec in projects.items():
        pspec = pspec or {}
        host = pspec.get("host", "?")
        rows = list((pspec.get("services") or {}).items())
        rows += [(f"{k} (debug)", v) for k, v in (pspec.get("debug") or {}).items()]
        for sname, alloc in rows:
            alloc = alloc or {}
            lr = f"  +lr {alloc['livereload']}" if alloc.get("livereload") else ""
            print(f"{pname:24} {sname:18} {alloc.get('port', '?'):>6}  "
                  f"{alloc.get('band', '-'):10} {host}{lr}")
    return 0


def main():
    ap = argparse.ArgumentParser(description="Project _data/ports.yml onto the fleet dev stack")
    sub = ap.add_subparsers(dest="cmd")

    c = sub.add_parser("check", help="gate the allocation and the generated files")
    c.add_argument("--audit", action="store_true",
                   help="also report submodules still publishing hardcoded ports")
    sub.add_parser("sync", help="regenerate .env.fleet, overrides and compose.fleet.yml")
    sub.add_parser("env", help="regenerate .env.fleet only")
    s = sub.add_parser("show", help="print the allocation table")
    s.add_argument("project", nargs="?")

    args = ap.parse_args()
    if not args.cmd:
        ap.print_help()
        return 0

    reg = load_registry()
    return {"check": cmd_check, "sync": cmd_sync,
            "env": cmd_env, "show": cmd_show}[args.cmd](reg, args)


if __name__ == "__main__":
    raise SystemExit(main())
