#!/usr/bin/env python3
"""
File: tools/gen-specs-data.py
Description: Generate _data/specs.yml — the machine-readable Universal Project
             Standard — from the requirement tables in specs/*.md, so prose and
             data can never disagree. Mirrors gen-projects-schema.py's shape.
Author: bamr87
Created: 2026-09-01
Last Modified: 2026-09-01
Version: 0.1.0
Usage: python3 tools/gen-specs-data.py [--check]
       --check  exit 1 when the committed file is stale (drift-gate style)
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SPECS = ROOT / "specs"
OUT = ROOT / "_data" / "specs.yml"

AREAS = {
    "REPO": ("REPOSITORY.md", "Repository layout and required files"),
    "AGENT": ("AGENT-CONTEXT.md", "Agent context"),
    "QA": ("QUALITY.md", "Quality gates"),
    "FE": ("FRONTEND.md", "Frontend: design system, core components, UX standards"),
    "FB": ("FEEDBACK.md", "The universal feedback component"),
    "BE": ("BACKEND.md", "HTTP API conventions and the client contract"),
    "OPS": ("OPERATIONS.md", "Configuration, observability, security, data"),
}
KINDS = ["all", "site", "app", "api", "lib", "cli", "ext", "content", "fork"]
ROW_RE = re.compile(r"^\|\s*(UPS-[A-Z]+-\d+)\s*\|(.*)\|\s*$")


def split_cells(line: str) -> list[str]:
    # Split on unescaped pipes, then unescape.
    parts = re.split(r"(?<!\\)\|", line.strip().strip("|"))
    return [p.strip().replace("\\|", "|") for p in parts]


def parse_applies(text: str) -> tuple[list[str], list[str]]:
    """'app, api (server-rendered)' -> (['app','api'], ['api (server-rendered)'])"""
    kinds, notes = [], []
    for chunk in text.split(","):
        chunk = chunk.strip()
        if not chunk:
            continue
        m = re.match(r"^(all except|all)\s*(.*)$", chunk)
        if m and m.group(1) == "all except":
            kinds.append("all")
            notes.append(chunk)
            continue
        word = chunk.split()[0].strip("`")
        if word in KINDS:
            kinds.append(word)
            if len(chunk.split()) > 1:
                notes.append(chunk)
        else:
            notes.append(chunk)
    return kinds or ["all"], notes


def yq(s: str) -> str:
    """Quote a YAML scalar safely (double-quoted, escaped)."""
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def render() -> str:
    lines = [
        "# =============================================================================",
        "# _data/specs.yml — the Universal Project Standard, machine-readable",
        "# =============================================================================",
        "# GENERATED by tools/gen-specs-data.py from the requirement tables in specs/*.md.",
        "# Do not hand-edit: change the spec table, then regenerate. The drift gate's",
        "# `--check` mode fails when this file is stale.",
        "#",
        "# Per requirement: id, area, level (MUST|SHOULD|MAY), applies (stack kinds from",
        "# specs/STACKS.md; `all` binds every kind, notes carry exceptions), the prose",
        "# requirement, what satisfies it, and the kit/tool that seeds it (`—` = gap).",
        "# Consumed by: the UPS audit (dash audit --spec, roadmap) and the dash site.",
        "# =============================================================================",
        "",
        'version: "1.0"',
        "status: draft",
        "kinds: [" + ", ".join(KINDS) + "]",
        "areas:",
    ]
    reqs: list[dict] = []
    for area, (fname, title) in AREAS.items():
        lines.append(f"  - id: {area}")
        lines.append(f"    file: specs/{fname}")
        lines.append(f"    title: {yq(title)}")
        section = ""
        for raw in (SPECS / fname).read_text(encoding="utf-8").splitlines():
            if raw.startswith("## "):
                section = raw[3:].strip()
                continue
            m = ROW_RE.match(raw)
            if not m:
                continue
            cells = split_cells(raw)
            rid = cells[0]
            if not rid.startswith(f"UPS-{area}-"):
                raise SystemExit(f"{fname}: row {rid} does not belong to area {area}")
            # Two table shapes: 6 cols (id level applies requirement satisfied seed)
            # or 7 cols with a `component` column (FE core component set).
            # The FE "Core component set" table is (id level applies component requirement seed);
            # every other table is (id level applies requirement satisfied seed).
            if fname == "FRONTEND.md" and section == "Core component set" and len(cells) == 6:
                level, applies, component, requirement, seed = cells[1:6]
                satisfied = ""
            elif len(cells) == 6:
                level, applies, requirement, satisfied, seed = cells[1:6]
                component = ""
            else:
                raise SystemExit(f"{fname}: row {rid} has {len(cells)} cells")
            kinds, notes = parse_applies(applies)
            reqs.append(dict(id=rid, area=area, section=section, level=level.strip("*"), kinds=kinds,
                             notes=notes, component=component, requirement=requirement,
                             satisfied=satisfied, seed=seed))
    seen = set()
    for r in reqs:
        if r["id"] in seen:
            raise SystemExit(f"duplicate id {r['id']}")
        seen.add(r["id"])
    lines.append("requirements:")
    for r in reqs:
        lines.append(f"  - id: {r['id']}")
        lines.append(f"    area: {r['area']}")
        lines.append(f"    section: {yq(r['section'])}")
        lines.append(f"    level: {r['level']}")
        lines.append("    applies: [" + ", ".join(r["kinds"]) + "]")
        if r["notes"]:
            lines.append("    applies_notes: [" + ", ".join(yq(n) for n in r["notes"]) + "]")
        if r["component"]:
            lines.append(f"    component: {yq(r['component'].strip('*'))}")
        lines.append(f"    requirement: {yq(r['requirement'])}")
        if r["satisfied"]:
            lines.append(f"    satisfied_by: {yq(r['satisfied'])}")
        lines.append(f"    seed: {yq(r['seed'])}")
        lines.append(f"    gap: {'true' if ('gap' in r['seed'] or r['seed'].strip() == '—') else 'false'}")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    text = render()
    if "--check" in sys.argv:
        if not OUT.exists() or OUT.read_text(encoding="utf-8") != text:
            print(f"STALE: {OUT.relative_to(ROOT)} — run tools/gen-specs-data.py", file=sys.stderr)
            return 1
        print(f"fresh: {OUT.relative_to(ROOT)}")
        return 0
    OUT.write_text(text, encoding="utf-8")
    n = text.count("\n  - id: UPS-")
    print(f"wrote {OUT.relative_to(ROOT)} ({n} requirements)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
